### ISSUE TITLE
报错“Json解析不合常规”

### ISSUE THREAD

**Issue by Gaowkang** [binary-husky/chatgpt_academic#103]
请问报错“Json解析不合常规”如何解决？

**Comment by Wangjiafeng2** [comment]
ERROR: No matching distribution found for orjson，如何解决呀

**Comment by MartinTJU** [comment]
每次api都被封是为什么呢

**Comment by jacyhen** [comment]
可能是账户问题，我发现我朋友帮我注册的账号没有API免费额度，而api是要花钱才能用的

**Comment by binary-husky** [comment]
看message呀，翻译一下就知道了。

比如 @SunShida 你的报错是提示违反openai的规定Your access was terminated due to violation of our policies

之前还有几位提示check your plan and billing details的，是要你给openai充钱的
