### ISSUE TITLE
请问上传时解析我的文档为private_load如何解决？

### ISSUE THREAD

**Issue by Maxiah** [binary-husky/chatgpt_academic#109]
我本来以为是我从OneDrive上传的原因，但是从D盘上传结果还是一样的。

> 作为一名中文学术论文写作改进助理，你的任务是改进所提供文本的拼写、语法、清晰、简洁和整体可读性，同时分解长句，减少重复，并提供改进建议。请只提供文本的更正版本，避免包括解释。请编辑以下文本：`private_upload/2023-03-29-22-08-42

> 同样地，我无法编辑你提供的文本，因为它是一个私人上传文件。请提供正确的文本，以便我可以为您提供需要的帮助。`

**Comment by Maxiah** [comment]
已解决哈哈哈，没有注意右上角，抱歉

**Comment by binary-husky** [comment]
抱歉，红色的函数模块才能接收文件作为参数

**Comment by Maxiah** [comment]
> 

thx
