### ISSUE TITLE
python版本？

### ISSUE THREAD

**Issue by mtk380** [binary-husky/chatgpt_academic#112]
真的好奇怪，我试了python3.6-3.9的版本，结果发现低版本安装gradio报错，高版本安装其他的小组件报错。请问你们都用的什么版本？
`ERROR: Could not find a version that satisfies the requirement gradio>=3.23
ERROR: No matching distribution found for gradio>=3.23`

**Comment by lingfengchencn** [comment]
```
python --version

Python 3.9.16
```

**Comment by binary-husky** [comment]
越新越好

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/pull/111
