### ISSUE TITLE
No module named 'fsspec.asyn'

### ISSUE THREAD

**Issue by Boltzxuann** [binary-husky/chatgpt_academic#114]
运行main.py时报错“No module named 'fsspec.asyn'”，是咋回事？

**Comment by Misaka89535** [comment]
同问，在这里卡住了

**Comment by fanfoxle** [comment]
You may be using an older version of fsspec.
Try to upgrade it by implenting "pip install --upgrade fsspec"

**Comment by Misaka89535** [comment]
> You may be using an older version of fsspec. Try to upgrade it by implenting "pip install --upgrade fsspec"

It works!Thank you!

**Comment by QGrain** [comment]
It is recommended to use a fresh virtual env (or conda env) and then install the requirements, which could avoid problems with older-version packages that existed before.
