### ISSUE TITLE
部署在云服务器上，可以正常访问页面，但提交会显示ERROR

### ISSUE THREAD

**Issue by WanCixiong** [binary-husky/chatgpt_academic#115]
我在服务器上部署，服务器可以正常使用，
使用我的PC进行访问，可以正常访问到页面，但是点击提交或者实验功能会显示ERROR，

使用Fiddler查看是queue/join   HTTP/1.1 403 Forbidden
附图：
![QQ截图20230329231312](https://user-images.githubusercontent.com/58263178/228587840-da309fb4-ba8d-4713-b4d7-df77a80c5d28.png)

**Comment by binary-husky** [comment]
代理配置正常，一提交就error #88
