### ISSUE TITLE
Huggingface在线部署版本

### ISSUE THREAD

**Issue by WangRongsheng** [binary-husky/chatgpt_academic#12]
1. 访问：https://huggingface.co/spaces/wangrongsheng/ChatImprovement

2. 添加自己的openai-key即可使用！

**Comment by binary-husky** [comment]
Good idea!

**Comment by xianbaoqian** [comment]
This is awesome. Great work on the project and HF demo! It would be great to add this link to the README.md file so that more people can see it :-)

**Comment by binary-husky** [comment]
@xianbaoqian 得优先解决一下文件上传的问题：#16

**Comment by binary-husky** [comment]
Huggingface在线部署的话，所有问答都对space的所有者透明，隐私问题难以解决，我也试了一下，并非一个容易的解决方法https://huggingface.co/spaces/qingxu98/gpt-academic

**Comment by WangRongsheng** [comment]
good jobs

**Comment by AeroXi** [comment]
> Huggingface在线部署的话，所有问答都对space的所有者透明，隐私问题难以解决，我也试了一下，并非一个容易的解决方法https://huggingface.co/spaces/qingxu98/gpt-academic

可以提供一个然后让大家自己fork后使用

**Comment by binary-husky** [comment]
@AeroXi @Austin-Jack    https://huggingface.co/spaces/qingxu98/gpt-academic/tree/main   可以参考这个

**Comment by xianbaoqian** [comment]
可以参考这里，让用户自己 duplicate 到自己的 private Space 来处理。

https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/38108242/228451249-1b2ea04a-a355-499a-ba81-7d6c0202abdd.png">

@binary-husky

**Comment by binary-husky** [comment]
@xianbaoqian 是个好办法

**Comment by StevenH7-S** [comment]
> 1. 访问：https://huggingface.co/spaces/wangrongsheng/ChatImprovement
> 2. 添加自己的openai-key即可使用！

感谢大佬，duplicate了你的库，可以使用了！

**Comment by binary-husky** [comment]
@xianbaoqian 谢谢 merge 啦

**Comment by binary-husky** [comment]
https://huggingface.co/spaces/qingxu98/gpt-academic

**Comment by StevenH7-S** [comment]
> https://huggingface.co/spaces/qingxu98/gpt-academic

为什么我duplicate这个库就不行呢，duplicate第一个就可以

**Comment by StevenH7-S** [comment]
![image](https://user-images.githubusercontent.com/84580643/229284357-6c8c7348-d18a-4ef5-91c7-845d80b960a6.png)

**Comment by HansBug** [comment]
这里有一个适合个人自由部署的fork：https://github.com/HansBug/chatgpt_academic_for_hfspace
部署在：https://huggingface.co/spaces/HansBug/ChatGPTForAcadamic
这个fork通过github workflow进行自动部署，也可以支持部署在私有space，各用各的，互不打扰。而且无需每次输入api_key，对项目的整体改动也很低，随时可以从主库同步。
@binary-husky

**Comment by binary-husky** [comment]
> 这里有一个适合个人自由部署的fork：https://github.com/HansBug/chatgpt_academic_for_hfspace 部署在：https://huggingface.co/spaces/HansBug/ChatGPTForAcadamic 这个fork通过github workflow进行自动部署，也可以支持部署在私有space，各用各的，互不打扰。而且无需每次输入api_key，对项目的整体改动也很低，随时可以从主库同步。 @binary-husky

关注中

**Comment by wuya-python** [comment]
Json解析不合常规，很可能是文本过长 “error”: { “message”: “You exceeded your current quota, please check your plan and billing details.”, “type”: “insufficient_quota”, “param”: null, “code”: null }} 这个是什么问题呀

**Comment by wuya-python** [comment]
[Local Message] Json Error

Traceback (most recent call last):

File "E:\chatgpt\chatgpt_academic\predict.py", line 169, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "D:\software\Conda\conda\lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)
File "D:\software\Conda\conda\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "D:\software\Conda\conda\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}  这个报错。有人遇到过吗

**Comment by liangxyz** [comment]
> 这里有一个适合个人自由部署的fork：https://github.com/HansBug/chatgpt_academic_for_hfspace 部署在：https://huggingface.co/spaces/HansBug/ChatGPTForAcadamic 这个fork通过github workflow进行自动部署，也可以支持部署在私有space，各用各的，互不打扰。而且无需每次输入api_key，对项目的整体改动也很低，随时可以从主库同步。 @binary-husky

请问这个如何同步上游最新代码？

**Comment by HansBug** [comment]
> 请问这个如何同步上游最新代码？

等我明天来手动merge一下，应该问题不大，我改的部分都比较外围。

**Comment by zonszer** [comment]
> > 请问这个如何同步上游最新代码？
> 
> 等我明天来手动merge一下，应该问题不大，我改的部分都比较外围。
> 
> @liangxyz 已经重新同步了，你仓库那边点更新（忽略掉conflict强制更新）即可

大佬您能再同步一下吗，好像fork后只能从您这里同步，十分感谢！

**Comment by binary-husky** [comment]
> > > 请问这个如何同步上游最新代码？
> > 
> > 
> > 等我明天来手动merge一下，应该问题不大，我改的部分都比较外围。
> > @liangxyz 已经重新同步了，你仓库那边点更新（忽略掉conflict强制更新）即可
> 
> 大佬您能再同步一下吗，好像fork后只能从您这里同步，十分感谢！

最近代码变更很频繁，没空同步huggingface，抱歉
