### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by zhouxiaobao123123** [binary-husky/chatgpt_academic#120]
import gradio as gr
ModuleNotFoundError: No module named 'gradio',这种情况该咋整啊，小白求助。。。

**Comment by fanfoxle** [comment]
你先pip install一下gradio看看是不是安装了它
如果安装了pip install --upgrade一下

**Comment by pzhren** [comment]
> import gradio as gr 导入gradio为gr ModuleNotFoundError: No module named 'gradio',这种情况该咋整啊，小白求助。。。

我也是，你解决了吗

**Comment by pzhren** [comment]
> import gradio as gr 导入gradio为gr ModuleNotFoundError: No module named 'gradio',这种情况该咋整啊，小白求助。。。

貌似不能在系统环境中安装，用conda建一个虚拟环境再装就好了

**Comment by zhouxiaobao123123** [comment]
没有解决，最后下载了另外的版本，B站上有up搞了个懒人版，你可以去搜索到，直接下载调整下参数就可以用了。







Mr_小周
***@***.***







                       
原始邮件
                       
                     

发件人："RenPengzhen"< ***@***.*** &gt;;

发件时间：2023/4/2 9:41

收件人："binary-husky/chatgpt_academic"< ***@***.*** &gt;;

抄送人："zhouxiaobao123123"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [binary-husky/chatgpt_academic] ModuleNotFoundError: No modulenamed &#39;gradio&#39; (Issue #120)




  
import gradio as gr 导入gradio为gr ModuleNotFoundError: No module named 'gradio',这种情况该咋整啊，小白求助。。。
  
我也是，你解决了吗
 
&mdash;

**Comment by binary-husky** [comment]
用anaconda吧

**Comment by yuanzaiyuanfang** [comment]
创建虚拟环境
python -m  venv venv

进入文件夹
cd venv/scripts

激活
activate

返回
两次 cd ..

再安装依赖
python -m pip install -r requirements.txt   

建一个批处理 .bat
call .\venv\Scripts\activate
python main.py

每次启动执行批处理

**Comment by zhouxiaobao123123** [comment]
非常感谢！




Mr_小周
***@***.***







                       
原始邮件
                       
                     

发件人："yuanzaiyuanfang"< ***@***.*** &gt;;

发件时间：2023/4/19 9:50

收件人："binary-husky/chatgpt_academic"< ***@***.*** &gt;;

抄送人："zhouxiaobao123123"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [binary-husky/chatgpt_academic] ModuleNotFoundError: No modulenamed &#39;gradio&#39; (Issue #120)




 
创建虚拟环境
 python -m  venv venv
 
进入文件夹
 cd venv/scripts
 
激活
 activate
 
返回
 两次 cd ..
 
再安装依赖
 python -m pip install -r requirements.txt
 
建一个批处理 .bat
 call .\venv\Scripts\activate
 python main.py
 
每次启动执行批处理
 
&mdash;

**Comment by Aaronyjx** [comment]
Mac M3 Docker:
使用项目内置Gradio获取最优体验! 请运行 `pip install -r requirements.txt` 指令安装内置Gradio及其他依赖, 详情信息见requirements.txt.
