### ISSUE TITLE
Enhancement : 支持rar格式

### ISSUE THREAD

**Issue by JasonGuo1** [binary-husky/chatgpt_academic#121]
zip格式用着很方便，刚发现rar格式目前不太行，未来或许可以支持

**Comment by binary-husky** [comment]
解压功能是chatgpt帮我写的，zip，tar，gz 都是python内置组件支持的。如果再支持rar、7z等格式，需要新加项目依赖，可能是因为这个原因chatgpt没给我支持rar。


```
def extract_archive(file_path, dest_dir):
    import zipfile
    import tarfile
    import os
    # Get the file extension of the input file
    file_extension = os.path.splitext(file_path)[1]

    # Extract the archive based on its extension
    if file_extension == '.zip':
        with zipfile.ZipFile(file_path, 'r') as zipobj:
            zipobj.extractall(path=dest_dir)
            print("Successfully extracted zip archive to {}".format(dest_dir))

    elif file_extension in ['.tar', '.gz', '.bz2']:
        with tarfile.open(file_path, 'r:*') as tarobj:
            tarobj.extractall(path=dest_dir)
            print("Successfully extracted tar archive to {}".format(dest_dir))
    else:
        return
```

**Comment by JasonGuo1** [comment]
确实

**Comment by JasonGuo1** [comment]
> 解压功能是chatgpt帮我写的，zip，tar，gz 都是python内置组件支持的。如果再支持rar、7z等格式，需要新加项目依赖，可能是因为这个原因chatgpt没给我支持rar。
> 
> ```
> def extract_archive(file_path, dest_dir):
>     import zipfile
>     import tarfile
>     import os
>     # Get the file extension of the input file
>     file_extension = os.path.splitext(file_path)[1]
> 
>     # Extract the archive based on its extension
>     if file_extension == '.zip':
>         with zipfile.ZipFile(file_path, 'r') as zipobj:
>             zipobj.extractall(path=dest_dir)
>             print("Successfully extracted zip archive to {}".format(dest_dir))
> 
>     elif file_extension in ['.tar', '.gz', '.bz2']:
>         with tarfile.open(file_path, 'r:*') as tarobj:
>             tarobj.extractall(path=dest_dir)
>             print("Successfully extracted tar archive to {}".format(dest_dir))
>     else:
>         return
> ```

试了下rarfile库，还有点报错

**Comment by JasonGuo1** [comment]
> > zip格式用着很方便，刚发现rar格式目前不太行，未来或许可以支持
> 
> 大神用的什么环境呀，能给个部署教程不

你好我用的Win上的PyCharm，然后Python3.7环境，我有空写个简介吧

**Comment by JasonGuo1** [comment]
收到，明天我会抽空填写下有关内容。
