### ISSUE TITLE
Json解析不合常规 “error”: { “message”: “Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.”, “type”: “access_terminated”, “param”: null, “code”: null }}

### ISSUE THREAD

**Issue by zhichonglyu** [binary-husky/chatgpt_academic#126]
Json解析不合常规 “error”: { “message”: “Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact [support@openai.com](mailto:support@openai.com).”, “type”: “access_terminated”, “param”: null, “code”: null }}

[Local Message] Json Error

Traceback (most recent call last):

File "D:\ruanjian\academic\predict.py", line 160, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ruanjian\Anaconda3\envs\chatgpt\Lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ruanjian\Anaconda3\envs\chatgpt\Lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ruanjian\Anaconda3\envs\chatgpt\Lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.", "type": "access_terminated", "param": null, "code": null }}

**Comment by zhichonglyu** [comment]
> Same question here

I guess my key may not work properly.

**Comment by Githubnewdeveloper** [comment]
Same question

**Comment by Guts-s** [comment]
same question +1

**Comment by zhichonglyu** [comment]
> 这是OpenAI提醒你的API key被封了

You are right. Thanks.

**Comment by MiaoCheng0517** [comment]
> You are right. Thanks.
Did you solve this question? How to do?

**Comment by ljiatu** [comment]
> > > 这是OpenAI提醒你的API key被封了
> > 
> > 
> > You are right. Thanks.
> 
> Did you solve this question? How to do?

联系OpenAI support去申诉或者申请个新的。
