### ISSUE TITLE
TypeError: 'set' object is not subscriptable

### ISSUE THREAD

**Issue by DrMoMing** [binary-husky/chatgpt_academic#127]
报错说这些地方有问题
![image](https://user-images.githubusercontent.com/112334993/228644170-6fd0e6dd-28a2-467c-9cea-630781f4c4e3.png)

但是我检查了半天也没看出哪有问题。config的第6行，false的时候能正常打开localhost，但是问不了，估计是没能连上网，但是我clash打开着的，进ChatGPT官网聊也没问题。改成true之后就报错了，表示一头雾水。
![1680117133207](https://user-images.githubusercontent.com/112334993/228643705-630049a2-ac8a-433a-ab1b-d2b6a4c8a183.jpg)
![image](https://user-images.githubusercontent.com/112334993/228643870-390fe637-fb5b-4b25-95cd-47a0ead97c87.png)
![image](https://user-images.githubusercontent.com/112334993/228644041-898c1be4-caef-4331-ab95-6a793af9fe8b.png)

**Comment by DrMoMing** [comment]
#122 说是自己不小心改动了什么，我和这里的文件比对了，在除了可以自己改的那几个地方以外没发现有什么不一样的地方。我也记得我没有碰别的地方。如果有需要，我可以全部截屏。哦对了，我只动过config和config_private文件的那几个需要改的地方。

**Comment by zhichonglyu** [comment]
我也没能运行成功，但是我觉得你的proxies有问题。

**Comment by DrMoMing** [comment]
> 

那你觉得哪里有问题，应该怎么填。我的clash开的是系统代理，全局模式。端口我填写的也没问题。确实不知道应该怎么填才好了。XD

**Comment by JasonGuo1** [comment]
![F_7NXW@ `OE6D{@DRF6MK4P](https://user-images.githubusercontent.com/33084364/228712922-22f701ae-16d5-41ea-98b7-1869e992ffdb.png)
Clash的一般是这样

**Comment by DrMoMing** [comment]
> ![F_7NXW@ `OE6D{@DRF6MK4P](https://user-images.githubusercontent.com/33084364/228712922-22f701ae-16d5-41ea-98b7-1869e992ffdb.png) Clash的一般是这样

非常感谢！我去试试，是我没搞懂格式X﹏X

**Comment by JasonGuo1** [comment]
> > ![F_7NXW@ `OE6D{@DRF6MK4P](https://user-images.githubusercontent.com/33084364/228712922-22f701ae-16d5-41ea-98b7-1869e992ffdb.png) Clash的一般是这样
> 
> 非常感谢！我去试试，是我没搞懂格式X﹏X

不客气哈，还有问题的话可以试试换个代理节点。

**Comment by DrMoMing** [comment]
现在已经解决了，至少现在没什么问题了，非常感谢。
