### ISSUE TITLE
新增的 批量总结PDF文档 功能，在Windows环境下的问题

### ISSUE THREAD

**Issue by Skysliao** [binary-husky/chatgpt_academic#136]
![image](https://user-images.githubusercontent.com/48003940/228719505-859b553e-2d98-4f9b-a536-74e589599ed9.png)
斜杠视乎是linux环境中的

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/pull/102

**Comment by binary-husky** [comment]
这个报错的文件是其他python包的，不在项目内部

**Comment by Skysliao** [comment]
> 

是的 但是好像是那个批量总结PDF.py 用到的这个包，但是传过去的路径里的斜杠不对 这个斜杠是linux支持的

**Comment by Skysliao** [comment]
好的 已解决 谢谢
