### ISSUE TITLE
怎么输入自己的prompt，在System prompt输入没反应

### ISSUE THREAD

**Issue by GaoZhuoXiu** [binary-husky/chatgpt_academic#137]
![1680148049079](https://user-images.githubusercontent.com/39984980/228723723-c61219e5-99c6-407a-9dae-e6e4a9a00a0f.png)
我上传了这篇论文，在System prompt写入我的prompt，回车键没反应，点最上面的提交也不对

**Comment by GaoZhuoXiu** [comment]
为什么没有使用手册呢，没有地方有介绍这个system prompt

**Comment by binary-husky** [comment]
system prompt就是给gpt预先调教一下，相当于在问问题之前提前交代一些事情。
和提问的区别是gpt会默默记住system prompt，但不会显式地反驳或回复。

不需要确认，填完就生效。

**Comment by binary-husky** [comment]
是的[GaoZhuoXiu](https://github.com/GaoZhuoXiu)，加一项即可
