### ISSUE TITLE
中文变量名与函数名乱码问题

### ISSUE THREAD

**Issue by mashiro-wxy** [binary-husky/chatgpt_academic#139]
Traceback (most recent call last):
  File "/home/wxy/mywxy/chatgpt_academic/main.py", line 31, in <module>
    crazy_functional = get_crazy_functionals()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/mywxy/chatgpt_academic/functional_crazy.py", line 8, in get_crazy_functionals
    from crazy_functions.读文章写摘要 import 读文章写摘要
ModuleNotFoundError: No module named 'crazy_functions.读文章写摘要'
有读文章写摘要.py文件但却import失败
大概率是中文乱码问题。。。。

**Comment by Seanie7171** [comment]
![Uploading 5681018.png…]()

**Comment by mashiro-wxy** [comment]
![image](https://user-images.githubusercontent.com/57902773/228740291-9539995b-0fd4-4d66-9e40-a194c131e23b.png)

**Comment by binary-husky** [comment]
操作系统和python版本是？

**Comment by binary-husky** [comment]
正常情况下不应该出现编码问题，建议使用docker

**Comment by mashiro-wxy** [comment]
> 操作系统和python版本是？

Ubuntu 18.04.5 LTS 
Python 3.11.2

**Comment by binary-husky** [comment]
尝试一下docker?

``` sh
# 下载项目
git clone https://github.com/binary-husky/chatgpt_academic.git
cd chatgpt_academic
# 配置 海外Proxy 和 OpenAI API KEY
config.py
# 安装
docker build -t gpt-academic .
# 运行
docker run --rm -it --net=host gpt-academic


```
