### ISSUE TITLE
代理配置问题

### ISSUE THREAD

**Issue by thierry14k** [binary-husky/chatgpt_academic#142]
你好，很感谢分享。我使用的是zoogVPN，协议是OpenVPN UDP，但是我上官网和软件都看不见端口信息，请问如何解决，谢谢！

**Comment by xiaoliwe** [comment]
zoogVPN 的端口信息获取如下：

- 进入 zoogVPN 应用程序，并登录您的账户。
- 在主页面上选择“设置”。
- 在下拉菜单中选择“高级设置”。
- 找到“协议和端口”部分，您将看到选择的 VPN 服务器的端口信息列出

**Comment by binary-husky** [comment]
Link to #1

**Comment by thierry14k** [comment]
> zoogVPN 的端口信息获取如下：
> 
> * 进入 zoogVPN 应用程序，并登录您的账户。
> * 在主页面上选择“设置”。
> * 在下拉菜单中选择“高级设置”。
> * 找到“协议和端口”部分，您将看到选择的 VPN 服务器的端口信息列出

你好，我的应用程序里没有高级设置呀，官网上也看不到端口信息

**Comment by thierry14k** [comment]
> zoogVPN 的端口信息获取如下：
> 
> * 进入 zoogVPN 应用程序，并登录您的账户。
> * 在主页面上选择“设置”。
> * 在下拉菜单中选择“高级设置”。
> * 找到“协议和端口”部分，您将看到选择的 VPN 服务器的端口信息列出

proxies = { "http": "http://uk2.zoogvpn.com:1194", "https": "http://uk2.zoogvpn.com:1194", }
![image](https://user-images.githubusercontent.com/129361556/228749847-5c6e13eb-9178-45e5-a2ec-7026933297e4.png)
这种情况怎么办呢

**Comment by binary-husky** [comment]
@thierry14k https://github.com/binary-husky/chatgpt_academic/issues/170

**Comment by binary-husky** [comment]
#1
