### ISSUE TITLE
后台为什么会有这个进程？后门？

### ISSUE THREAD

**Issue by ComputerApp** [binary-husky/chatgpt_academic#158]
![image](https://user-images.githubusercontent.com/21033069/228810100-51d9661b-a635-4fef-9078-98ce05a11b95.png)

**Comment by kivid** [comment]
你可以去gradio项目提issue

**Comment by binary-husky** [comment]
这个东西不属于此项目，你可以去gradio项目提issue

**Comment by moyiliyi** [comment]
把main.py里面最后一行launch的share设成False就没了，给开一个公网界面用的
