### ISSUE TITLE
建议添加上传文件和通过url自动拉取文件再分析的功能

### ISSUE THREAD

**Issue by ifyz** [binary-husky/chatgpt_academic#16]
输入文件绝对路径才能使用实验功能，对于部署在服务器从远程访问的人使用有些不便。

**Comment by binary-husky** [comment]
我试试看吧

**Comment by binary-husky** [comment]
测试可行，测试分支localFileToRemote：https://github.com/binary-husky/chatgpt_academic/tree/localFileToRemote

![image](https://user-images.githubusercontent.com/96192199/227845160-26be483b-2c32-4b77-aba6-fba677c7aa95.png)
![image](https://user-images.githubusercontent.com/96192199/227845539-8b453b2c-dd04-4d05-b562-aa4683a95bf5.png)

**Comment by binary-husky** [comment]
merged to master  [ac9b590](https://github.com/binary-husky/chatgpt_academic/commit/ac9b5906606d4f9e8e035a7090ae44d2e9a9f847)
