### ISSUE TITLE
配置出现问题

### ISSUE THREAD

**Issue by fileban** [binary-husky/chatgpt_academic#160]
![无标题](https://user-images.githubusercontent.com/129386797/228812095-0ec2b311-5bc1-477b-997e-915e0e53839a.png)

**Comment by fileban** [comment]
代理用的v2ray，可以使用网页版ChatGPT但是无法打开这个是怎么回事？

**Comment by fileban** [comment]
弹出以下界面
![无标题](https://user-images.githubusercontent.com/129386797/228814506-4555193c-d041-4ab7-a058-f784fb2445c9.png)

**Comment by water-root** [comment]
加端口号了吗？

**Comment by fileban** [comment]
> 加端口号了吗？

加了

**Comment by fileban** [comment]
> V2ray要是自动配置系统代理的状态，然后就是去软件的参数设置里看本地监听端口，我发现v2ray给系统代理的端口会+1，建议在代理那里两个localhost后面都写端口，我也不清楚为什么系统代理端口会+1，但是看软件调用还是原来的。你可以尝试一下10808端口

![无标题](https://user-images.githubusercontent.com/129386797/229070347-91fcfba5-0623-42fc-b4ca-c0a285bf2527.png)
配置是这样的，有问题吗？

**Comment by Yngjx** [comment]
怎么解决的

**Comment by Yngjx** [comment]
更换浏览器是指什么

**Comment by fileban** [comment]
> 更换浏览器是指什么

之前用的edge浏览器，换成了Chrome后成功了，可能是edge的ssl证书的问题

**Comment by binary-husky** [comment]
Maybe related 在最后运行main.py后出现空白页，网络代理没有报错，但有警告是怎么回事？换了浏览器解决了  #169

**Comment by chenliansgithub** [comment]
请问怎么换浏览器呢
