### ISSUE TITLE
腾讯云公网部署学术chatgpt方案

### ISSUE THREAD

**Issue by sunchongwei** [binary-husky/chatgpt_academic#163]
看这么多人来看，我再好好整理下。
这个文档总体上就讲两件事情：配置VPN，运行chatgpt_academic项目。
# 1.配置VPN
参考博客：[https://www.hduzn.cn/2022/06/14/Linux%E4%BD%BF%E7%94%A8v2ray//](https://www.hduzn.cn/2022/06/14/Linux%E4%BD%BF%E7%94%A8v2ray//)
因为在CentOS的服务器上装东西的，用到了github，直接访问不了。本地windows系统用的v2rayN的客户端，想到v2ray在Linux上也可以用，就装上试一下。
v2ray本身是不区分服务端和客户端的，只要配置好相关文件，反正都可正常使用。（就是配置文件的区别）
## 1.1下载 v2ray-linux-64.zip
v2ray的Github地址：
https://github.com/v2ray/v2ray-core/releases/
目前最新的版本是v4.31.0，下面有Download页面：
https://github.com/v2fly/v2ray-core/releases/tag/v4.31.0
在页面中找到 v2ray-linux-64.zip 文件下载（我的是64位的CentOS系统）。
下载后解压出来是一个 v2ray-linux-64 目录，用ftp工具上传到linux的服务器上。
当然，也可以直接把解压包上传后，再用unzip命令解压。
## 1.2 把文件复制到对应的目录中
用复制(cp命令)或移动(mv命令)都可以。这里用cp举例。
首先，进入 v2ray-linux-64 目录，可以用 ls -l查看目录下的文件。
目录中的几个文件需要修改下权限，需要添加下可执行的权限。
```shell
cd v2ray-linux-64
chmod 755 v2ray
chmod 755 v2ctl
chmod 755 systemd/system/v2ray.service
chmod 755 systemd/system/v2ray@.service
```
然后复制目录中的文件到指定位置：
```shell
cp v2ray /usr/local/bin/
cp v2ctl /usr/local/bin/

cp systemd/system/v2ray.service /etc/systemd/system/
cp systemd/system/v2ray@.service /etc/systemd/system/

mkdir /usr/local/share/v2ray/
cp geoip.dat /usr/local/share/v2ray/
cp geosite.dat /usr/local/share/v2ray/

mkdir /var/log/v2ray/
cp access.log /var/log/v2ray/
cp error.log /var/log/v2ray/
```
两个日志文件没有的话，自己新建一个就行，要保证所有人都有读写权限。
反正配置文件中不用的话，其实也无所谓，就先建着扔着。
还有一个config.json配置文件，等配置完了再复制。
## 1.3 config.json配置文件
原生的V2ray并不支持订阅，反正我本来就在windows下用的，直接在v2rayN的客户端，服务器列表中中右键->【导出所选服务器为客户端配置】，保存成config.json文件。

然后把这个config.json文件也上传到 v2ray-linux-64 目录中，再来复制。
```
mkdir /usr/local/etc/v2ray/
cp config.json /usr/local/etc/v2ray/config.json
```
## 1.4启动v2ray
 ```
启动V2ray
sudo systemctl start v2ray
 检查V2ray状态
sudo systemctl status v2ray
设置V2ray开机自启动
sudo systemctl enable v2ray
```
![image](https://user-images.githubusercontent.com/36410461/229136405-6e2ee568-692b-4a51-a500-09f37abed03d.png)
## 1.5.检验代理是否生效
curl -x socks5://127.0.0.1:1080 https://www.google.com -v
如果能返回google.com的源代码，即表示配置成功。
**另外在配置的时候注意一个坑。就是使用的配置文件config.json是从客户端中导出的，所以端口号也是和客户端一样的，我的是10808**
# 2. 部署项目
## 2.1修改config.py
修改config.py时注意：
1. 修改key
2. 修改USE_PROXY = True
3. 修改代理协议：proxies = { "http": "socks5h://localhost:10808", "https": "socks5h://localhost:10808", }
4. 修改port端口号，默认-1表示随机找一个空闲端口， 这里设置为固定的端口如 9333。
5. AUTHENTICATION 设置用户名和密码
**注意，只有在本地运行的情况下可添加账户密码，如果是在云服务端则不能添加账户密码，主要是由于gradio存在的Bug问题导致访问失败！！！**
## 2.2运行
windows运行
 ```
python main.py&
```
linux运行
```
nohup python main.py&     # 一直运行，及时登录账号退出也会继续运行
```
## 2.3 开放端口
由于是云服务器需要打开端口供其他客户端访问.
具体是在腾讯云服务器控制台-》防火墙设置过滤规则。

# 3.可能会存在的问题及解决方案
（1）python版本尽量使python3.8及以上
（2）gradio存在着bug导致添加账号密码后云服务器上提供的功能没法使用出现connection error!

**Comment by binary-husky** [comment]
谢谢，给您加wiki里面了https://github.com/binary-husky/chatgpt_academic/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by adrianzzk** [comment]
@sunchongwei 您好，请问测试成功返回的信息是什么呀

**Comment by adrianzzk** [comment]
我返回的是这个
‘’‘<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com/sorry/index?continue=https://www.google.com/&amp;q=EgRrrxxUGJD3lqEGIjDcDGTmxG6p39WEao_QJ_cSqOb0mfY6d5RRv9Ri9ul66OckrhTap-fm9ekGE-Lj4q4yAXJKGVNPUlJZX0FCVVNJVkVfTkVUX01FU1NBR0U">here</A>.
</BODY></HTML>
’‘’

**Comment by sunchongwei** [comment]
> 我返回的是这个 ‘’‘
> 
> <TITLE>302 Moved</TITLE>
> # 302 Moved
> The document has moved [here](https://www.google.com/sorry/index?continue=https://www.google.com/&q=EgRrrxxUGJD3lqEGIjDcDGTmxG6p39WEao_QJ_cSqOb0mfY6d5RRv9Ri9ul66OckrhTap-fm9ekGE-Lj4q4yAXJKGVNPUlJZX0FCVVNJVkVfTkVUX01FU1NBR0U). ’‘’

正常情况是乱七八糟很多，是个html页面

**Comment by mqk98** [comment]
不建议这样 会被抓的 已经因为翻被封了

**Comment by leyiweb** [comment]
gradio存在着bug导致添加账号密码后云服务器上提供的功能没法使用出现connection error!，感觉公网环境下这个是刚需

**Comment by mqk98** [comment]
> gradio存在着bug导致添加账号密码后云服务器上提供的功能没法使用出现connection error!，感觉公网环境下这个是刚需



> 不建议这样 会被抓的 已经因为翻被封了

除非是非大陆服务器 只要是大陆服务器都不要这么搞 这是在翻墙 还是在暴露的环境下 想查你很容易

**Comment by sunchongwei** [comment]
> 

目前本人在国内和香港服务器上均进行了部署考虑到国内主机的各种问题（VPN节点有时不稳定，不合法...）目前本人已经将服务器迁到香港服务器上，所以也就不存在翻墙这个说法。哈哈哈哈，望周知，本人没有游走在法律边缘

**Comment by moxi000** [comment]
> 

请问解决添加账号密码后无法访问插件功能的帖子在哪里呢，可否指路

**Comment by Mahonehan** [comment]
v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 五 2023-05-12 13:21:30 CST; 4s ago
     Docs: https://www.v2fly.org/
  Process: 22049 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=23)
 Main PID: 22049 (code=exited, status=23)

5月 12 13:21:30 hecs-263008 systemd[1]: Started V2Ray Service.
5月 12 13:21:30 hecs-263008 v2ray[22049]: V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) ...d64)
5月 12 13:21:30 hecs-263008 v2ray[22049]: A unified platform for anti-censorship.
5月 12 13:21:30 hecs-263008 systemd[1]: v2ray.service: main process exited, code=exited, status=23/n/a
5月 12 13:21:30 hecs-263008 systemd[1]: Unit v2ray.service entered failed state.
5月 12 13:21:30 hecs-263008 systemd[1]: v2ray.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
这个怎么解决

**Comment by CodePothunter** [comment]
腾讯云是不允许部署VPN之类的服务的。

**Comment by Mahonehan** [comment]
解决了，刚开始用的华为云打开不了，用了腾讯云之后就好了

**Comment by Mahonehan** [comment]
> 腾讯云是不允许部署VPN之类的服务的。

解决了，刚开始用的华为云打开不了，用了腾讯云之后就好了

**Comment by allenwendy** [comment]
偏危险一点，建议香港的服务器用，其他地区还是算了，容易被查。我还是花钱搞个海外的服务器，省去这一步吧

**Comment by Gsatb** [comment]
请问这个如何设置https？
