### ISSUE TITLE
中文学术润色问题

### ISSUE THREAD

**Issue by 2213500360** [binary-husky/chatgpt_academic#165]
点击中文学术润色之后显示如下：这是什么原因呢？
![image](https://user-images.githubusercontent.com/67719519/228840619-0cec8270-1a6a-4929-ab4e-b0a40a6d9931.png)

**Comment by JJJzjz** [comment]
这个怎么安装啊

**Comment by binary-husky** [comment]
你没输入文本呢，先输入带润色的内容，再点击

**Comment by JJJzjz** [comment]
> 点击中文学术润色之后显示如下：这是什么原因呢？ ![image](https://user-images.githubusercontent.com/67719519/228840619-0cec8270-1a6a-4929-ab4e-b0a40a6d9931.png)

这个怎么装朋友，能给帮忙介绍一下，没有装过这个不是计算机专业

**Comment by 2213500360** [comment]
> > 点击中文学术润色之后显示如下：这是什么原因呢？ ![image](https://user-images.githubusercontent.com/67719519/228840619-0cec8270-1a6a-4929-ab4e-b0a40a6d9931.png)
> 
> 这个怎么装朋友，能给帮忙介绍一下，没有装过这个不是计算机专业

就是运行python代码啊，运行前配置好config.py文件。按README教程走
