### ISSUE TITLE
[Quesiton] 如何解析上传的pdf文件？

### ISSUE THREAD

**Issue by HighScorePlayer** [binary-husky/chatgpt_academic#168]
比如我上传了一篇论文，需要它对其进行翻译，总结，生成图片等等功能.

Web里没有看到解析pdf的button，但是似乎是有一个正在测试的模块，我需要补充安装依赖吗？

**Comment by binary-husky** [comment]
就是那个正在测试的模块，跟文件的大小无关，只和文本的长度有关

**Comment by binary-husky** [comment]
> 装好了好像效果不咋好，1.1mb的文件他还说大了，要是放生化环材的文章那还得了. 当然tex好像足够好了.

![image](https://user-images.githubusercontent.com/96192199/228873924-c315e557-a17b-4bb6-9636-05d9df3bd56a.png)

一个意思，需要想办法分割pdf的章节

**Comment by HighScorePlayer** [comment]
> > 装好了好像效果不咋好，1.1mb的文件他还说大了，要是放生化环材的文章那还得了. 当然tex好像足够好了.
> 
> ![image](https://user-images.githubusercontent.com/96192199/228873924-c315e557-a17b-4bb6-9636-05d9df3bd56a.png)
> 
> 一个意思，需要想办法分割pdf的章节

多谢了，我没咋写不会实现这个工程.

**Comment by ValeriaWong** [comment]
您好，现在的批量总结pdf的crazy function还只支持文本，并未加入图像等功能，另外由于现在是gpt3.5turbo其实是不支持看图的，

现在相关的主要代码如下
```with fitz.open(fp) as doc:
            file_content = ""
            for page in doc:
                file_content += page.get_text()
            print(file_content)
```
可以看到现在其实是只有get_text()功能的
