### ISSUE TITLE
在最后运行main.py后出现空白页，网络代理没有报错，但有警告是怎么回事？

### ISSUE THREAD

**Issue by fileban** [binary-husky/chatgpt_academic#169]
![无标题](https://user-images.githubusercontent.com/129386797/228871188-5dfaa572-a2e6-4616-8885-6843ef1c3590.png)
![无标题1](https://user-images.githubusercontent.com/129386797/228871214-ea3648b0-5881-4a51-b312-808a07fa16c5.png)
![无标题2](https://user-images.githubusercontent.com/129386797/228871842-468c633a-ef86-4085-b4cd-a640854c6c78.png)
如题，这个问题是什么问题？请问该如何解决？

**Comment by ifyz** [comment]
SSL证书出错，应该是浏览器拦截了当前页面含https的资源报错

**Comment by fileban** [comment]
> SSL证书出错，应该是浏览器拦截了当前页面含https的资源报错

请问一下该怎么解决这个问题呢？

**Comment by fileban** [comment]
换了浏览器解决了
