### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by jojoygstar** [binary-husky/chatgpt_academic#170]
![image](https://user-images.githubusercontent.com/91509470/228881444-ef3b8bfd-dd95-4ab9-a283-83a4c1c9f228.png)
我已经更改了config中的apikey和代理，但却运行后出现如上然后闪退

**Comment by binary-husky** [comment]
1、更新代码
2、删除config_private.py（如果有）
3、修改config.py

**Comment by binary-husky** [comment]
@jojoygstar 升级gradio。如果不影响使用，也可以选择可以无视。

**Comment by Jessy-Ding** [comment]
在国外，所以绕过了代理设置。

**Comment by Jessy-Ding** [comment]
solved

**Comment by dzzzheartsteel** [comment]
在config.py中修改了API后，询问问题时显示额度不足，但是API所属账号能够正常访问openai官方的gpt3.5，请问该如何解决
<img width="587" alt="6fdb93ffac76ae36e1ebbe455775422" src="https://github.com/binary-husky/gpt_academic/assets/149289619/7dbdd506-ab24-4e00-87f0-ba5843f6ec9c">
<img width="616" alt="7cfd25fd2461907f592b44195eb641a" src="https://github.com/binary-husky/gpt_academic/assets/149289619/e007d187-6a2f-4de7-b755-ba4524960481">

**Comment by ZzhAlan** [comment]
我目前遇到了相同的问题，请问您这边如何解决呢？感谢

> 在config.py中修改了API后，询问问题时显示额度不足，但是API所属账号能够正常访问openai官方的gpt3.5，请问该如何解决 <img alt="6fdb93ffac76ae36e1ebbe455775422" width="587" src="https://private-user-images.githubusercontent.com/149289619/283351279-7dbdd506-ab24-4e00-87f0-ba5843f6ec9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MjQwNzgsIm5iZiI6MTcwMzkyMzc3OCwicGF0aCI6Ii8xNDkyODk2MTkvMjgzMzUxMjc5LTdkYmRkNTA2LWFiMjQtNGUwMC04N2YwLWJhNTg0M2Y2ZWM5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQwODA5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjRmNDFiYzlmMDc1OTkxZWQ4MTFmNjY0MDgwZDY5MzRkNTYwYTRjNDE4ODY4NWVkZjUwYjhlOTgxZDZjYTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jNGY_GAzbglSHNMIw-zpa3xs7eh253Qkxh7_1VqfWEg"> <img alt="7cfd25fd2461907f592b44195eb641a" width="616" src="https://private-user-images.githubusercontent.com/149289619/283351285-e007d187-6a2f-4de7-b755-ba4524960481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MjQwNzgsIm5iZiI6MTcwMzkyMzc3OCwicGF0aCI6Ii8xNDkyODk2MTkvMjgzMzUxMjg1LWUwMDdkMTg3LTZhMmYtNGRlNy1iNzU1LWJhNDUyNDk2MDQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQwODA5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjcwNWU4YTNlNjI1YTFkMzY2YWY0YTYwMTI5ZGY5M2ZlZmNmMGI3NjA4Y2I1ZTc4MzkxMTNkMDVjZWIwOTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kb2Z50wvQCDnmH4Yq-KZYeuIpaBxtlKll_1JRmLp2u4">

**Comment by Frankcui123** [comment]
我的key是新的，字符数共132个，如何识别呢？
