### ISSUE TITLE
最新暗黑色主题界面如何配置？

### ISSUE THREAD

**Issue by substitute5** [binary-husky/chatgpt_academic#173]
我拉取了最新的代码运行，界面仍旧是之前的风格，想要知道如何实现暗黑主题风格的配置，谢谢。

**Comment by benlw** [comment]
或许是系统/浏览器的效果, 代码里没有暗黑相关的设定

**Comment by wangfeng35** [comment]
同是白的

**Comment by houjie8888** [comment]
@ifyz 你好，预设的主题没有暗黑风格，请问如何修改让他变成暗黑风格呢，set_theme.set()中哪个属性是控制背景颜色的呀

**Comment by binary-husky** [comment]
我是把浏览器调节到暗色模式

**Comment by binary-husky** [comment]
在浏览器url后面添加/?__dark-theme=true可以切换dark主题
