### ISSUE TITLE
能加一个海外版的使用方法吗？

### ISSUE THREAD

**Issue by Jessy-Ding** [binary-husky/chatgpt_academic#175]
您好，我在海外不需要代理，终端遇到如下报错：

网络代理状态：未配置。无代理状态下很可能无法访问。
Traceback (most recent call last):
  File "/Users/<...>/chatgpt_academic/main.py", line 3, in <module>
    from predict import predict
  File "/Users/<...>/chatgpt_academic/predict.py", line 25, in <module>
    get_conf('proxies', 'API_URL', 'API_KEY', 'TIMEOUT_SECONDS', 'MAX_RETRY', 'LLM_MODEL')
  File "/Users/<...>/chatgpt_academic/toolbox.py", line 230, in get_conf
    assert False, "正确的API_KEY密钥是51位，请在config文件中修改API密钥, 添加海外代理之后再运行。" + \
AssertionError: 正确的API_KEY密钥是51位，请在config文件中修改API密钥, 添加海外代理之后再运行。（如果您刚更新过代码，请确保旧版config_private文件中没有遗留任何新增键值）

**Comment by yilin-gong** [comment]
看起来是API Key 没输对？修改一下config里面的API key试试

**Comment by yilin-gong** [comment]
`if arg=='API_KEY' and len(r) != 51:`

这里只检测是否有API_KEY和长度是否为51， 可以检查api key是否正确

**Comment by Jessy-Ding** [comment]
确定对的~

**Comment by Okabe-Rintarou-0** [comment]
确认一下 config_private 有没有这些内容：'proxies', 'API_URL', 'API_KEY', 'TIMEOUT_SECONDS', 'MAX_RETRY', 'LLM_MODEL'

**Comment by binary-husky** [comment]
请见wiki常见问题，里面有

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/issues/170

**Comment by Jessy-Ding** [comment]
确认一下 config_private 有没有这些内容：'proxies', 'API_URL', 'API_KEY', 'TIMEOUT_SECONDS', 'MAX_RETRY', 'LLM_MODEL'
有的
