### ISSUE TITLE
添加”清空会话“功能

### ISSUE THREAD

**Issue by tay10rb** [binary-husky/chatgpt_academic#18]
添加一个清空会话框功能，这样一次分析结束后，清空会话方便下次分析。

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/227850285-3c4012ff-2384-4aab-a98a-e27532379da5.png)
刚加了一个快捷的报告下载功能，应该可以满足要求 

清空回话的话，我觉得还是F5刷新更靠谱一点：不太清楚gradio的页面能挂多久，似乎过几个小时，页面就和后端断开连接的

**Comment by benlw** [comment]
> ![image](https://user-images.githubusercontent.com/96192199/227850285-3c4012ff-2384-4aab-a98a-e27532379da5.png) 刚加了一个快捷的报告下载功能，应该可以满足要求
> 
> 清空回话的话，我觉得还是F5刷新更靠谱一点：不太清楚gradio的页面能挂多久，似乎过几个小时，页面就和后端断开连接的

作者您好，请问这个功能是如何触发的？通过“完成”的关键词吗？

**Comment by benlw** [comment]
噢噢，谢谢，我看到了，write_results_to_file()

**Comment by binary-husky** [comment]
@benlw 有个低版本的gradio无法触发的问题，可以通过升级gradio解决

**Comment by from-china-to** [comment]
> 噢噢，谢谢，我看到了，write_results_to_file()

你好，你明白了 我没明白，请教下 这个write_results_to_file()要添加在哪里？

**Comment by benlw** [comment]
> > 噢噢，谢谢，我看到了，write_results_to_file()
> 
> 你好，你明白了 我没明白，请教下 这个write_results_to_file()要添加在哪里？

可以参考生成函数注释.py 30多行那里类似调用下 生成报告文件就可以了。

**Comment by benlw** [comment]
> @benlw 有个低版本的gradio无法触发的问题，可以通过升级gradio解决

谢谢开发者，我知道啦。

这个项目很好，而且模块化设计很赞。很方便加入自己的prompt

**Comment by Yuanliang-Li** [comment]
那么清空会话有啥解决方案？

**Comment by KingMV** [comment]
> 

F5刷新
