### ISSUE TITLE
包的版本存在依赖冲突

### ISSUE THREAD

**Issue by Jiangxinkai** [binary-husky/chatgpt_academic#181]
您好，gradio 和 uvicorn 包存在冲突,
ERROR: Cannot install -r requirements.txt (line 1) because these package versions have conflicting dependencies
The conflict is caused by:
    gradio 3.24.0 depends on uvicorn
    gradio 3.23.0 depends on uvicorn
我是否可以删除 requirements.txt 中的冲突包的版本信息，让 pip 尝试解决依赖关系冲突。

**Comment by binary-husky** [comment]
虽然但是我们这依赖只有三条

gradio>=3.23
requests[socks]
mdtex2html

**Comment by binary-husky** [comment]
尝试
1、剔除非官方pip源
2、可以尝试conda或者docker
