### ISSUE TITLE
解析py项目代码每次到最后的总结阶段就出现这个错误

### ISSUE THREAD

**Issue by ItachiWithSasuke** [binary-husky/chatgpt_academic#182]
![QQ截图20230331115628](https://user-images.githubusercontent.com/48608215/229019423-936c3c81-85a3-4c31-8a24-dc67a06260a5.png)

**Comment by binary-husky** [comment]
可以阐述一下操作步骤吗？还有你解析的文件？

**Comment by binary-husky** [comment]
看上去是个小bug，我尽快解决

**Comment by AwxChen** [comment]
我也遇到了一样的问题

**Comment by EvelynCarter** [comment]
我也遇到了一样的问题

**Comment by EvelynCarter** [comment]
什么时候解决了  告知一下

**Comment by EvelynCarter** [comment]
> 看上去是个小bug，我尽快解决

什么时候解决  告知一下

**Comment by ItachiWithSasuke** [comment]
> 可以阐述一下操作步骤吗？还有你解析的文件？

我把[YangtaoWANG95](https://github.com/YangtaoWANG95)
/
[TokenCut](https://github.com/YangtaoWANG95/TokenCut)这个项目下载到本地了，然后在界面input里面输入了路径，点了解析PYTHON项目的按钮，之前每个单独文件都可以正常给出梗概，但在最后自动要求根据上述描述整个整个项目的时候出现了这个报错

**Comment by ItachiWithSasuke** [comment]
![QQ图片20230331154052](https://user-images.githubusercontent.com/48608215/229056017-0ebc4691-8218-4333-aac9-5c8b176c6922.png)
有时候会出现已经给出的解答，然后又跳变成了这样的报错

**Comment by EvelynCarter** [comment]
是不是项目过大引起的

**Comment by EvelynCarter** [comment]
> 看上去是个小bug，我尽快解决

[Local Message] 实验性函数调用出错:

Traceback (most recent call last):

File "D:\tianyiyun\Chatgpt\toolbox.py", line 81, in decorated

yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)

File "D:\tianyiyun\Chatgpt\crazy_functions\解析项目源代码.py", line 107, in 解析一个Python项目

yield from 解析源代码(file_manifest, project_folder, top_p, temperature, chatbot, history, systemPromptTxt)

File "D:\tianyiyun\Chatgpt\crazy_functions\解析项目源代码.py", line 42, in 解析源代码

res = write_results_to_file(history)

      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\tianyiyun\Chatgpt\toolbox.py", line 59, in write_results_to_file

f.write(content)

TypeError: write() argument must be str, not None

**Comment by binary-husky** [comment]
没找到触发条件，我先脚疼医脚了直接

```
def write_results_to_file(history, file_name=None):
    """
        将对话记录history以Markdown格式写入文件中。如果没有指定文件名，则使用当前时间生成文件名。
    """
    import os, time
    if file_name is None:
        # file_name = time.strftime("chatGPT分析报告%Y-%m-%d-%H-%M-%S", time.localtime()) + '.md'
        file_name = 'chatGPT分析报告' + time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime()) + '.md'
    os.makedirs('./gpt_log/', exist_ok=True)
    with open(f'./gpt_log/{file_name}', 'w', encoding = 'utf8') as f:
        f.write('# chatGPT 分析报告\n')
        for i, content in enumerate(history):
            if type(content) != str: content = str(content) # ------------------> 强行转化字符串
            if i%2==0: f.write('## ')
            f.write(content)
            f.write('\n\n')
    res = '以上材料已经被写入' + os.path.abspath(f'./gpt_log/{file_name}')
    print(res)
    return res
```

**Comment by AwxChen** [comment]
> [7c8b8b9](https://github.com/binary-husky/chatgpt_academic/commit/7c8b8b95b2ef96c84d9f03dc64050b9dd6f392c8) 已经提交了修改 @ItachiWithSasuke @EvelynCarter @AwxChen @SadPencil 我依然不确定问题根源在哪，但这样应该至少能把报告导出

感谢你的修改！
