### ISSUE TITLE
circular import 循环引用问题

### ISSUE THREAD

**Issue by lushuangning** [binary-husky/chatgpt_academic#183]
测试 `check_proxy.py` 时报错：
```
ImportError: cannot import name 'get_conf' from partially initialized module 'toolbox' (most likely due to a circular import)
```
经检查，`check_proxy.py` 导入包的时候使用了`from toolbox import get_conf`， 而 `toobox.py` 中又导入了 `from predict import predict_no_ui`，最后在 `predict.py` 中再次导入了 `from toolbox import get_conf`，导致了循环引用。

另外，运行 ` main.py` 时也有这个问题

**Comment by binary-husky** [comment]
测试了没问题，你自己改代码改的出bug来了

**Comment by binary-husky** [comment]
我大体明白你是怎么改出问题的了，toolbox是装工具函数的，不要把工具函数里面import移到外面

**Comment by lushuangning** [comment]
sorry，是我这边改的问题，麻烦移除相关issue

binary-husky ***@***.***> 于2023年3月31日周五 12:47写道：
