### ISSUE TITLE
为什么我运行了main.py以后没有跳出图形化界面啊。。。

### ISSUE THREAD

**Issue by tanbojie-mob** [binary-husky/chatgpt_academic#187]
![image](https://user-images.githubusercontent.com/82080927/229030216-994b138c-fa0b-4aa0-a3b9-ab01f0b5abc8.png)
运行了main.py以后只有这句话，然后图形化界面没有跳出来。。。

**Comment by starstarb** [comment]
+1我也是

**Comment by Euclid-Jie** [comment]
把网址复制到浏览器也行

**Comment by fileban** [comment]
![无标题](https://user-images.githubusercontent.com/129386797/229069610-bb3fa6ec-a286-4918-b102-3732dbc52a77.png)
我也没成功，弹出的界面是这样的

**Comment by Waston12** [comment]
可以试试把能关的杀毒软件都关掉，尤其是Mcafee的实时扫描

**Comment by fileban** [comment]
> ![无标题](https://user-images.githubusercontent.com/129386797/229069610-bb3fa6ec-a286-4918-b102-3732dbc52a77.png) 我也没成功，弹出的界面是这样的

换了Chrome浏览器之后解决了。。。。之前用的edge
