### ISSUE TITLE
docker无法正常使用代理

### ISSUE THREAD

**Issue by water-root** [binary-husky/chatgpt_academic#188]
不使用docker的本地部署可以正常使用代理。使用docker后无法正常使用代理，但curl google是可以的，python3 check_proxy.py 也能正常显示出代理
![image](https://user-images.githubusercontent.com/124557984/229030113-2ffaf7e0-fe46-4739-a480-d2c6b0c00db7.png)

![223](https://user-images.githubusercontent.com/124557984/229033258-64231f05-3244-4630-ab58-afdb1d5196bd.png)

**Comment by binary-husky** [comment]
您好，确定本地代理协议是https吗？我头一次见本地代理用https协议的……

**Comment by binary-husky** [comment]
另外不是wsl吧？

**Comment by binary-husky** [comment]
如果是windows，--net=host就失效了，wiki里面有人给了别的方案

**Comment by water-root** [comment]
用的是Ubuntu 20.04.1 服务器

**Comment by binary-husky** [comment]
“python3 check_proxy.py 也能正常显示出代理”

这不对吧，main.py和check_proxy.py检查代理调用的是一个函数，怎么会出不同的结果呢？

**Comment by water-root** [comment]
main.py和check_proxy.py都是可以使用代理，docker就无法使用

**Comment by water-root** [comment]
这是main.py运行后的结果，代理可以使用
![FireShot Cap](https://user-images.githubusercontent.com/124557984/229037982-382efbfc-7432-4326-b994-27d524e364f9.png)

![image](https://user-images.githubusercontent.com/124557984/229038222-e5529b93-d8ae-4373-84fa-36d54346913e.png)

**Comment by binary-husky** [comment]
> main.py和check_proxy.py都是可以使用代理，docker就无法使用

那我就有点蒙了，有没有可能docker设置了某种安全策略禁用了--net=host?
试试端口映射？把 --net=host 换成 -p 20231:20231

**Comment by binary-husky** [comment]
或者你已经在docker内部了，你实际上在docker in docker嵌套？

**Comment by water-root** [comment]
> > main.py和check_proxy.py都是可以使用代理，docker就无法使用
> 
> 那我就有点蒙了，有没有可能docker设置了某种安全策略禁用了--net=host? 试试端口映射？把 --net=host 换成 -p 20231:20231

v2rayA 的docker占用20231端口😂

**Comment by AllenXiao95** [comment]
> > main.py和check_proxy.py都是可以使用代理，docker就无法使用
> 
> 那我就有点蒙了，有没有可能docker设置了某种安全策略禁用了--net=host? 试试端口映射？把 --net=host 换成 -p 20231:20231

我也遇到了类似情况, 使用指定端口做expose就可以, --net=host就不行

**Comment by FR13ndSDP** [comment]
我在宿主机运行`python3 check_proxy.py` 输出：
```
网络代理状态：运行。
查询代理的地理位置，返回的结果是 ...
代理配置 http://127.0.0.1:7890, 代理所在地：Malaysia
```
然而使用docker运行 `docker run --rm -it --net=host gpt-academic python3 check_proxy.py`,却有：
```
网络代理状态：未配置。无代理状态下很可能无法访问。
```
尝试在`.docker/config.json`中指定代理仍然失败，究竟是为什么呢？

**Comment by FR13ndSDP** [comment]
> 我在宿主机运行`python3 check_proxy.py` 输出：
> 
> ```
> 网络代理状态：运行。
> 查询代理的地理位置，返回的结果是 ...
> 代理配置 http://127.0.0.1:7890, 代理所在地：Malaysia
> ```
> 
> 然而使用docker运行 `docker run --rm -it --net=host gpt-academic python3 check_proxy.py`,却有：
> 
> ```
> 网络代理状态：未配置。无代理状态下很可能无法访问。
> ```
> 
> 尝试在`.docker/config.json`中指定代理仍然失败，究竟是为什么呢？

此问题已解决，需要在build镜像之前修改`config.py`，在这之后`docker run --rm -it --net=host gpt-academic`正确运行

**Comment by SadPencil** [comment]
密钥，不是秘……调一下输入法把错误的词删了吧

**Comment by SadPencil** [comment]
如果有需要我可以做个PR，把你这个dockerfile改成最通常的环境变量做法

**Comment by AllenXiao95** [comment]
通过args方式传递参数可能更好一点

**Comment by SadPencil** [comment]
@AllenXiao95 主流的设计原则是，敏感参数要么从 tty 直接读要么环境变量要么文件，不能从命令行参数读入

**Comment by binary-husky** [comment]
> @AllenXiao95 主流的设计原则是，敏感参数要么从 tty 直接读要么环境变量要么文件，不能从命令行参数读入

这样呀~

不过在windows上配置环境变量真的是很难受，而且在git bash和在cmd配置环境变量的命令还不一样……

**Comment by binary-husky** [comment]
> > @AllenXiao95 主流的设计原则是，敏感参数要么从 tty 直接读要么环境变量要么文件，不能从命令行参数读入
> 
> 这样呀~
> 
> 不过在windows上配置环境变量真的是很难受，而且在git bash和在cmd配置环境变量的命令还不一样……

另外之后应该可以设计成按照一定的优先级，依次读取 argparse，环境变量，config_private 和 config

```
@lru_cache(maxsize=128)
def read_single_conf_with_lru_cache(arg):
    try: r = getattr(importlib.import_module('config_private'), arg)
    except: r = getattr(importlib.import_module('config'), arg)
    # 在读取API_KEY时，检查一下是不是忘了改config
    if arg=='API_KEY':
        # 正确的 API_KEY 是 "sk-" + 48 位大小写字母数字的组合
        API_MATCH = re.match(r"sk-[a-zA-Z0-9]{48}$", r)
        if API_MATCH:
            print(f"[API_KEY] 您的 API_KEY 是: {r[:15]}*** API_KEY 导入成功")
        else:
            assert False, "正确的 API_KEY 是 'sk-' + '48 位大小写字母数字' 的组合，请在config文件中修改API密钥, 添加海外代理之后再运行。" + \
                        "（如果您刚更新过代码，请确保旧版config_private文件中没有遗留任何新增键值）"
    if arg=='proxies':
        if r is None: 
            print('[PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问。建议：检查USE_PROXY选项是否修改。')
        else: 
            print('[PROXY] 网络代理状态：已配置。配置信息如下：', r)
            assert isinstance(r, dict), 'proxies格式错误，请注意proxies选项的格式，不要遗漏括号。'
    return r

def get_conf(*args):
    # 建议您复制一个config_private.py放自己的秘密, 如API和代理网址, 避免不小心传github被别人看到
    res = []
    for arg in args:
        r = read_single_conf_with_lru_cache(arg)
        res.append(r)
    return res
```

**Comment by SadPencil** [comment]
@binary-husky 不应使用 argparse 读取敏感信息。就好比 mysql 的 client 可以通过 tty 或环境变量读取密码，但绝不会提供命令行参数读取密码的功能一样。

**Comment by sfs999** [comment]
docker初学者，我在使用docker构建时也发生了该问题，原因是在配置代理地址时使用的是localhost，此时无法跳出docker的网络连接到宿主机，应该将之改为host.docker.internal，此时docker内部程序可以访问宿主机的代理端口

**Comment by jasonliu222** [comment]
> docker初学者，我在使用docker构建时也发生了该问题，原因是在配置代理地址时使用的是localhost，此时无法跳出docker的网络连接到宿主机，应该将之改为host.docker.internal，此时docker内部程序可以访问宿主机的代理端口

这个特殊的 DNS 名称目前仅适用于 Docker for Mac 和 Docker for Windows，并不适用于所有环境。
