### ISSUE TITLE
在页面上增加设置api-key的功能

### ISSUE THREAD

**Issue by echoyang52hz** [binary-husky/chatgpt_academic#19]
在页面上直接给一个填入api-key的位置，方便换用不同的api-key，这样会不会更方便一些；
目前来看，某些openai账号在使用api方式不当时会有被封的情况出现（不太清楚被封的理由，可能与机场有关）；
而且有不少使用了账号注册时赠送的额度，频繁更换api-key的情景估计不少……

**Comment by binary-husky** [comment]
有啥办法能批量注册api key呢？
