### ISSUE TITLE
对话框输入后永远跳出来这句话怎么办呀

### ISSUE THREAD

**Issue by tanbojie-mob** [binary-husky/chatgpt_academic#190]
![image](https://user-images.githubusercontent.com/82080927/229039448-70a47408-2d51-42b5-a0ce-65ca5a4d6096.png)
check_proxy.py是可以检测到代理的呀。。。

**Comment by ziwooniya** [comment]
config.py  USE_PROXY改成true了吗

**Comment by binary-husky** [comment]
#1
