### ISSUE TITLE
代理配置后返回错误结果

### ISSUE THREAD

**Issue by sierxue** [binary-husky/chatgpt_academic#191]
我的代理配置在 config_private.py 中，配置如下：
```
USE_PROXY = true
if USE_PROXY:
    proxies = { "http": "socks5h://127.0.0.1:37192", "https": "socks5h://127.0.0.1:37192", }
    print('网络代理状态：运行。')
else:
    proxies = None
    print('网络代理状态：未配置。无代理状态下很可能无法访问。')
```

用 check_proxy.py 返回的结果是

网络代理状态：未配置。无代理状态下很可能无法访问。
查询代理的地理位置，返回的结果是{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
代理配置 无, 代理所在地：未知，IP查询频率受限

请问怎么解决这个问题？

**Comment by sierxue** [comment]
true 修改为 True 就可以了。

**Comment by FuckingNoO** [comment]
> true 修改为 True 就可以了。
还是不行啊
