### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by RichardQt** [binary-husky/chatgpt_academic#193]
![1](https://user-images.githubusercontent.com/70936615/229064656-56c27945-3781-46c2-9796-71067fc51fda.jpg)

运行报错，显示aiohttp包下的语法错误

python版本3.8.8
望大佬解决！

**Comment by binary-husky** [comment]
再确认下python的版本吧

建议用严格按照README中的conda安装步骤创建一个新环境
