### ISSUE TITLE
nohup后台运行问题

### ISSUE THREAD

**Issue by funners** [binary-husky/chatgpt_academic#197]
想问一下大家使用nohup运行后链接不显示咋办，服务在运行，不知道网址。

**Comment by funners** [comment]
![image](https://user-images.githubusercontent.com/33130760/229084024-e3c62d71-fbf7-453a-919c-7cd562a8f5c9.png)

**Comment by Okabe-Rintarou-0** [comment]
nohup python main.py > log.txt &

**Comment by funners** [comment]
> nohup python main.py > log.txt &

运行完log.txt文件是空的

**Comment by funners** [comment]
已解决，在运行的时候加入-u参数，程序不启用缓存
![image](https://user-images.githubusercontent.com/33130760/229105800-696b5925-82fd-4f49-8d3a-5726a41a395c.png)
