### ISSUE TITLE
最后运行python main.py时TypeError

### ISSUE THREAD

**Issue by dmhshuai** [binary-husky/chatgpt_academic#200]
网络代理状态：运行。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
Traceback (most recent call last):
  File "C:\Users\52501\Downloads\chatgpt_academic-master\main.py", line 59, in <module>
    statusDisplay = gr.Markdown(f"Tip: 按Enter提交, 按Shift+Enter换行。当前模型: {LLM_MODEL} \n {check_proxy(proxies)}")
                                                                                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\52501\Downloads\chatgpt_academic-master\check_proxy.py", line 4, in check_proxy
    proxies_https = proxies['https'] if proxies is not None else '无'
                    ~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
求解QAQ

**Comment by Okabe-Rintarou-0** [comment]
你的proxy 是不是填了一个字符串？请用[] 框起来作为一个数组

**Comment by dmhshuai** [comment]
> 你的proxy 是不是填了一个字符串？请用[] 框起来作为一个数组
这是我的代码QAQ
def check_proxy(proxies):
    import requests
    proxies_https = proxies['https'] if proxies is not None else '无'
    try:
        response = requests.get("https://ipapi.co/json/", proxies=proxies, timeout=4)
        data = response.json()
        print(f'查询代理的地理位置，返回的结果是{data}')
        if 'country_name' in data:
            country = data['country_name']
            result = f"代理配置 {proxies_https}, 代理所在地：{country}"
        elif 'error' in data:
            result = f"代理配置 {proxies_https}, 代理所在地：未知，IP查询频率受限"
        print(result)
        return result
    except:
        result = f"代理配置 {proxies_https}, 代理所在地查询超时，代理可能无效"
        print(result)
        return result


if __name__ == '__main__':
    import os; os.environ['no_proxy'] = '*' # 避免代理网络产生意外污染
    from toolbox import get_conf
    proxies, = get_conf('proxies')
    check_proxy(proxies)

**Comment by dmhshuai** [comment]
感谢
