### ISSUE TITLE
运行main.py时报错，请问类该怎么解决呀

### ISSUE THREAD

**Issue by HePatrick11** [binary-husky/chatgpt_academic#201]
![image](https://user-images.githubusercontent.com/129493336/229118360-50ce373b-0383-42d3-bf35-805c25ec3034.png)

**Comment by yuanyu1031** [comment]
执行
python -m pip install -r requirements.txt 
安装依赖的库

**Comment by Okabe-Rintarou-0** [comment]
建议装个anaconda
