### ISSUE TITLE
设置用户名密码后，通过公网IP远程访问显示“Connection errored out.”，在本机通过"127.0.0.1:port"访问无任何问题

### ISSUE THREAD

**Issue by Ron1116** [binary-husky/chatgpt_academic#202]
设置用户名密码后，通过公网IP远程访问，可正常登录，但是进行问答时显示“Connection errored out.”，在本机通过"127.0.0.1:port"访问无任何问题。关闭用户名密码，也可以通过公网IP远程正常进行问答。docker容器和conda环境下均是这种情况。gradio是通过阿里云镜像下载的最新版。
<img width="656" alt="截屏2023-03-31 20 26 26" src="https://user-images.githubusercontent.com/54891799/229119638-352db733-ac2c-42f5-804c-b811eb7676a2.png">

**Comment by sunchongwei** [comment]
首先，这是个很好的问题，但是很遗憾的告诉你这就是个bug ,在2.23上存在的bug !
原文地址：https://github.com/gradio-app/gradio/issues/3716

**Comment by Ron1116** [comment]
> 首先，这是个很好的问题，但是很遗憾的告诉你这就是个bug ,在2.23上存在的bug ! 原文地址：[gradio-app/gradio#3716](https://github.com/gradio-app/gradio/issues/3716)

明白了，看来是gradio的问题。感谢您的解答！

**Comment by 0xZhangxu** [comment]
有解决办法了: https://github.com/gradio-app/gradio/issues/3716#issuecomment-1493272631

**Comment by Ron1116** [comment]
临时解决方法见：https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/89#issuecomment-1468024223
