### ISSUE TITLE
新版更新后出现json解析不合常规

### ISSUE THREAD

**Issue by EvelynCarter** [binary-husky/chatgpt_academic#210]
[Local Message] Json Error

Traceback (most recent call last):

File "D:\tianyiyun\Chatgpt\predict.py", line 163, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\anacm\envs\Chatgpt\Lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\anacm\envs\Chatgpt\Lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\anacm\envs\Chatgpt\Lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

**Comment by Okabe-Rintarou-0** [comment]
"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }

**Comment by crazy-zxx** [comment]
+1

**Comment by binary-husky** [comment]
You exceeded your current quota, please check your plan and billing details.

**Comment by HusBunia** [comment]
> 报错信息在这："error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } 和你的openai账户有关

但是openai的网页还是可以登上去正常使用的。

**Comment by 1my23** [comment]
我也是，有额度用不了
