### ISSUE TITLE
what's wrong with it?

### ISSUE THREAD

**Issue by Succharo** [binary-husky/chatgpt_academic#214]
<img width="662" alt="截屏2023-04-01 上午3 50 08" src="https://user-images.githubusercontent.com/129551683/229217271-a7893e8c-82ab-4911-90a7-c1469822ea81.png">

**Comment by lanhao34** [comment]
Did you modified `config.py`? This error message says that the syntax at line 10 of `config.py` is wrong. You can try to revert the modification or re-download the source code from GitHub.

**Comment by whoaimedith** [comment]
按照说明进行配置才可以，另外你需要有openai的key

**Comment by binary-husky** [comment]
我想报错已经写的很清楚了，改config时，缩进改出问题了
