### ISSUE TITLE
1

### ISSUE THREAD

**Issue by wangwangwaang** [binary-husky/chatgpt_academic#217]
我这个是什么问题？
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gradio/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gradio/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gradio/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gradio/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gradio/
ERROR: Could not find a version that satisfies the requirement gradio>=3.23 (from versions: none)
ERROR: No matching distribution found for gradio>=3.23

**Comment by Okabe-Rintarou-0** [comment]
README 有写
# 备注：使用官方pip源或者阿里pip源，其他pip源（如清华pip）有可能出问题，临时换源方法： 
# pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

**Comment by Okabe-Rintarou-0** [comment]
使用官方源也可以：pip install gradio --index-url https://pypi.org/simple/

**Comment by binary-husky** [comment]
tsinghua他们镜像源这都宕机几天了还没好吗，醉了
