### ISSUE TITLE
A tiny problem about functional.py

### ISSUE THREAD

**Issue by ZhuZheart98** [binary-husky/chatgpt_academic#218]
there is a word mistake in 
"英语学术润色": {
            # 前言
            "Prefix":   r"Below is a paragraph from an academic paper. Polish the writing to meet the academic style, " +
                        r"improve the spelling, grammar, clarity, concision and overall readability. When neccessary, rewrite the whole sentence. " +
                        r"Furthermore, list all modification and explain the reasons to do so in markdown table." + "\n\n",

It should be "When necessary", extra "c"

**Comment by binary-husky** [comment]
3Q！

sorry for bad English

**Comment by binary-husky** [comment]
fixed in https://github.com/binary-husky/chatgpt_academic/commit/bca61754e3e79429d84ed14ec5840276920aaa48

**Comment by ZhuZheart98** [comment]
This is an excellent project, it takes a lot of effort to solve various bugs. Some small errors are inevitable, and I just do some minor help.
