### ISSUE TITLE
len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0 报错

### ISSUE THREAD

**Issue by RecoveryAshes** [binary-husky/chatgpt_academic#22]
`Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\chatgpt_academic-master\chatgpt_academic-master\predict.py", line 118, in predict
    if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

请问这个错误是什么原因，如何解决 chunk.decode()输出是 "error": {

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/227909185-8cbf9046-f393-491f-8c81-cccd9ea24156.png)
右下角显示啥？

**Comment by RecoveryAshes** [comment]
“error”: { “message”: “Invalid URL (POST /v1/chat/completions)”, “type”: “invalid_request_error”, “param”: null, “code”: null }}

**Comment by RecoveryAshes** [comment]
解决了，API_KEY有问题

**Comment by zulihit** [comment]
API_KEY有问题怎么检查有没有问题，我也碰到了这个问题

**Comment by RecoveryAshes** [comment]
> API_KEY有问题怎么查有没有问题，我也碰到了这个问题

我是换了一个号解决的，我也觉得很奇怪，明明那个号官网可以正常使用，但是key就是没法使用

**Comment by Fenglinyu** [comment]
Json解析不合常规 “error”: { “message”: “You exceeded your current quota, please check your plan and billing details.”, “type”: “insufficient_quota”, “param”: null, “code”: null }}   我也是这个问题

**Comment by linjie111** [comment]
所以怎么解决

**Comment by zulihit** [comment]
换个账号就行了
________________________________
发件人: wanglin ***@***.***>
发送时间: 2023年4月2日 19:48
收件人: binary-husky/chatgpt_academic ***@***.***>
抄送: zuli ***@***.***>; Comment ***@***.***>
主题: Re: [binary-husky/chatgpt_academic] len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0 报错 (Issue #22)


所以怎么解决

―
