### ISSUE TITLE
ModuleNotFoundError: No module named 'crazy_functions.读文章写摘要'

### ISSUE THREAD

**Issue by dk-liang** [binary-husky/chatgpt_academic#222]
![image](https://user-images.githubusercontent.com/23117298/229269710-522acd23-2bbf-46c3-a11f-17eabc4c3b84.png)

**Comment by binary-husky** [comment]
tree ~/chatgpt_academic 看看是不是缺失文件

**Comment by binary-husky** [comment]
另外是什么操作系统和python版本呢

**Comment by lanjingweilai** [comment]
啊我也是，前两天都能用今天一运行给我报这个错

**Comment by lanjingweilai** [comment]
> 啊我也是，前两天都能用今天一运行给我报这个错

然后我发现我这个路径下这几个py文件莫名其妙没了，重新解压重新配就好了
