### ISSUE TITLE
Linux arm64机器，armbian系统，python3.9.2，页面一直显示Loading...

### ISSUE THREAD

**Issue by weiqiang2310** [binary-husky/chatgpt_academic#228]
过程都没有问题，代理检测也没问题，然后打开页面一直在Loading...

**Comment by binary-husky** [comment]
两个小方块在转的那个页面吗？

**Comment by weiqiang2310** [comment]
> 两个小方块在转的那个页面吗？

是的

**Comment by Kiwamm** [comment]
![image](https://user-images.githubusercontent.com/50472785/229284573-dac02da1-7c01-459c-8fc9-d0f4519ec156.png)
一直这样

**Comment by Kiwamm** [comment]
![image](https://user-images.githubusercontent.com/50472785/229284600-db54734c-2ba4-40c7-8d9e-42da61e397c2.png)
一直这样

**Comment by binary-husky** [comment]
@weiqiang2310 这个确实没见过，arm的windows吗？

**Comment by weiqiang2310** [comment]
@binary-husky 电视盒子，系统armbian，就是debian

**Comment by michiko5173** [comment]
> > 两个小方块在转的那个页面吗？
> 
> 是的 <img alt="1680347958171" width="428" src="https://user-images.githubusercontent.com/61399256/229285736-8e13c624-8d57-4c8f-86b6-a975e62b91c0.png">

一样，你解决了嘛？

**Comment by weiqiang2310** [comment]
> > > 两个小方块在转的那个页面吗？
> > 
> > 
> > 是的 <img alt="1680347958171" width="428" src="https://user-images.githubusercontent.com/61399256/229285736-8e13c624-8d57-4c8f-86b6-a975e62b91c0.png">
> 
> 一样，你解决了嘛？

已排除故障，或许是gradio问题，卸载库重装，注意版本

**Comment by crankler** [comment]
请问有人解决了这个问题吗
