### ISSUE TITLE
解析项目

### ISSUE THREAD

**Issue by sjtuSecondSilly** [binary-husky/chatgpt_academic#229]
除了python项目之外，他还能解析其他程序语言的项目吗，比如matlab项目。
如果可以的话，这个要怎么操作呢？

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/229277756-c05c7356-4dcc-4b49-9587-c38207c7032d.png)

**Comment by binary-husky** [comment]
也就改一行代码的事

**Comment by sjtuSecondSilly** [comment]
可以
还有hxd,能不能直接丢pdf论文进去让他翻译啊

**Comment by binary-husky** [comment]
你试试
