### ISSUE TITLE
建议加上用户名和密码登录

### ISSUE THREAD

**Issue by smartnikocj** [binary-husky/chatgpt_academic#23]
Thx，建议加上用户名和密码登录。

**Comment by binary-husky** [comment]
https://gradio.app/sharing-your-app/#authentication
需要的话，加在main.py的最后一行。

**Comment by morestart** [comment]
> https://gradio.app/sharing-your-app/#authentication 需要的话，加在main.py的最后一行。

使用IP访问的话需要修改 `site-packages/gradio/routes.py `的 `ws_login_check`函数`access-token`到`access-token-unsecure`否则ws会报错

**Comment by smartnikocj** [comment]
> > https://gradio.app/sharing-your-app/#authentication 需要的话，加在main.py的最后一行。
> 
> 使用IP访问的话需要修改 `site-packages/gradio/routes.py `的 `ws_login_check`函数`access-token`到`access-token-unsecure`否则ws会报错

能直接改动main.py来达到同样目的不？

**Comment by smartnikocj** [comment]
> https://gradio.app/sharing-your-app/#authentication 需要的话，加在main.py的最后一行。

Thanks，但是加上之后，能登录，ask的时候出现了network error。估计是要像 @morestart 说的这样弄。

**Comment by binary-husky** [comment]
不需要吧，

```
demo.queue().launch(server_name="0.0.0.0", share=True, server_port=PORT, auth=[('webbrowser', 'webbrowserx'), ('webbrowser2', 'webbrowser2x')])
```

我这里测试没问题

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/228249982-02c6b7f9-956e-4bb1-b631-582e1875b03f.png)
![image](https://user-images.githubusercontent.com/96192199/228250009-f76a1cc1-5fbc-45fb-868b-53a585c87f26.png)

**Comment by smartnikocj** [comment]
> 不需要吧，
> 
> ```
> demo.queue().launch(server_name="0.0.0.0", share=True, server_port=PORT, auth=[('webbrowser', 'webbrowserx'), ('webbrowser2', 'webbrowser2x')])
> ```
> 
> 我这里测试没问题，不管是登陆还是其他功能都正常。是不是你gradio版本太旧了？

![image](https://user-images.githubusercontent.com/20366111/228402339-b19db454-6d9e-488b-a096-ef18c1dd30c0.png)
还是不行呀。

**Comment by xiaoliwe** [comment]
@smartnikocj  问题解决了么？ 同遇到“ Connection errored out" 的错误, 看样子，是config.py 最后的auth配置引起的？

**Comment by xiaoliwe** [comment]
补一张错误图：
<img width="665" alt="Screen Shot 2023-03-29 at 8 30 27 PM" src="https://user-images.githubusercontent.com/9930176/228536098-1f00f67c-2780-4b6b-ad53-f193d6a72ab1.png">

**Comment by binary-husky** [comment]
我似乎也见过这个bug，可能是gradio的bug，也许跟系统的环境有关系。但只要放docker里面就好了。

**Comment by tingod** [comment]
> 补一张错误图： <img alt="Screen Shot 2023-03-29 at 8 30 27 PM" width="665" src="https://user-images.githubusercontent.com/9930176/228536098-1f00f67c-2780-4b6b-ad53-f193d6a72ab1.png">

这看起来像是nginx代理未转发ws的原因。
试试在nginx内设置：

```
http {
     map $http_upgrade $connection_upgrade { 
        default          keep-alive; 
        'websocket'      upgrade;
    }
    ...
    server {
        ...
         location /xxx/ {
            proxy_pass http://xxxxx;
            proxy_set_header Upgrade $http_upgrade; 
            proxy_set_header Connection $connection_upgrade;
        }
    }
```

**Comment by xiaoliwe** [comment]
@tingod 赞～ ，确实是这个原因.

**Comment by 17TheWord** [comment]
> 

问题解决，感谢！

**Comment by 17TheWord** [comment]
> > 补一张错误图： <img alt="Screen Shot 2023-03-29 at 8 30 27 PM" width="665" src="https://user-images.githubusercontent.com/9930176/228536098-1f00f67c-2780-4b6b-ad53-f193d6a72ab1.png">
> 
> 这看起来像是nginx反代未转发ws的原因。 试试在nginx内设置：
> 
> ```
> http {
>      map $http_upgrade $connection_upgrade { 
>         default          keep-alive; 
>         'websocket'      upgrade;
>     }
>     ...
>     server {
>         ...
>          location /xxx/ {
>             proxy_pass http://xxxxx;
>             proxy_set_header Upgrade $http_upgrade; 
>             proxy_set_header Connection $connection_upgrade;
>         }
>     }
> ```

问题解决，感谢！

**Comment by panxiang126** [comment]
请问知道用 Clash for Windows 的怎么配置吗？
