### ISSUE TITLE
小白问一下没有历史记录是因为api不支持吗

### ISSUE THREAD

**Issue by 20171105130** [binary-husky/chatgpt_academic#230]

**Comment by binary-husky** [comment]
有历史记录的
![image](https://user-images.githubusercontent.com/96192199/229276785-cdacf70c-5c1c-4b81-b0bf-c506b9683e0a.png)

至于没有加载UI界面上的原因，
其一是不清楚历史记录到底有没有实际用途，如果有，在哪些场合有用；
其二是不知道怎么加才能美观可靠，在多人共用时，防止隐私泄露

**Comment by 20171105130** [comment]
> 有历史记录的 ![image](https://user-images.githubusercontent.com/96192199/229276785-cdacf70c-5c1c-4b81-b0bf-c506b9683e0a.png)
> 
> 至于没有加载UI界面上的原因， 其一是不清楚历史记录到底有没有实际用途，如果有，在哪些场合有用； 其二是不知道怎么加才能美观可靠，在多人共用时，防止隐私泄露
谢谢大佬，爱你
