### ISSUE TITLE
requirement文件的依赖包安装不成功

### ISSUE THREAD

**Issue by Varian789** [binary-husky/chatgpt_academic#231]
运行main.py文件报这个错怎么办。
AttributeError: module 'attr' has no attribute 's'

**Comment by Varian789** [comment]
python版本用anaconda更新到了3.11报了这个错。是版本没有安装队吗。requirement里面的依赖包也装好了

**Comment by Varian789** [comment]
我卸载了attrs包，重新安装，就不报错了。但是会一直报各种包不存在，都需要卸载重新安装，有办法可以批量卸载安装嘛

**Comment by binary-husky** [comment]
anaconda或者docker

![image](https://user-images.githubusercontent.com/96192199/229277607-0a84d07f-9ba1-4329-9ce6-008cdea82787.png)
