### ISSUE TITLE
部署到docker（Linux）后输入弹出Something went wrong Connection errored out.

### ISSUE THREAD

**Issue by BigYty** [binary-husky/chatgpt_academic#232]
![未标题-1](https://user-images.githubusercontent.com/35890111/229276103-895ac724-1cb5-46b7-89bf-a609aa6f0a9e.png)

**Comment by BigYty** [comment]
没有启用代理，我的服务器位于美国，ip正常

**Comment by binary-husky** [comment]
wiki上有总结其他人的经验

https://github.com/binary-husky/chatgpt_academic/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

也许是websocket的问题？
