### ISSUE TITLE
执行完main.py后是显示网页吗？我这里网页打不开，大佬知道什么情况吗？

### ISSUE THREAD

**Issue by 666666ing** [binary-husky/chatgpt_academic#233]

**Comment by gamilian** [comment]
加一

**Comment by hello-sky123** [comment]
我也是，执行完打不开网页

**Comment by CM-study-hard1** [comment]
我也打不开，执行完main.py后网络配置没问题，但是网页打不开

**Comment by song343119682** [comment]
我也是

**Comment by xuwuzhou** [comment]
+1

**Comment by xuwuzhou** [comment]
具体来讲，代理挂上去了，ip没问题，但是本地访问localhost一直被拒绝
![HC5$}I$X(ERE%SVK0 JFZKP](https://user-images.githubusercontent.com/44218507/229336641-084ef15d-46fb-4869-87c2-e233e9de5cc8.png)
![MHM具体来讲，代理挂上去了，ip没问题，但是本地访问localhost一直被拒绝
![HC5$}I$X(ERE%SVK0 JFZKP](https://user-images.githubusercontent.com/44218507/229336641-084ef15d-46fb-4869-87c2-e233e9de5cc8.png)
4@DS_MQMRGQUR9IC%6](https://user-images.githubusercontent.com/44218507/229336646-1c323f5c-7395-4f7f-aa64-81019c94ccdd.png)

**Comment by hello-sky123** [comment]
&nbsp; &nbsp; &nbsp; &nbsp; 我已经解决了这个问题，就是你执行完main.py弹出那个localhost网页以后，先关掉代理，然后刷新网页，就可以出来正常的页面了，然后打开代理！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
祝科研顺利^_^



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CM-study-hard1 ***@***.***&gt;
发送时间: 2023年4月2日 10:33
收件人: binary-husky/chatgpt_academic ***@***.***&gt;
抄送: ZHANGZhongping ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [binary-husky/chatgpt_academic] 执行完main.py后是显示网页吗？我这里网页打不开，大佬知道什么情况吗？ (Issue #233)





 
我也打不开，执行完main.py后网络配置没问题，但是网页打不开

**Comment by xuwuzhou** [comment]
> &nbsp; &nbsp; &nbsp; &nbsp; 我已经解决了这个问题，就是你执行完main.py弹出那个localhost网页以后，先关掉代理，然后刷新网页，就可以出来正常的页面了，然后打开代理！ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 祝科研顺利^_^ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: CM-study-hard1 ***@***.***&gt; 发送时间: 2023年4月2日 10:33 收件人: binary-husky/chatgpt_academic ***@***.***&gt; 抄送: ZHANGZhongping ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [binary-husky/chatgpt_academic] 执行完main.py后是显示网页吗？我这里网页打不开，大佬知道什么情况吗？ (Issue #233) 我也打不开，执行完main.py后网络配置没问题，但是网页打不开 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

试了，好像不起作用。

**Comment by 972063175** [comment]
我打开是白板，网页图标出来了，但没内容

**Comment by binary-husky** [comment]
都用的啥代理软件呀，连localhost都不放过吗

**Comment by zhouyulong** [comment]
> 都用的啥代理软件呀，连localhost都不放过吗

里面用了很多外部的 js/css等资源，有时候这些外部资源挂了代理反而加载不出来，原因似乎SSL版本不一致导致的问题，本质原因没有深究。所以出现了，关闭代理反正能正常打开页面的情况。
