### ISSUE TITLE
安装依赖出现问题，求大佬解答

### ISSUE THREAD

**Issue by chishichengyang** [binary-husky/chatgpt_academic#235]
![08261831cb7a1f09b3f2d45c973b561](https://user-images.githubusercontent.com/45236669/229277215-8d5cd0fc-f0eb-4523-8eb4-6306c4c88e5d.png)
![c6049be1ba1514399f4d013ef95cccf](https://user-images.githubusercontent.com/45236669/229277219-8e465720-4e87-45b6-8a16-a7fa54278583.png)
为什么安装包成功了，会出现这种报错？？求解答

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/229277509-4e0e9c2e-6479-43fa-901f-161c85ea4b1e.png)

**Comment by chishichengyang** [comment]
我有回去看了一遍视频，没问题啊
是因为路径问题吗？
我是直接在conda先创建一个叫chatgpt的环境，然后再promote安装包的，，我是用pycharm的，没有像你回答中的代码那样创建环境
我算是电脑小白，求解答qing
