### ISSUE TITLE
运行main.py时报错ModuleNotFoundError: No module named 'toolbox'

### ISSUE THREAD

**Issue by RW7077** [binary-husky/chatgpt_academic#240]
Traceback (most recent call last):
  File "D:\chatgpt academic\main.py", line 3, in <module>
    from predict import predict
  File "D:\chatgpt academic\predict.py", line 23, in <module>
    from toolbox import get_conf
ModuleNotFoundError: No module named 'toolbox'
求教该怎么解决

**Comment by binary-husky** [comment]
python版本？

**Comment by RW7077** [comment]
python版本是3.11.2

**Comment by RW7077** [comment]
现在变成这样了...
Traceback (most recent call last):
  File "D:\chatgpt academic\main.py", line 3, in <module>
    from predict import predict
  File "D:\chatgpt academic\predict.py", line 23, in <module>    
    from toolbox import get_conf
ImportError: cannot import name 'get_conf' from 'toolbox' (D:\anaconda\envs\chatgpt\Lib\site-packages\toolbox\__init__.py)

**Comment by RoderickChan** [comment]
> 现在变成这样了... Traceback (most recent call last): File "D:\chatgpt academic\main.py", line 3, in from predict import predict File "D:\chatgpt academic\predict.py", line 23, in from toolbox import get_conf ImportError: cannot import name 'get_conf' from 'toolbox' (D:\anaconda\envs\chatgpt\Lib\site-packages\toolbox__init__.py)

你的`toolbox__init__.py`是个啥

**Comment by RW7077** [comment]
那个目录下面搜索不到toolbox__init__.py 我也不清楚怎么回事

**Comment by RoderickChan** [comment]
> 那个目录下面搜索不到toolbox__init__.py 我也不清楚怎么回事
你按我这个pr修改后看看

**Comment by RW7077** [comment]
Traceback (most recent call last):
  File "D:\chatgpt academic\main.py", line 3, in <module>
    from predict import predict
  File "D:\chatgpt academic\predict.py", line 23, in <module>
    from toolbox import get_conf
ImportError: cannot import name 'get_conf' from 'toolbox' (D:\anaconda\envs\chatgpt\Lib\site-packages\toolbox\__init__.py)
还是这个结果

**Comment by RW7077** [comment]
ImportError: cannot import name 'get_conf' from 'toolbox' (D:\anaconda\envs\chatgpt\Lib\site-packages\toolbox\__init__.py)

**Comment by RW7077** [comment]
后面是toolbox\_init_.py

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/229291683-4b21ad3a-8a5b-4501-a44e-2e24b8259b63.png)
你配置conda环境严格按照这个来试试

**Comment by RW7077** [comment]
Traceback (most recent call last):
  File "D:\chatgpt academic\main.py", line 3, in <module>
    from predict import predict
  File "D:\chatgpt academic\predict.py", line 23, in <module>
    from toolbox import get_conf
ModuleNotFoundError: No module named 'toolbox'
变回这样了

**Comment by RoderickChan** [comment]
> Traceback (most recent call last): File "D:\chatgpt academic\main.py", line 3, in from predict import predict File "D:\chatgpt academic\predict.py", line 23, in from toolbox import get_conf ModuleNotFoundError: No module named 'toolbox' 变回这样了

1. print(sys.path) 看一下你的搜索路径
2. 当前目录是否有toolbox.py

**Comment by RW7077** [comment]
acaconda中有toolbox，python目录和搜索路径中没有；向python的搜索路径中添加后还是没用，
C:\Users\chn23>    pip install toolbox
Requirement already satisfied: toolbox in d:\anaconda\lib\site-packages (1.10.0)

>>> import toolbox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named toolbox

**Comment by RoderickChan** [comment]
> acaconda中有toolbox，python目录和搜索路径中没有；向python的搜索路径中添加后还是没用， C:\Users\chn23> pip install toolbox Requirement already satisfied: toolbox in d:\anaconda\lib\site-packages (1.10.0)
> 
> > > > import toolbox
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > ImportError: No module named toolbox

不要`pip install toolbox`

我说的当前目录是你执行`python main.py`的目录，会有一个`toolbox.py`文件

似乎你没有按照conda的安装教程来执行

**Comment by RW7077** [comment]
执行python main.py的目录中没有toolbox.pytoolbox.py

**Comment by binary-husky** [comment]
@RW7077  如果你确定文件确实存在，那应该只能是python版本或者文件读写权限。建议换个盘或者路径，或者使用docker
