### ISSUE TITLE
[Local Message] Request timeout. Network error. Please check proxy settings in config.py.

### ISSUE THREAD

**Issue by CGTpeach** [binary-husky/chatgpt_academic#243]
[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。
![image](https://user-images.githubusercontent.com/93721759/229289630-3cac12c7-ea25-429e-94f1-b02f2e5fe2fe.png)
![image](https://user-images.githubusercontent.com/93721759/229289662-56bdab3a-7092-4166-8e0f-1a6064e621c4.png)
![image](https://user-images.githubusercontent.com/93721759/229289671-e0d5cc8d-cefd-4435-baa8-c075be7de8b6.png)
都试过了还是报这个错误，怎么解决呀？

**Comment by binary-husky** [comment]
能显示代理所在地吗

**Comment by 15058415003** [comment]
如果用的clash的话，可以开启tun模式，关闭系统代理，然后把项目配置里的代理模式关了就行。我测试下来是没问题的

**Comment by HMTeen** [comment]
> 如果用的clash的话，可以开启tun模式，关闭系统代理，然后把项目配置里的代理模式关了就行。我测试下来是没问题的

我clash用tun模式不行，我用了代理：代理开全局，然后把“clash-常规”页面的端口号，在config.py文件对应修改，不用更改协议、地址，即可使用

**Comment by binary-husky** [comment]
#1
https://github.com/binary-husky/chatgpt_academic/wiki/%E4%BB%A3%E7%90%86%E8%BD%AF%E4%BB%B6%E9%97%AE%E9%A2%98%E7%9A%84%E6%96%B0%E6%89%8B%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95%EF%BC%88%E6%96%B9%E6%B3%95%E5%8F%AA%E9%80%82%E7%94%A8%E4%BA%8E%E6%96%B0%E6%89%8B%EF%BC%89

**Comment by Matthew1204** [comment]
同样的问题，以上方案均无法解决

**Comment by 15058415003** [comment]
以上方案均无法解决时，应当尝试更换机场或节点

**Comment by xigrug** [comment]
同样的问题，以上方案均无法解决

**Comment by chenliansgithub** [comment]
无法解决

**Comment by newgaor** [comment]
我用的是v2rayN，显示这个错误[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。运行check.py显示是美国，运行main.py显示代理所在地：China。这个怎么解决呀？

**Comment by yuyang-P** [comment]
原本我也碰到这个问题，试了以上方法都无效，就点击到“局域网设置”中的“对于本地地址不使用代理服务器”取消勾选之后发现就能用了。![image](https://user-images.githubusercontent.com/53478968/236630285-9162e45a-21d2-4c6b-973e-da626a5a4243.png)

**Comment by Iservei** [comment]
已解决，更改飞机场节点即可。
<img width="616" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/97902914/adfe221c-2df5-4a7b-b56c-c122b1af7acf">

**Comment by buIabuIab** [comment]
如果梯子有全局代理和智能代理两种模式的话，换成全局就可以了

**Comment by jasprehan** [comment]
> 如果用的clash的话，可以开启tun模式，关闭系统代理，然后把项目配置里的代理模式关了就行。我测试下来是没问题的

亲测有用，用clash直接开全局不行，开tun模式然后关了代理就可以
