### ISSUE TITLE
直接部署在外网服务器，用IP：端口访问，可以看到网页，但是不能提交问题

### ISSUE THREAD

**Issue by ATPs** [binary-husky/chatgpt_academic#244]
显示：
Something went wrong
Connection errored out.

已经把改为
demo.queue(concurrency_count=CONCURRENT_COUNT).launch(server_name="0.0.0.0", share=False, server_port=PORT, auth=AUTHENTICATION)

有设置密码。

**Comment by ATPs** [comment]
http//:my_ip:port 这种形式

**Comment by sunchongwei** [comment]
我了解到的是这是gradio的bug或者是产品特性，如果部署在外网还需要密码的话应该是要https协议。另外你如果还是用Http协议的话则需要降低版本，把gradio降低到3.16

**Comment by ATPs** [comment]
好像可以了，谢谢。
