### ISSUE TITLE
请对下面的程序文件做一个概述: E:\PycharmProjects\chatgpt_academic-master\mani.py

### ISSUE THREAD

**Issue by qiubo88** [binary-husky/chatgpt_academic#248]
很抱歉，我作为AI语言模型无法查看您电脑上的文件。但我可以根据文件名猜测该文件一般是用Python语言编写的，并且与名为"chatgpt_academic"的项目有关，文件名"mani.py"中可能包含了项目中的一些主程序或者函数。
无法实现示例教程的效果啊？什么情况？

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/229296189-14f64afb-caff-4d43-a2e1-cd4ed72bf700.png)
![image](https://user-images.githubusercontent.com/96192199/229296191-c96345f1-a826-4942-8bc3-551a3eecc7fd.png)

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/wiki/chatgpt-academic%E9%A1%B9%E7%9B%AE%E8%87%AA%E8%AF%91%E8%A7%A3%E6%8A%A5%E5%91%8A
