### ISSUE TITLE
还有api余额为什么还有这个

### ISSUE THREAD

**Issue by minkfusiki** [binary-husky/chatgpt_academic#254]
![}}SPA26K~JOPI(SN~N5EOYN](https://user-images.githubusercontent.com/104705115/229328128-d8e8ca22-cf41-4a16-90d2-2cedacf3a954.png)

**Comment by minkfusiki** [comment]
我处理成功了，就是封号了，另一方面，我配置还是有问题

**Comment by minkfusiki** [comment]
我被封的账号还在申诉。找个稳定的账号调用api。其余的就参考https://www.bilibili.com/video/BV1hL411X7bZ/?spm_id_from=333.1007.top_right_bar_window_history.content.click

**Comment by binary-husky** [comment]
余额过期了，我的也是刚过期

**Comment by binary-husky** [comment]
充钱吧

**Comment by binary-husky** [comment]
额度不足，或者额度没用完但是过期了#263
