### ISSUE TITLE
在docker的Linux容器中可以用吗，我下载到容器里面了。

### ISSUE THREAD

**Issue by 666666ing** [binary-husky/chatgpt_academic#256]
在docker的Linux容器中可以用吗，我下载到容器里面了。

我用的 v2rayN，显示 代理所在地查询超时，代理可能无效，
是我没有部署完成吗 ？
我使用的python -m pip install -r requirements.txt 部署，

有大佬解答一下吗？
![屏幕截图 2023-04-02 121353](https://user-images.githubusercontent.com/122001545/229330999-ee0477fc-a02e-4731-a6a6-b5b889a102ca.png)

**Comment by 666666ing** [comment]
这个容器里的代理ip应该怎么配置呀

**Comment by binary-husky** [comment]
-v 挂载代理端口
