### ISSUE TITLE
Something went wrong Connection errored out.

### ISSUE THREAD

**Issue by ttjygbtj** [binary-husky/chatgpt_academic#257]
### Describe the bug

启动程序后，能打开页面正常显示，但是上传文档或者发送提问法会出错“Something went wrong Connection errored out.”

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

按照正常步骤：
git clone https://github.com/binary-husky/chatgpt_academic.git
cd chatgpt_academic
python -m pip install -r requirements.txt 
python main.py

config.py的配置是：
USE_PROXY = True

### Screenshot

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/66538098/229296702-36166ed4-d077-4ee8-9af3-d263b3039dc5.png">
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/66538098/229327959-e8d3857d-9495-4c28-8a3f-cf1a8d294248.png">
给出了正确的API key，却发现从没使用过
<img width="809" alt="image" src="https://user-images.githubusercontent.com/66538098/229331202-a1850a02-d1f2-4a69-97d1-cb5e285d8e8f.png">

### Logs

```shell
控制台报错[Error] WebSocket connection to 'ws://localhost:62694/queue/join' failed: There was a bad response from the server. (x4)
```

### System Info

```shell
gradio:3.24.1
ProductName:macOS
ProductVersion:13.3
BuildVersion:22E252
```

### Severity

annoying

**Comment by FLIER001** [comment]
一样的问题。服务器仅开放了特定端口，即使在config.py中设定了特定端口，点击按钮或者上传文件都会报这个错

**Comment by ttjygbtj** [comment]
发现config.py这里不填写# 设置用户名和密码 AUTHENTICATION = []就可以正常了
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/66538098/229339653-bd07cd30-3519-4761-9234-324502a7d2fc.png">

**Comment by FredYuuu** [comment]
> 发现config.py这里不填写# 设置用户名和密码 AUTHENTICATION = []就可以正常了 <img alt="image" width="1084" src="https://user-images.githubusercontent.com/66538098/229339653-bd07cd30-3519-4761-9234-324502a7d2fc.png">

不设置用户名和密码 依然报错Connection errored out，我这里的情况是本地电脑部署工作正常，放在国外远程服务器就会报错

**Comment by binary-husky** [comment]
看下wiki吧

**Comment by liusky0212** [comment]
实测按照wiki配置下nginx 反代，问题解决。 
环境：clash+docker
应该是这个原因   https://github.com/gradio-app/gradio/issues/3716

**Comment by TonyHuang0711** [comment]
> 实测按照wiki配置下nginx 反代，问题解决。 环境：clash+docker 应该是这个原因 [gradio-app/gradio#3716](https://github.com/gradio-app/gradio/issues/3716)

似乎就是这个原因 我修改了gradio包的routes.py就可以正常使用了 感谢！
