### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by BNU-luoneng** [binary-husky/chatgpt_academic#260]
当尝试将下面一句话翻译为英文，就会报错，但代理显示似乎是正常的，不知道是啥原因，在线求解？
Please translate following sentence to English:

机制分析表明使用动态融合技术改进了上述地区各层垂直速度的模拟，其中对湿度垂直分布和凝结潜热廓线的改进起重要作用。

Tip: 按Enter提交, 按Shift+Enter换行。当前模型: gpt-3.5-turbo
代理配置 socks5h://localhost:9981, 代理所在地：China
[Local Message] Json Error

Traceback (most recent call last):

File "D:\CHATGPT\chatgpt_academic-master\predict.py", line 169, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "C:\Users\dell\miniconda3\lib\json__init__.py", line 348, in loads

return _default_decoder.decode(s)
File "C:\Users\dell\miniconda3\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\dell\miniconda3\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

**Comment by AnliComputer** [comment]
您好，请问你部署好之后遇到这样的问题嘛？Uncaught (in promise) TypeError z.stylesheets is not iterable。

**Comment by binary-husky** [comment]
#263
