### ISSUE TITLE
持续报错请帮帮我吧

### ISSUE THREAD

**Issue by shjzhai** [binary-husky/chatgpt_academic#265]
Traceback (most recent call last):
  File "/Users/zhai/Downloads/chatgpt_academic-master/main.py", line 93, in <module>
    checkboxes.select(fn_area_visibility, [checkboxes], [area_basic_fn, area_crazy_fn] )
AttributeError: 'CheckboxGroup' object has no attribute 'select'
这是什么问题呢？大家有遇到吗？

**Comment by shjzhai** [comment]
![截屏2023-04-02 17 23 04](https://user-images.githubusercontent.com/129656158/229344143-0fd7e4bd-a8ee-40de-99f7-a2e82d03ff24.png)

**Comment by binary-husky** [comment]
你好，如果新手建议严格使用anaconda环境，并严格按照README中的说明走

这是gradio的版本问题，又是pip镜像的受害者吗？

**Comment by binary-husky** [comment]
@shjzhai

**Comment by shjzhai** [comment]
> 你好，如果新手建议严格使用anaconda环境，并严格按照README中的说明走
> 
> 这是gradio的版本问题，又是pip镜像的受害者吗？

你好，我使用了anaconda来配置环境，使用conda install 安装gradio提示找不到，我搜索之后使用的conda install -c conda-forge gradio安装，但好像版本是3.23，现在应该怎么更新呢？（纯新手求教）

**Comment by shjzhai** [comment]
> 

我再次按照README中的教程安装了依赖，目前已经解决问题了，非常感谢。
如果安装gradio有问题的话，请参考下面这条代码
python -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
