### ISSUE TITLE
提示代理不生效，怎么办，用的是vpn软件

### ISSUE THREAD

**Issue by Royal18625194910** [binary-husky/chatgpt_academic#268]
![image](https://user-images.githubusercontent.com/58453927/229347176-bc8a5d1f-3950-4f1a-8f72-03af00ba5fe6.png)
![image](https://user-images.githubusercontent.com/58453927/229347195-dc1712e9-dde5-484e-a24b-d9c59e450cb8.png)
![image](https://user-images.githubusercontent.com/58453927/229347209-1ac9128e-7e63-49b4-ab8a-ddf8c0e39d83.png)

**Comment by binary-husky** [comment]
#1
