### ISSUE TITLE
设置端口时怎么找啊

### ISSUE THREAD

**Issue by Royal18625194910** [binary-husky/chatgpt_academic#281]
怎么找vpn软件的端口啊，找不到每次都是端口问题

**Comment by LXLPRC** [comment]
代理设置里面都有的

**Comment by Royal18625194910** [comment]
> 代理设置里面都有的

没有啊，我用的是快连vpn

**Comment by LXLPRC** [comment]
你是网页版吗，常用的都是config.py里面提到的那几款，这些都在软件显眼位置

**Comment by LXLPRC** [comment]
或者你打开本机网络设置，点代理，可以看到
![image](https://user-images.githubusercontent.com/101474094/229442261-6f5c1870-c2b7-4128-800c-c06bf080d67c.png)

**Comment by Royal18625194910** [comment]
![image](https://user-images.githubusercontent.com/58453927/229443434-84504fbd-9a4c-408c-bcc1-d8f8fd1486a5.png)
我这默认是关的，如果打开代理就上不了网了

**Comment by Royal18625194910** [comment]
> #1

不是clash，之前用clash根本登不上chatgpt，也不知道是ss还是v2ray，就是直接买的letsVpn软件，查看不了端口

**Comment by Royal18625194910** [comment]
> 我刚才下载看了，这玩意是个独立软件，你自己下载一个v2rayn试试 ![image](https://user-images.githubusercontent.com/101474094/229448004-19940bc5-8174-44f5-958d-5a6fa4a16a63.png) ，里面有推广的机场，剩下自己琢磨

感谢大佬，v2rayn可以，已经搞定了

**Comment by niuqudebimao** [comment]
老哥用哪边的端口地址啊，几个都测试了一下， 还是不行

**Comment by zd-w** [comment]
同样的问题，求助

**Comment by SamWangGibhub** [comment]
How to write proxy in vpn?

**Comment by qtencent7** [comment]
> > 代理设置里面都有的
> 
> 没有啊，我用的是快连vpn

请问快连的代理端口是多少
