### ISSUE TITLE
提示访问有问题

### ISSUE THREAD

**Issue by zeduth** [binary-husky/chatgpt_academic#282]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by zeduth** [comment]
[本地消息] Json错误

追溯（最近一次通话）：

文件“D:\chromedowload\chatgpt_academic-master (2)\chatgpt_academic-master\predict.py”，第 162 行，在预测中

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json__init__.py”，第 346 行，加载

return _default_decoder.decode(s)
文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py”，第 337 行，在解码中

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py”，第 355 行，在 raw_decode 中

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError：预期值：第 1 行第 1 列（字符 0）

阅读>

拒绝访问
您无权访问 chat.openai.com。

网站所有者可能设置了限制，阻止您访问该网站。

射线 ID：7b1f3f606e3224cd
时间戳：2023-04-03 06:27:45 UTC
您的 IP 地址：209.209.57.74
请求的 URL：chat.openai.com/backend-api/conversation
错误参考编号：1020
服务器ID：FL_4F547
用户代理：python-requests/2.28.2


[本地消息] Json错误

追溯（最近一次通话）：

文件“D:\chromedowload\chatgpt_academic-master (2)\chatgpt_academic-master\predict.py”，第 162 行，在预测中

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json__init__.py”，第 346 行，加载

return _default_decoder.decode(s)
文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py”，第 337 行，在解码中

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py”，第 355 行，在 raw_decode 中

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError：预期值：第 1 行第 1 列（字符 0）

阅读>

拒绝访问
您无权访问 chat.openai.com。

网站所有者可能设置了限制，阻止您访问该网站。

射线 ID：7b1f3f606e3224cd
时间戳：2023-04-03 06:27:45 UTC
您的 IP 地址：209.209.57.74
请求的 URL：chat.openai.com/backend-api/conversation
错误参考编号：1020
服务器ID：FL_4F547
用户代理：python-requests/2.28.2

**Comment by binary-husky** [comment]
无法复现

**Comment by zeduth** [comment]
> 无法复现

撒子意思
