### ISSUE TITLE
[local] Request timeout, network error. please check proxy settings in config.py.

### ISSUE THREAD

**Issue by xigrug** [binary-husky/chatgpt_academic#285]
代理配置 http://127.0.0.1:7890, 代理所在地：United States ，使用的是clash

看了下之前类似问题，好像还是没有确切的回答，是梯子用的人太多了吗？

**Comment by binary-husky** [comment]
先看下代理配置正不正确 #1
然后测试下api-key：https://huggingface.co/spaces/qingxu98/gpt-academic  
然后更新下代码，你这个代码太旧了
如果api-key测试通过，那就只能是梯子的问题了
