### ISSUE TITLE
弱弱的提问，怎么可以解析前端项目呢

### ISSUE THREAD

**Issue by LiZheGuang** [binary-husky/chatgpt_academic#286]
弱弱的提问，怎么可以解析前端项目呢

**Comment by binary-husky** [comment]
js?

https://github.com/binary-husky/chatgpt_academic/blob/master/crazy_functions/%E8%A7%A3%E6%9E%90%E9%A1%B9%E7%9B%AE%E6%BA%90%E4%BB%A3%E7%A0%81.py

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/229463516-3fa44278-caae-42a0-8b35-ce5d405d16a1.png)

**Comment by LiZheGuang** [comment]
> ![图像](https://user-images.githubusercontent.com/96192199/229463516-3fa44278-caae-42a0-8b35-ce5d405d16a1.png)

尊敬的作者你好，我发现了一个重复的对象声明，我在这个PR里进行修复 
https://github.com/binary-husky/chatgpt_academic/pull/290

**Comment by binary-husky** [comment]
> > ![图像](https://user-images.githubusercontent.com/96192199/229463516-3fa44278-caae-42a0-8b35-ce5d405d16a1.png)
> 
> 尊敬的作者你好，我发现了一个重复的对象声明，我在这个PR里进行修复 #290

谢谢！ 很不好意思，粗心搞出了这种幺蛾子
