### ISSUE TITLE
总结PDF文档出错

### ISSUE THREAD

**Issue by K8lyN-4ever** [binary-husky/chatgpt_academic#287]
[Local Message] 实验性函数调用出错:
Traceback (most recent call last):
File "F:\other\academicGPT\toolbox.py", line 81, in decorated
yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
File "F:\other\academicGPT\crazy_functions\批量总结PDF文档.py", line 99, in 批量总结PDF文档
yield from 解析PDF(file_manifest, project_folder, top_p, temperature, chatbot, history, systemPromptTxt)
File "F:\other\academicGPT\crazy_functions\批量总结PDF文档.py", line 49, in 解析PDF
res = write_results_to_file(history)
File "F:\other\academicGPT\toolbox.py", line 59, in write_results_to_file
f.write(content)
TypeError: write() argument must be str, not None
当前代理可用性:
代理配置 http://127.0.0.1:7890, 代理所在地：未知，IP查询频率受限

运行check_proxy.py可以正常识别到代理IP

**Comment by binary-husky** [comment]
更新代码

**Comment by K8lyN-4ever** [comment]
> 更新代码

感谢！
现在不会出现如上错误，但是会有这样的问题：
[Local Message] 异常：HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')).
是因为梯子的质量不好吗（我的宽带不是很好）

**Comment by binary-husky** [comment]
> > 更新代码
> 
> 感谢！ 现在不会出现如上错误，但是会有这样的问题： [Local Message] 异常：HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')). 是因为梯子的质量不好吗（我的宽带不是很好）

可能吧，是瞬间报错还是等半分钟之后才报错？如果是等待很久的情况，和梯子有关系
建议用 https://huggingface.co/spaces/qingxu98/gpt-academic 测试下key有没有问题
