### ISSUE TITLE
代理检察过了。但是还是无法创建TCP不知道问题在哪里

### ISSUE THREAD

**Issue by GhostYee** [binary-husky/chatgpt_academic#288]
**Describe the bug 简述**
代理检察过了。但是还是无法创建TCP不知道问题在哪里，应该怎么解决，有什么思路
**Screen Shot 截图**

Traceback (most recent call last):
  File "/Users/***/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/***/miniconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/***/miniconda3/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Terminal Traceback 终端traceback（如果有）**

**Comment by GhostYee** [comment]
> **Describe the bug 简述** 代理检察过了。但是还是无法创建TCP不知道问题在哪里，应该怎么解决，有什么思路 **Screen Shot 截图**
> 
> Traceback (most recent call last): File "/Users/_**/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/Users/**_/miniconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "/Users/***/miniconda3/lib/python3.10/socket.py", line 955, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno 8] nodename nor servname provided, or not known
> 
> **Terminal Traceback 终端traceback（如果有）**

是MAC

**Comment by binary-husky** [comment]
下面这个问题和mac有关，没用过mac，有用过的可以回答下

https://stackoverflow.com/questions/20252294/ssh-could-not-resolve-hostname-hostname-nodename-nor-servname-provided-or-n
