### ISSUE TITLE
运行main.py时报错，求指点

### ISSUE THREAD

**Issue by zalpbcog** [binary-husky/chatgpt_academic#289]
![{O`J1 $~ H351Z8JS2YYN9F](https://user-images.githubusercontent.com/101802805/229473758-64d9b5c9-c92c-44e1-a6cd-2bf82a293cfe.png)

**Comment by ZRQii** [comment]
运行main.py，import error: cannot import name timeout_seconds
Traceback (most recent call last):
  File "D:\39887\Documents\chatgpt_academic\predict.py", line 12, in <module>
    try: from config_private import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
ImportError: cannot import name 'TIMEOUT_SECONDS' from 'config_private' (D:\39887\Documents\chatgpt_academic\config_private.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from predict import predict
  File "D:\39887\Documents\chatgpt_academic\predict.py", line 13, in <module>
    except: from config import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
ImportError: cannot import name 'TIMEOUT_SECONDS' from 'config' (D:\39887\Documents\chatgpt_academic\config.py)

**Comment by ZRQii** [comment]
api key 是chatgpt4

**Comment by binary-husky** [comment]
更新代码 @ZRQii

**Comment by ZRQii** [comment]
非常感谢，已解决
