### ISSUE TITLE
用的是Mac版的小火箭，config文件里的代理应如何配置

### ISSUE THREAD

**Issue by lugaochao** [binary-husky/chatgpt_academic#29]
用的是Mac版的小火箭，应该如何配置proxies

**Comment by binary-husky** [comment]
大体步骤是一样的。

具体细节得劳驾用过macos的来解答下啦😂

**Comment by luze2021** [comment]
代理的json文件内容如下
{
  "host" : "zh01lv3tw02.feiguayun.xyz",
  "file" : "",
  "obfsParam" : "",
  "alpn" : "",
  "cert" : "",
  "created" : 1678109143.7620711,
  "updated" : 1678109143.7629728,
  "mtu" : "",
  "flag" : "TW",
  "ping" : 31,
  "privateKey" : "",
  "uuid" : "92FEA794-3327-4D9D-9D4A-88DBE2B45C65",
  "type" : "Shadowsocks",
  "downmbps" : "",
  "user" : "",
  "plugin" : "",
  "method" : "aes-256-gcm",
  "data" : "",
  "udp" : 1,
  "filter" : "",
  "protoParam" : "",
  "reserved" : "",
  "alterId" : "",
  "keepalive" : "",
  "upmbps" : "",
  "port" : "50321",
  "obfs" : "none",
  "dns" : "",
  "publicKey" : "",
  "peer" : "",
  "weight" : 1678109143,
  "ip" : "",
  "title" : "lv.3-台湾2-NF&动画疯",
  "proto" : "none",
  "password" : "18c8aaa4-46fa-4589-80bf-68071be9e283",
  "chain" : ""
}

**Comment by KarryChiang** [comment]
同问，我用的是mac版的ClashX，也有相同的问题

**Comment by Austin-Jack** [comment]
> 用的是Mac版的小火箭，应该如何配置proxies

mac版的小火箭是M1原生版本的吗

**Comment by binary-husky** [comment]
@luze2021 别放这种私密信息呀，尽快删除吧，😂，这个是连接远程服务器用的，你要找的是本地代理协议和端口

duplication of #1

**Comment by luze2021** [comment]
> 大体步骤是一样的。
> 
> 具体细节得劳驾用过macos的来解答下啦😂

感谢大佬，问题已解决

**Comment by luze2021** [comment]
> macOS 一直在报这个错唉 #assert False, "请在config文件中修改API密钥, 添加海外代理之后再运行" API Key也添加好了呢，端口写修改好了，终端反馈是「网络代理状态：运行。」但一直跳到最后的#assert False报错，求救🆘一下啦~~，从demo网站里，用API Key可以正常反馈，说明key没有问题，可能还是代理的问题吧？

删掉最后三行
# 检查一下是不是忘了改config
if API_KEY == "sk-此处填API秘钥":
    assert False, "请在config文件中修改API密钥, 添加海外代理之后再运行"

**Comment by luze2021** [comment]
> > 用的是Mac版的小火箭，应该如何配置proxies
> 
> mac版的小火箭是M1原生版本的吗

是的

**Comment by luze2021** [comment]
配置规则如下 proxies = { "http": "127.0.0.1:*****", "https": "127.0.0.1:*****", } ，其中*****代表的含义是你本地的端口号

**Comment by Austin-Jack** [comment]
> 

求推一下链接

**Comment by Austin-Jack** [comment]
> > > 用的是Mac版的小火箭，应该如何配置proxies
> > 
> > 
> > mac版的小火箭是M1原生版本的吗
> 
> 是的

求推一下下载链接

**Comment by luze2021** [comment]
![Uploading iShot_2023-03-28_19.30.58.png…]()
本地端口号如上图所示。

**Comment by luze2021** [comment]
> > > > 用的是Mac版的小火箭，应该如何配置proxies
> > > 
> > > 
> > > mac版的小火箭是M1原生版本的吗
> > 
> > 
> > 是的
> 
> 求推一下下载链接

我自己注册的美区的apple id，然后某宝买的礼品卡，自己买的小火箭

**Comment by luze2021** [comment]
也可以参考部署的视频https://www.bilibili.com/video/BV1Th411V75K/?spm_id_from=333.999.0.0&vd_source=c9e21af39fadd099941149d255974c85

**Comment by RedMery** [comment]
proxies = { "http": "http://127.0.0.1:63864", "https": "http://127.0.0.1:63864", }
配置成这样可行
<img width="831" alt="截屏2023-04-02 18 11 38" src="https://user-images.githubusercontent.com/33085987/229346614-4f4b06d3-32fe-4ac6-9bc9-1b564f966ff4.png">
