### ISSUE TITLE
Json Error

### ISSUE THREAD

**Issue by 1511351836** [binary-husky/chatgpt_academic#295]
我完全按照指示进行了安装，我是使用conda的，所以运行了
# （选择二）如果您使用anaconda，步骤也是类似的：
# （选择二.1）conda create -n gptac_venv python=3.11
# （选择二.2）conda activate gptac_venv
# （选择二.3）python -m pip install -r requirements.txt

但发送了信息之后却得到这样的结果
![image](https://user-images.githubusercontent.com/34052270/229529486-414a5539-4740-45d9-ae11-e46a2c5644fa.png)

[Local Message] Json Error

Traceback (most recent call last):

File "D:\chatgpt_academic\predict.py", line 169, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\application\anaconda3\envs\gptac_venv\Lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\application\anaconda3\envs\gptac_venv\Lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\application\anaconda3\envs\gptac_venv\Lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

**Comment by binary-husky** [comment]
#279
另外，请更新代码
