### ISSUE TITLE
找不到本地项目或无权访问

### ISSUE THREAD

**Issue by williamlorder** [binary-husky/chatgpt_academic#296]
出现了下面的情况。无法读取代码文件
<img width="841" alt="截屏2023-04-03 22 28 11" src="https://user-images.githubusercontent.com/83387569/229539900-3012ddcd-19ec-4feb-bbda-ebcc98b7116b.png">

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/229553919-189de95d-9b4b-48b0-9e41-7c82da8eef66.png)
