### ISSUE TITLE
json error , json 异常 求助

### ISSUE THREAD

**Issue by freemank1224** [binary-husky/chatgpt_academic#298]
**Describe the bug 简述**
配置都是成功的，但是干啥都直接跳出这一段：

>  [Local Message] 异常
> 
> Traceback (most recent call last):
>   File "C:\Users\Dyson\Documents\chatgpt_academic\predict.py", line 169, in predict
>     if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ProgramData\Anaconda3\envs\academic\Lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ProgramData\Anaconda3\envs\academic\Lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ProgramData\Anaconda3\envs\academic\Lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> "error": { "message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.", "type": "access_terminated", "param": null, "code": null }}

**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/24630609/229560680-ca9e84b1-1ca1-4894-bcd0-0c2412044bc8.png)

**Comment by TonyHuang0711** [comment]
git更新一下代码就会变成[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由，拒绝服务.
检查了余额重新生成了APIKEY也无效

**Comment by binary-husky** [comment]
用https://huggingface.co/spaces/qingxu98/gpt-academic检查apikey

**Comment by cunning2017** [comment]
解决了吗 我也是

**Comment by freemank1224** [comment]
> 解决了吗 我也是

解决了，这个问题的根本原因是我的API权限被封了…… 二月就被封了 只是我不知道，但是我的账号是正常用的，我看了邮件才知道。换了别人的API就好了
