### ISSUE TITLE
Json解析不合常规，很可能是文本过长

### ISSUE THREAD

**Issue by EvA56356** [binary-husky/chatgpt_academic#299]
![image](https://user-images.githubusercontent.com/111786705/229601106-887db481-9ede-4890-a355-0e27888b4545.png)

**Comment by WhItEG-bit** [comment]
加一

**Comment by TonyHuang0711** [comment]
![1680572019998](https://user-images.githubusercontent.com/60097976/229663540-f13760d5-70a1-4c60-9831-eeac6a5a31df.png)
+1 今天突然就这样了 昨天早上还是好好的 是不是官方更改了返回的json结构？

**Comment by TonyHuang0711** [comment]
uodate：这个error在重新pull代码后变成了[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由，拒绝服务.
再重新生成APIKEY后依然是这个问题 似乎问题在predict.py中

**Comment by binary-husky** [comment]
代码陈旧，更新代码

**Comment by TonyHuang0711** [comment]
我的是更新了代码 但是在确定api可用的情况下还是显示openai拒绝服务 余额不足字样&nbsp; &nbsp;&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月4日(周二) 下午3:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [binary-husky/chatgpt_academic] Json解析不合常规，很可能是文本过长 (Issue #299)




 
代码陈旧，更新代码
