### ISSUE TITLE
基于clash for MacOS，代理check总是出问题

### ISSUE THREAD

**Issue by Nijika-Ijichi** [binary-husky/chatgpt_academic#303]
**Describe the bug 简述**
1、自己按照config.py中所述的方式操作，出现问题后也看了#1 中的解决方式，结果还是不行，在代理check部分就过不去。
2、关于代理问题：
（1）如图所示，在我挂上Clash（澳洲梯子）后，运行check_proxy.py查看代理时，显示代理所在地仍在China，然而在https://ipapi.co/json/ 上检查，却是Australia
（2）这样的问题，导致我无论如何修改proxies，都会卡在代理check部分
**Screen Shot 截图**
<img width="560" alt="截屏2023-04-04 11 43 55" src="https://user-images.githubusercontent.com/129817549/229681841-0b90ca61-4a7b-4362-ac96-e89fe2b191ec.png">
![截屏2023-04-04 11 44 45](https://user-images.githubusercontent.com/129817549/229681970-1492d5ff-9b54-4277-a659-383fb6f0cf01.png)

**Comment by binary-husky** [comment]
USE_PROXY = True

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/wiki

**Comment by Nijika-Ijichi** [comment]
> USE_PROXY = True

感谢owner解答，不过把USE_PROXY设置为True之后，问题仍然存在。最开始倒腾的时候也没有忽视这一项，如果是我忽视了它，我完全没有提问的必要:(

怕表述不清楚，就简单完善一下问题：#1 中并未找到适用于clash for MacOS的解决方式，即便已经设置"USE_PROXY = True"
