### ISSUE TITLE
输出区域Markdown能否支持代码高亮

### ISSUE THREAD

**Issue by Masterlovsky** [binary-husky/chatgpt_academic#304]
![image](https://user-images.githubusercontent.com/45965357/229684958-e9c0da20-7454-4eef-985e-85105ca8cd61.png)
如上图，暗模式下看代码很不方便，能否实现语法高亮显示？

**Comment by binary-husky** [comment]
暂无方案，欢迎pr和讨论

**Comment by Masterlovsky** [comment]
version2.5 supported this issue!
