### ISSUE TITLE
这个到底要怎么开始第一步呢？

### ISSUE THREAD

**Issue by earth-5G** [binary-husky/chatgpt_academic#314]
我看教程，第一步下载哪个东西，哪个网址要在哪里输入呢？下载一个python？我试了，好像没反应。你们是怎么弄的。请指教12！

**Comment by yuan1311467** [comment]
下vscode/python 3.11
在vscode里装python拓展，以及绑定python 3.11，再用vscode打开文件夹，改好config之后找到main，f5运行。可能会提示缺东西。缺什么你就用vscode的终端下载什么就好
csdn上也可以搜得到如何再vscode上运行python

**Comment by Okabe-Rintarou-0** [comment]
建议用anaconda。
