### ISSUE TITLE
input路径是什么样的？

### ISSUE THREAD

**Issue by yuan1311467** [binary-husky/chatgpt_academic#317]
是  ./crazy_functions/test_project/latex/attention/+txt  文件吗？
为啥提示《找不到任何.tex文件: ./crazy_functions/test_project/latex/attention/yjz_test.txt》

**Comment by binary-husky** [comment]
选择1：
输入  ./crazy_functions/test_project/latex/attention/，然后按解析py项目

选择2：
打包python项目，上传到文件上传区，然后按解析py项目
