### ISSUE TITLE
【开发者】我们在dev_ui分支发布了新界面布局的测试，欢迎大家测试和反馈

### ISSUE THREAD

**Issue by binary-husky** [binary-husky/chatgpt_academic#322]
# 更新一：输入区位置的切换
## 不勾选 底部输入区
![image](https://user-images.githubusercontent.com/96192199/229846165-d1173f6d-4191-43a4-920f-b9540c805c16.png)
## 勾选 底部输入区
![image](https://user-images.githubusercontent.com/96192199/229846275-c3e8d254-ae56-4f18-a8c1-425be226f3a5.png)

# 更新二：新增上下布局（"TOP-DOWN"）
调整的方式是在config.py中调整LAYOUT选项："LEFT-RIGHT"（左右布局） # "TOP-DOWN"（上下布局）
![image](https://user-images.githubusercontent.com/96192199/229846438-3476e7b6-4ab9-4dff-ae90-f485371a3a73.png)

## 不勾选 底部输入区
![image](https://user-images.githubusercontent.com/96192199/229846892-beeea866-a695-4bc4-906c-b169ffd89b02.png)

## 勾选 底部输入区
![image](https://user-images.githubusercontent.com/96192199/229846940-39e644c6-cad5-49fd-8bed-a566a6348c69.png)

## 隐藏基础功能区和函数插件区之后
![image](https://user-images.githubusercontent.com/96192199/229849631-091c557e-57ba-4979-af9c-139f1f22ce85.png)

**Comment by binary-husky** [comment]
新分支的下载方法
git clone https://github.com/binary-husky/chatgpt_academic.git -b dev_ui

**Comment by binary-husky** [comment]
修复了几个函数wrapper的bug

**Comment by cyrilyoung** [comment]
不起作用了

**Comment by binary-husky** [comment]
#342
