### ISSUE TITLE
目标计算机积极拒绝怎样解决

### ISSUE THREAD

**Issue by dk8625** [binary-husky/chatgpt_academic#326]
**[Local Message] 异常：SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')).

**Comment by cosmopolitan033** [comment]
i'm facing the same problem, plz let me know how if u worked out the issue
