### ISSUE TITLE
模型怎么改成gpt4

### ISSUE THREAD

**Issue by Austin-Jack** [binary-husky/chatgpt_academic#33]
要申请是什么意思，我能在官网用4.0模型，在配置文件这样改吗
LLM_MODEL = "gpt4"
改了出错了

**Comment by binary-husky** [comment]
用api需要额外申请，好像要填个表格，哪位仁兄有成功经验来讲讲😂

**Comment by Austin-Jack** [comment]
还有就是用自己的域名能登陆但是不能问答，用给的public url没问题，因为问答是wss协议的原因吗

**Comment by Austin-Jack** [comment]
> 还有就是用自己的域名能登陆但是不能问答，用给的public url没问题，因为问答是wss协议的原因吗

或者说是我服务器ip被chatgpt限制了，但是public url是走了代理的所以没有问题是吗

**Comment by from-china-to** [comment]
> > 还有就是用自己的域名能登陆但是不能问答，用给的public url没问题，因为问答是wss协议的原因吗
> 
> 或者说是我服务器ip被chatgpt限制了，但是public url是走了代理的所以没有问题是吗
 
要不要加个联系方式一起交流交流摸索摸索试试

**Comment by Austin-Jack** [comment]
> > > 还有就是用自己的域名能登陆但是不能问答，用给的public url没问题，因为问答是wss协议的原因吗
> > 
> > 
> > 或者说是我服务器ip被chatgpt限制了，但是public url是走了代理的所以没有问题是吗
> 
> 要不要加个联系方式一起交流交流摸索摸索试试

wx: llynsyw

**Comment by hqy2020** [comment]
我也想知道什么时候能用gpt4的接口

**Comment by ZacharyZhang-NY** [comment]
你得再openai的api官网申请啊，这个和chatgpt的gpt4模型不是同一个地方，cahtgpt你可以用gpt4不代表你能用api。https://platform.openai.com/overview在这里注册之后，需要申请GPT-4 api的权限，现在都是再排队，不知道什么时候才能开放呢

**Comment by ShiXiangnan** [comment]
> 要申请是什么意思，我能在官网用4.0模型，在配置文件这样改吗 LLM_MODEL = "gpt4" 改了出错了

会不会是改成gpt-4

**Comment by ZacharyZhang-NY** [comment]
> > 要申请是什么意思，我能在官网用4.0模型，在配置文件这样改吗 LLM_MODEL = "gpt4" 改了出错了
> 
> 会不会是改成gpt-4

是需要有权限的，假如你申请成功：
LATEST MODEL | DESCRIPTION | MAX TOKENS | TRAINING DATA
-- | -- | -- | --
gpt-4 | More capable than any GPT-3.5 model, able to do more complex tasks, and optimized for chat. Will be updated with our latest model iteration. | 8,192 tokens | Up to Sep 2021
gpt-4-0314 | Snapshot of gpt-4 from March 14th 2023. Unlike gpt-4, this model will not receive updates, and will only be supported for a three month period ending on June 14th 2023. | 8,192 tokens | Up to Sep 2021
gpt-4-32k | Same capabilities as the base gpt-4 mode but with 4x the context length. Will be updated with our latest model iteration. | 32,768 tokens | Up to Sep 2021
gpt-4-32k-0314 | Snapshot of gpt-4-32 from March 14th 2023. Unlike gpt-4-32k, this model will not receive updates, and will only be supported for a three month period ending on June 14th 2023. | 32,768 tokens | Up to Sep 2021

**Comment by wucangeo** [comment]
我买了Plus也买了API，但改了“gpt-4”后还是报错，估计是还没对GPT4做好适配。
名称应该没错，参考：https://platform.openai.com/docs/models/gpt-4

`Traceback (most recent call last):
  File "/gpt/request_llm/bridge_chatgpt.py", line 169, in predict
    if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
^CKeyboard interruption in main thread... closing server.`

**Comment by ShiXiangnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wucangeo** [comment]
> 我买了Plus也买了API，但改了“gpt-4”后还是报错，估计是还没对GPT4做好适配。 名称应该没错，参考：https://platform.openai.com/docs/models/gpt-4
> 
> ```
> Traceback (most recent call last):
>   File "/gpt/request_llm/bridge_chatgpt.py", line 169, in predict
>     if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ^CKeyboard interruption in main thread... closing server.
> ```

最新的3.x好像已经支持了

**Comment by ShiXiangnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
