### ISSUE TITLE
导入软件依赖失败的问题

### ISSUE THREAD

**Issue by weiyoubest** [binary-husky/chatgpt_academic#331]
导入软件依赖失败。使用该模块需要额外依赖，安装方法pip install --upgrade pymupdf。
导入软件依赖失败。使用该模块需要额外依赖，安装方法pip install --upgrade python-docx pywin32。

对PDF或者WORD进行总结的时候提示这两个错误，但是这两个库我均已经安装完成并重启过电脑，还是提示这个错误，你们遇到过吗？

**Comment by binary-husky** [comment]
电脑上有几个python呢？😂

**Comment by weiyoubest** [comment]
> 电脑上有几个python呢？😂

之前有2个3.8 3.11  现在把3.8删了 还是这个报错 请问怎么解决？

**Comment by weiyoubest** [comment]
正在使用的版本也是3.11  没有问题..头疼

**Comment by amingson** [comment]
> 搞定了

请问您是这么处理的呢？方便分享一下？

**Comment by kylinqin** [comment]
> 搞定了

请问是如何处理的？

**Comment by PIANNOion** [comment]
> 搞定了

请问是怎么处理的啊
