### ISSUE TITLE
【BUG】一切部署成功，返回地址和链接地址在新加坡，网页弹出但无UI

### ISSUE THREAD

**Issue by chewgunboy** [binary-husky/chatgpt_academic#336]
**Describe the bug 简述**
我按照操作全部进行，也报出成功，运行72小时，科学上网链接成功，弹出了本地链接

进入之后，完全没有UI界面，反复实验两次，为了排除插件干扰分别使用了chrome，edge，和完全么没打插件的firefox

**Screen Shot 截图**

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
提供信息不足
