### ISSUE TITLE
为何LaTeX公式无法显示？

### ISSUE THREAD

**Issue by ssln5014** [binary-husky/chatgpt_academic#338]
**Describe the bug 简述**
如图所示
**Screen Shot 截图**
![Screenshot_20230406104820](https://user-images.githubusercontent.com/81206855/230260371-ca1cc35b-fd61-49e7-9499-551c15c52d8a.jpg)

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
复现方法？

**Comment by ssln5014** [comment]
> 

在replit上搭建，按照文档安装，网址是https://ai.reol.ml

**Comment by binary-husky** [comment]
本地不能复现，huggingface也不能复现：
![image](https://user-images.githubusercontent.com/96192199/230272620-164ed9b9-301f-48f8-be11-fee97188e365.png)

![image](https://user-images.githubusercontent.com/96192199/230272439-e1635cb5-21e8-442a-bff2-007bb8ba1a64.png)

**Comment by ssln5014** [comment]
> 本地不能复现，huggingface也不能复现： ![image](https://user-images.githubusercontent.com/96192199/230272620-164ed9b9-301f-48f8-be11-fee97188e365.png)
> 
> ![image](https://user-images.githubusercontent.com/96192199/230272439-e1635cb5-21e8-442a-bff2-007bb8ba1a64.png)

好的，无妨
