### ISSUE TITLE
请教windows config文件配置问题

### ISSUE THREAD

**Issue by njausxl** [binary-husky/chatgpt_academic#34]
在知乎上转载了您的项目，然后好多人都来问我，如何配置windows系统上的。https://zhuanlan.zhihu.com/p/616922151

下面是我的代码，我的代理从clasn换到v2rayN 切换了全局和PAC模式还是没法使用。

我的API key也没有过期，request.txt文件也全部都安装成功了。

请您帮忙看一下该如何解决，我好教一下其他人

`
# API_KEY = "sk-8dllgEAW17uajbDbv7IST3BlbkFJ5H*" 此key无效
API_KEY = "sk-Qs0onCC6CGeh5c0gZ4RvT3BlbkFJCjgx6AR******"
API_URL = "https://api.openai.com/v1/chat/completions"

# 改为True应用代理
USE_PROXY = True
if USE_PROXY:
    # 代理网络的地址，打开你的科学上网软件查看代理的协议(socks5/http)、地址(localhost)和端口(11284)
    proxies = { "http": "sock5h://127.0.0.1:61007", "https": "sock5h://127.0.0.1:61107", } 
    print('网络代理状态：运行。')
else:
    proxies = None
    print('网络代理状态：未配置。无代理状态下很可能无法访问。')

# 发送请求到OpenAI后，等待多久判定为超时
TIMEOUT_SECONDS = 20

# 网页的端口, -1代表随机端口
WEB_PORT = -1

# 如果OpenAI不响应（网络卡顿、代理失败、KEY失效），重试的次数限制
MAX_RETRY = 2

# 选择的OpenAI模型是（gpt4现在只对申请成功的人开放）
LLM_MODEL = "gpt-3.5-turbo"

# 检查一下是不是忘了改config
if API_KEY == "sk-Qs0onCC6CGeh5c0gZ4*":
    assert False, "请在config文件中修改API密钥, 添加海外代理之后再运行"

# 运行main.py 结果

网络代理状态：运行。
Traceback (most recent call last):
  File "C:\Users\sxl\Desktop\下载\chatgpt_academic\predict.py", line 12, in <module>
    try: from config_private import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
ModuleNotFoundError: No module named 'config_private'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from predict import predict
  File "C:\Users\sxl\Desktop\下载\chatgpt_academic\predict.py", line 13, in <module>
    except: from config import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
  File "C:\Users\sxl\Desktop\下载\chatgpt_academic\config.py", line 29, in <module>
    assert False, "请在config文件中修改API密钥, 添加海外代理之后再运行"
AssertionError: 请在config文件中修改API密钥, 添加海外代理之后再运行

`

**Comment by Pefect96** [comment]
遇到了同样的问题

**Comment by AtalsZem** [comment]
蹲

**Comment by doyle1996** [comment]
蹲

**Comment by onetance** [comment]
请问你解决这个问题了吗

**Comment by ZhouO-v-O** [comment]
顶一下，同样遇到这个问题了

**Comment by sparsepenn** [comment]
同问，不知道是key-api的问题，还是代理的问题。日常代理是可以用的

**Comment by HiddenStar1** [comment]
有人解决了嘛

**Comment by Palai-s** [comment]
if API_KEY == "sk-Qs0onCC6CGeh5c0gZ4*" 这里的API_KEY 不能和上面的一样吧 检查用的

**Comment by njausxl** [comment]
> if API_KEY == "sk-Qs0onCC6CGeh5c0gZ4*" 这里的API_KEY 不能和上面的一样吧 检查用的

我只能说你是一个人才，解决了

**Comment by Sheerand** [comment]
> > if API_KEY == "sk-Qs0onCC6CGeh5c0gZ4*" 这里的API_KEY 不能和上面的一样吧 检查用的
> 
> 我只能说你是一个人才，解决了
是这个问题

**Comment by blu3sh0rk** [comment]
> 

我也 我check_proxy返回值跟main上打印的返回值还不一样，明明是直接调用。。。

**Comment by sheliangwang** [comment]
> 

两处填写API key，不一样该如何填写呢

**Comment by Sheerand** [comment]
解决了Clash填proxies = {"http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }就行

**Comment by Sheerand** [comment]
> > 
> 
> 两处填写API key，不一样该如何填写呢

上面填写申请的API key,下面那个不要动，那个if语句是用来判断你有没有改过最上面的API key的，如果相同，说明你上面没改，所以第二个不要改

**Comment by Sheerand** [comment]
> 

解决了Clash填proxies = {"http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }就行

**Comment by onetance** [comment]
![image](https://user-images.githubusercontent.com/61740950/228407378-d0c64f66-3047-4539-abed-9d3a4fcd106e.png)
朋友，可以帮忙看看我的代理这里应该怎么填吗，尝试了很多次都报错，实在不知道怎么弄了
![image](https://user-images.githubusercontent.com/61740950/228407807-bf28fd3b-eedf-4e94-a79c-662a78bd2dd6.png)
![image](https://user-images.githubusercontent.com/61740950/228407935-c6424ef3-0dcf-4f05-9591-d826059547e6.png)

**Comment by wei-seven** [comment]
> > 
> 
> 解决了Clash填proxies = {"http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }就行

我用的也是这个方法 可以正常运行

**Comment by onetance** [comment]
> > 
> 
> 解决了Clash填proxies = {"http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }就行

我按照这个也成功了，谢谢

**Comment by sheliangwang** [comment]
嗯，好的谢谢。还有一个问题是我安装python 依赖的时候总是报语法错误，试过很多次了。

**Comment by bqgao** [comment]
> > > 
> > 
> > 
> > 解决了Clash填proxies = {"http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }就行
> 
> 我按照这个也成功了，谢谢

你好呀，我的也是这个vpn，按照这样写还是代理无效，端口应该也是33210吧

**Comment by Sheerand** [comment]
> > > > 
> > > 
> > > 
> > > 解决了Clash填proxies = {"http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }就行
> > 
> > 
> > 我按照这个也成功了，谢谢
> 
> 你好呀，我的也是这个vpn，按照这样写还是代理无效，端口应该也是33210吧

USE_PROXY = False 改为True，很多人都忘了这一步，你看看有没有改

**Comment by FYZ-1539874** [comment]
[local] Request timeout, network error. please check proxy settings in config.py.

最后进去显示这样，这要怎么办
