### ISSUE TITLE
增加逆序显示聊天对话的选项或是改进聊天对话显示逻辑。

### ISSUE THREAD

**Issue by moxi000** [binary-husky/chatgpt_academic#342]
目前的对话机制，对于长对话或是需要频繁交互的访问，不是很友好。需要滚动到最下面才能看到内容，能否设计为逆序显示对话。或是让当前最新的对话显示在页面上。

**Comment by GitYohoo** [comment]
赞成  上面输入下面输出太反习惯了

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/230361774-53e4dff2-67e0-48b6-b487-539bbc4eab60.png)
![image](https://user-images.githubusercontent.com/96192199/230361793-cd479cdf-9afb-4a30-b077-b6cdcc7176cd.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/230361834-533e5c9c-c9cb-4cbf-872c-5b1ac2246f67.png)
![image](https://user-images.githubusercontent.com/96192199/230361857-05a2c5f0-599f-43cb-a1ca-7614a51c1579.png)
![image](https://user-images.githubusercontent.com/96192199/230361889-717eab86-cab9-453f-ba45-6c7003b19171.png)

**Comment by moxi000** [comment]
非常感谢，我这就进行同步和测试。
