### ISSUE TITLE
docker(Linux)部署,批量总结PDF文档应该如何实现？

### ISSUE THREAD

**Issue by Sloanleee** [binary-husky/chatgpt_academic#346]
提示是这个
导入软件依赖失败。使用该模块需要额外依赖，安装方法pip install --upgrade pymupdf
但我安装此依赖后，build/run还是不行啊，求教

**Comment by binary-husky** [comment]
docker run 之后，用docker exec -it <container_hash> bash进入容器，然后再pip3 install

**Comment by Sloanleee** [comment]
> docker run 之后，用docker exec -it <container_hash> bash进入容器，然后再pip3 install

感谢，成功解决
