### ISSUE TITLE
各位大佬，我部署在国外的服务器上，怎么样可以用固定的ip+端口的方式长期访问？

### ISSUE THREAD

**Issue by xiaosaaaa** [binary-husky/chatgpt_academic#348]
前言：我部署了账号和密码，本身是国外的服务器没开启config.py内的代理。

1. 现在运行main.py会随机端口，使用服务器的公网ip+给出的随机端口，可以进入但是使用时会显示连接错误，看了之前的issue好像是bug？截图如下：
![image](https://user-images.githubusercontent.com/115446601/230398091-af5d2b05-4123-4e3c-88d9-12060d38a365.png)

2. https://xxxxxxxx.gradio.live
用这个地址是可以正常使用的，但是好像只有三天的使用时间。
我想部署在服务器上直接使用  ip+固定的端口，长期使用，如何配置，谢谢各位。

**Comment by Linaom1214** [comment]
> 

修改配置文件就可以固定端口吧， 我在腾讯云上部署的一直可以用 


![image](https://user-images.githubusercontent.com/60921095/230402423-b1a3ebfd-f7ef-4f0f-a86d-e2851f74714c.png)

**Comment by xiaosaaaa** [comment]
请教以下怎么修改，加账号密码了吗？

**Comment by wlp233** [comment]
在config.py里改web
`# 网页的端口, -1代表随机端口
WEB_PORT = `
同时记得在服务器防火墙那边设置好入站规则
![image](https://user-images.githubusercontent.com/73226302/230413465-9aa79186-0dfa-4a4a-9880-781696f277da.png)

**Comment by xiaosaaaa** [comment]
好的，谢谢

**Comment by RuSignalFlag** [comment]
@xiaosaaaa 你是用ip 加端口访问报错那个问题解决了吗

**Comment by xiaosaaaa** [comment]
应该是bug，设置了密码后用http访问会出现问题，好像是用https可以，没验证过。

**Comment by xjtydl** [comment]
我这也是部署出现错误提示，， 那只能不要帐号密码了？

**Comment by RuSignalFlag** [comment]
@xjtydl 有域名的话可以用nginx+ssl 用https访问就没有问题

**Comment by xiaosaaaa** [comment]
好像还得开启websocket
