### ISSUE TITLE
latex 代码符号会被吞掉

### ISSUE THREAD

**Issue by iamcxds** [binary-husky/chatgpt_academic#350]
**Describe the bug 简述**

一些latex元素显示的时候会被处理掉, 例如 `from $\mathbf{c}_{jK}$ to $\mathbf{c}_{jI}$ ` 里面的`_`会被吞掉. 产生的原因是显示的时候被识别成markdown的元素了, 比如说把两个`_`处理成了斜体.

这样导致直接复制粘贴的时候挺麻烦.

**Screen Shot 截图**

![282KV3W3ZWPHPY40H5}3 Q](https://user-images.githubusercontent.com/10074835/230418315-33265e7b-8267-46fe-9024-113d5a09d9ca.png)

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
Fixed and add equation highlight, please checkout

![image](https://user-images.githubusercontent.com/96192199/230591577-219a05c6-87a3-449c-8818-8d35d46eea7a.png)
