### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by RuSignalFlag** [binary-husky/chatgpt_academic#352]
**Describe the bug 简述**

使用docker部署，会报连接错误

**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/78648337/230433295-e4a9400b-31c3-4e88-b363-5c0f82a2ea6d.png)

**Terminal Traceback 终端traceback（如果有）**
无

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by RuSignalFlag** [comment]
很奇怪的是，用nginx反向代理，使用域名访问就没有这个问题，我的docker命令是 docker run -d -p 端口:端口 镜像名称

**Comment by binary-husky** [comment]
看下wiki

**Comment by RuSignalFlag** [comment]
@binary-husky 谢谢，找到了，是因为我添加了账号密码的原因，这个bug好奇怪，我用nginx反向代理下用域名访问就没有问题了
