### ISSUE TITLE
昨天api挂上gptac，我账号被封了，这咋办？

### ISSUE THREAD

**Issue by RebelYoung** [binary-husky/chatgpt_academic#355]
**Describe the bug 简述**
昨天api挂上gptac，我账号被封了，这咋办？

**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/59256512/230523564-948a86b5-dce6-4c7d-bce2-ddf5e463eecb.png)

昨天晚上开始的，但是有一瞬间我全局模式下还登录上了，这是封的ip还是封的账号呢？
目前gptac还可以用。。。

**Comment by RuSignalFlag** [comment]
别紧张，这是封的IP，账号还能用API就没问题，换个IP登录就好了

**Comment by RebelYoung** [comment]
> 

就是换个节点吗？我试了另一个美国的，但是头上173.82.xxx是一样的，还是打不开chat，是不是得换个国家？

**Comment by RuSignalFlag** [comment]
@RebelYoung 多换几个试试，一般新加坡的比较稳定

**Comment by RebelYoung** [comment]
> @RebelYoung 多换几个试试，一般新加坡的比较稳定

试了一下，真是可以
