### ISSUE TITLE
函数插件-理解PDF内容-出现error，一直在重新发送，

### ISSUE THREAD

**Issue by gysabc** [binary-husky/chatgpt_academic#370]
**理解pdf内容时一直在重新发送，本地消息中显示等待gpt回复，进度从1到25，总共150，但是只到25就又从1开始计数了**

**Screen Shot 截图**
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/68911920/230698292-5baef118-a2f9-46ed-9038-cea0e472ddf1.png">

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by gysabc** [comment]
现在发现是连不上openai了，原先是可以的，现在断掉了
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/68911920/230698587-5f1728ec-7a31-4bd4-9282-69e52073d9f7.png">

**Comment by binary-husky** [comment]
代理网络可能不太稳定

**Comment by gysabc** [comment]
我换了Windows试了试，今天晚上用了用，断过一次。诶，太难受了，时好时坏，代理也比较慢。是不是在海外服务器部署，然后用代理访问海外服务器比较稳妥🤣


 ***@***.***
 ***@***.***
  



---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2023年04月08日 22:40 收件人  ***@***.***> 抄送至  Gao ***@***.***>***@***.***> 主题  Re: [binary-husky/chatgpt_academic] 函数插件-理解PDF内容-出现error，一直在重新发送， (Issue #370)  

代理网络可能不太稳定

**Comment by binary-husky** [comment]
尝试更新代码
