### ISSUE TITLE
本机测试没问题，部署后可以查询代理地址但是连接报错

### ISSUE THREAD

**Issue by wzqvip** [binary-husky/chatgpt_academic#371]
**Describe the bug 简述**
从本机运行后开127.0.0.1：xx是正常的，但是部署在服务器上后（代理 已设置）无论是直接跑还是docker都不行。Something went wrong。Connection errored out.

是立即报错，不是等待一会超时报错。代理配置了其他的也是不行。

**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/30136639/230702062-66b7c7f3-44d8-4300-a5c6-6395c1745b2a.png)

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by wwrtpfa** [comment]
![image](https://user-images.githubusercontent.com/46293921/230769613-cde8c43b-44ee-4a61-9921-3077b302ba26.png)
docker服务器部署加一，求解决

**Comment by zjw0358** [comment]
> 我刚开始好的，后来一堆升级后也出现相同问题，看 http 数据流是服务器返回 403，websocket 连接被拒绝了，nginx 配置都是正常的，目前还未解决

应该是我设置了访问密码后造成的，

解决办法: gradio-app/gradio#3716 (comment)

**Comment by zjw0358** [comment]
Temporarily change the routes.py file to access-token-unsecure made it work if '0.0.0.0' is set to expose.

before
token = websocket.cookies.get("access-token")
after
token = websocket.cookies.get("access-token-unsecure")
