### ISSUE TITLE
每次关闭后再打开会报错， No module named 'gradio'

### ISSUE THREAD

**Issue by xdw926** [binary-husky/chatgpt_academic#373]
每次用完关闭后，再打开会报错缺失 No module named 'gradio'
用完后我先关闭浏览器，再Ctrl c 命令行
[](url)
![(3(10C@{ 2PI)90HZI)4U~F](https://user-images.githubusercontent.com/110446687/230706453-f359ba66-16cb-4ff3-af23-823bdd70b5d7.png)
![OR8M(5K~@PK)I`3K}0E~ S6](https://user-images.githubusercontent.com/110446687/230706456-da706a18-01df-421f-9bdc-2d25873e154b.png)
然后我只能重新安装环境才行

**Comment by xdw926** [comment]
大佬们救救

**Comment by xdw926** [comment]
解决了，我忘记切换环境了
conda activate gptac_venv
就好了

**Comment by binary-husky** [comment]
是这样的
