### ISSUE TITLE
关于public url

### ISSUE THREAD

**Issue by Nicoals-James** [binary-husky/chatgpt_academic#376]
![Screenshot 2023-04-08 170556](https://user-images.githubusercontent.com/78332286/230713429-e0cc9a3f-1da9-4e76-b24a-67c35624a866.png)

这个public url 是经过博主自己搭建的服务器的吗？我本地搭建之后在手机打开这个url也能用

**Comment by binary-husky** [comment]
gradio的服务器，可以在main.py的最后一行share=False，来把public url关闭
