### ISSUE TITLE
localhost 拒绝了我们的连接请求。

### ISSUE THREAD

**Issue by More500code** [binary-husky/chatgpt_academic#391]
**Describe the bug 简述**
通过VSCODE部署完成之后，通过chrome打开就显示拒绝。
**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/80738561/230760478-d42da748-4967-4c37-b732-d34f2b92c1dc.png)
![image](https://user-images.githubusercontent.com/80738561/230760603-accc5d00-c50b-4849-b8e6-9176ada00919.png)

**Terminal Traceback 终端traceback（如果有）**
[PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问。建议：检查USE_PROXY选项是否修改。
[API_KEY] 您的 API_KEY 是: sk-nvN3BCfMbxRr*** API_KEY 导入成功
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'ip': '165.154.243.24', 'network': '165.154.243.0/24', 'version': 'IPv4', 'city': 'Taipei', 'region': 'Taipei City', 'region_code': 'TPE', 'country': 'TW', 'country_name': 'Taiwan', 'country_code': 'TW', 'country_code_iso3': 'TWN', 'country_capital': 'Taipei', 'country_tld': '.tw', 'continent_code': 'AS', 'in_eu': False, 'postal': '', 'latitude': 25.0504, 'longitude': 121.5324, 'timezone': 'Asia/Taipei', 'utc_offset': '+0800', 'country_calling_code': '+886', 'currency': 'TWD', 'currency_name': 'Dollar', 'languages': 'zh-TW,zh,nan,hak', 'country_area': 35980.0, 'country_population': 23451837, 'asn': 'AS142002', 'org': 'Scloud Pte Ltd'}
代理配置 无, 代理所在地：Taiwan
如果浏览器没有自动打开，请复制并转到以下URL：
        （亮色主体）: http://localhost:5600
        （暗色主体）: http://localhost:5600/?__dark-theme=true

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by Masterlovsky** [comment]
先看看有没有端口冲突，5600端口有没有其他服务。然后检查一下防火墙设置，关了防火墙再访问http://localhost:5600试试，如果不行的话看一下你是不是有自签的证书，我就是之前自签过然后会自动跳转到https。

**Comment by More500code** [comment]
> 先看看有没有端口冲突，5600端口有没有其他服务。然后检查一下防火墙设置，关了防火墙再访问[http://localhost:5600试试，如果不行的话看一下你是不是有自签的证书，我就是之前自签过然后会自动跳转到https。](http://localhost:5600%E8%AF%95%E8%AF%95%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%B8%8D%E8%A1%8C%E7%9A%84%E8%AF%9D%E7%9C%8B%E4%B8%80%E4%B8%8B%E4%BD%A0%E6%98%AF%E4%B8%8D%E6%98%AF%E6%9C%89%E8%87%AA%E7%AD%BE%E7%9A%84%E8%AF%81%E4%B9%A6%EF%BC%8C%E6%88%91%E5%B0%B1%E6%98%AF%E4%B9%8B%E5%89%8D%E8%87%AA%E7%AD%BE%E8%BF%87%E7%84%B6%E5%90%8E%E4%BC%9A%E8%87%AA%E5%8A%A8%E8%B7%B3%E8%BD%AC%E5%88%B0https%E3%80%82)

删除了自签证书后还是不行

**Comment by Masterlovsky** [comment]
> 
试试下面的方法
1. 地址栏中输入edge://net-internals/#hsts，如果是chrome就是chrome://net-internals/#hsts
2. 在Delete domain中输入项目的域名,比如你这个就是127.0.0.1，并Delete（删除）
3. 可以在Query domain测试是否删除成功。

**Comment by binary-husky** [comment]
尝试关闭全局代理/绕过局域网或大陆（配置完成后，只要保持上网软件后台运行即可，不需要全局代理）

**Comment by luqijun** [comment]
在wsl中的docker中部署时，我也遇到了相同的问题：

**Terminal**：
 [PROXY] 网络代理状态：已配置。配置信息如下： {'http': '172.18.160.1:10809', 'https': '172.18.160.1:10809'}
 [API_KEY] 您的 API_KEY 是: sk-WLJfdWF2jcVW*** API_KEY 导入成功
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'ip': '174.136.201.10', 'network': '174.136.201.0/24', 'version': 'IPv4', 'city': 'Miami', 'region': 'Florida', 'region_code': 'FL', 'country': 'US', 'country_name': 'United States', 'country_code': 'US', 'country_code_iso3': 'USA', 'country_capital': 'Washington', 'country_tld': '.us', 'continent_code': 'NA', 'in_eu': False, 'postal': '33197', 'latitude': 25.7689, 'longitude': -80.1946, 'timezone': 'America/New_York', 'utc_offset': '-0400', 'country_calling_code': '+1', 'currency': 'USD', 'currency_name': 'Dollar', 'languages': 'en-US,es-US,haw,fr', 'country_area': 9629091.0, 'country_population': 327167434, 'asn': 'AS23470', 'org': 'RELIABLESITE'}
代理配置 172.18.160.1:10809, 代理所在地：United States
如果浏览器没有自动打开，请复制并转到以下URL：
        （亮色主题）: http://localhost:38605
        （暗色主题）: http://localhost:38605/?__dark-theme=true
Running on local URL:  http://0.0.0.0:38605

To create a public link, set `share=True` in `launch()`.
自动更新程序：已禁用

Chrome浏览器，输入地址：http://localhost:38605/?__dark-theme=true
**报错如下**：
无法访问此网站localhost 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
[检查代理服务器和防火墙](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

**Comment by ShiDing007** [comment]
> **Describe the bug 简述** 通过VSCODE部分完成之后，通过chrome打开就显示拒绝。 **Screen Shot 截图** ![图像](https://user-images.githubusercontent.com/80738561/230760478-d42da748-4967-4c37-b732-d34f2b92c1dc.png) ![图像](https://user-images.githubusercontent.com/80738561/230760603-accc5d00-c50b-4849-b8e6-9176ada00919.png)
> 
> **终端追溯终端（** proxy] [proxy]：未未：未配置。无代理代理状态下下很可能可能可能无法无法访问无法：检查use_proxy use_proxy选项[api_key] [api_key ]引导成功 所有询问记录将自动保存在本地目录./gpt_log/chat_secrets.log，请注意我隐私保护哦！ 查询代理的位置，返回的结果是{'ip': '165.154.243.24', 'network': '165.154.243.0/24', 'version': 'IPv4', 'city': 'Taipei', ' region': '台北市', 'region_code': 'TPE', 'country': 'TW', 'country_name': '台湾', 'country_code': 'TW', 'country_code_iso3': 'TWN', 'country_capital ': '台北', 'country_tld': '.tw', 'continent_code': 'AS', 'in_eu': False, 'postal': '', 'latitude': 25.0504, 'longitude': 121.5324, 'timezone ': '亚洲/台北', 'utc_offset': '+0800', 'country_calling_code': '+886', 'currency': 'TWD', 'currency_name': '美元', 'languages': 'zh-TW,zh,nan,hak', 'country_area': 35980.0, 'country_population': 23451837, 'asn': 'AS142002', 'org': 'Scloud Pte Ltd'} 代理配置无, 代理所在地：台湾 若浏览器没有自动打开，请复制并转至以下网址： （亮色主体）: http://localhost:5600 （暗色主体）:http://localhost:5600/?__dark-theme=true
> 
> 在提交问题之前提交问题之前：
> 
> * 请尝试升级您的代码。如果您的代码不是最新的，建议您先尝试更新代码
> * 请查看项目 wiki 以获取常见问题解决方案。项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

请问你这个问题解决了吗？ 我也遇到了同样的问题。

**Comment by amosocean** [comment]
可以尝试edge的Inprivate模式
