### ISSUE TITLE
上传PDF，显示接受完成问我要问什么问题，问了就开始胡说，和PDF毫不相关

### ISSUE THREAD

**Issue by LighteningSkype** [binary-husky/chatgpt_academic#392]
**Describe the bug 简述**

**Screen Shot 截图**

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by BabelTower** [comment]
一样的问题，用了 插件“理解PDF文档内容（通用接口，读取文件输入区）”，上传了一篇论文pdf，连标题都回答不对。
<img width="970" alt="image" src="https://user-images.githubusercontent.com/44083490/230773329-c0344349-9ffd-4b6f-a802-2259c30339e4.png">

**Comment by binary-husky** [comment]
我写的插件随意吐槽没关系

但这个插件是热心的开发者贡献的，不满意就自己调整，愿意分享就pr分享出来。
请不要在这抱怨，这毫无建设性，还会影响大家的开发热情

**Comment by binary-husky** [comment]
项目插件是属于所有人的，任何人的任何插件只要合理就可以merge到主线，然后欢迎任何改进pr和意见，但意见反馈要注意方式，不要打击大家的热情。
