### ISSUE TITLE
代理设置无效

### ISSUE THREAD

**Issue by PythonCancer** [binary-husky/chatgpt_academic#393]
你好，我自己开启代理后，直接访问chagpt是可以的，可以进行对话，但是在你们这个项目中，在config.py中开启代理后，设置代理，一直都报错，能帮我看看嘛？截图如下：
![841f45301e4764371f292d6a5e60140](https://user-images.githubusercontent.com/40718793/230774040-f14dd708-24b8-48f3-b1a1-a2c2ae2dfae7.png)

![2ee269994200b6a15651e2b255cd3d7](https://user-images.githubusercontent.com/40718793/230774036-f4256be6-d08d-496d-a205-9704e4254689.png)

**Comment by binary-husky** [comment]
信息不足 #1
