### ISSUE TITLE
[local] Request timeout, network error. please check proxy settings in config.py.

### ISSUE THREAD

**Issue by doyle1996** [binary-husky/chatgpt_academic#40]
首先第一个问题： 代理所在地查询超时，代理可能无效 这是因为梯子问题吗。
可是我在https://ipapi.co/json/查询，country是新加坡（我用的新加坡的梯子）

然后在正常运行画面导入zip文件，向他提问就是timeout了，不知道哪里出了问题,,

**Comment by binary-husky** [comment]
#1

**Comment by binary-husky** [comment]
duplication of #1

**Comment by lishuai6119** [comment]
求助求助，我也遇到了这个问题！！

**Comment by lishuai6119** [comment]
求助求助，我也遇到了这个问题！！

**Comment by yagao-dream** [comment]
同问

**Comment by lishuai6119** [comment]
不会呀

--------------原始邮件--------------
发件人："高亚 ***@***.***&gt;;
发送时间：2023年3月30日(星期四) 晚上9:24
收件人："binary-husky/chatgpt_academic" ***@***.***&gt;;
抄送："李加主 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [binary-husky/chatgpt_academic] [local] Request timeout, network error. please check proxy settings in config.py. (Issue #40)
-----------------------------------

 

 
同问

**Comment by Royal18625194910** [comment]
怎么办，特地买的t字

**Comment by Royal18625194910** [comment]
用美国和印度的也没用

**Comment by lishuai6119** [comment]
加个微信

--------------原始邮件--------------
发件人："lin92n ***@***.***&gt;;
发送时间：2023年4月2日(星期天) 下午4:43
收件人："binary-husky/chatgpt_academic" ***@***.***&gt;;
抄送："李加主 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [binary-husky/chatgpt_academic] [local] Request timeout, network error. please check proxy settings in config.py. (Issue #40)
-----------------------------------

 

 
怎么办，特地买的t字

**Comment by Royal18625194910** [comment]
加，你能解决吗

**Comment by Royal18625194910** [comment]
> 加，你能解决吗
