### ISSUE TITLE
WebSocket connection to 'ws://xxx.xxxx.xxxx:2002/queue/join' failed

### ISSUE THREAD

**Issue by md5xwl** [binary-husky/chatgpt_academic#401]
2.5版本，部署在海外服务器。ubuntu20.04, python3.8
用账号/密码登陆后可以正常显示界面，输入区输入内容后点提交，弹小窗
Something went wrong
Connection errored out.
按F12看了下log,
WebSocket connection to 'ws://xxx.xxxx.xxxx:2002/queue/join' failed

**Comment by binary-husky** [comment]
看下wiki，可能反代的问题
