### ISSUE TITLE
demo测试说我openai拒绝请求，直接搜索说我账户额度不够，但我直接用chatgpt没有问题，请问大家碰到过这个情况吗？

### ISSUE THREAD

**Issue by xiongtun666** [binary-husky/chatgpt_academic#406]
**Describe the bug 简述**

**Screen Shot 截图**

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
https://platform.openai.com/account/usage

**Comment by 15058415003** [comment]
直接去官网用ChatGPT是免费的，但是调用API是要付费的。但凡是官网之外的ChatGPT，都是调用API。如果你的API免费额度用完了或者过期了，那就需要自己找个美国的信用卡或者虚拟信用卡，绑定到你的OpenAI账户上。保证卡里有余额，才能继续使用API。具体方法，你可以问其他人或者自己搜索
