### ISSUE TITLE
已经升级pymupdf和tiktoken包，但仍然无法使用pdf翻译功能

### ISSUE THREAD

**Issue by Misaka89535** [binary-husky/chatgpt_academic#409]
![图片](https://user-images.githubusercontent.com/90268558/230956044-98a73ef0-590e-4830-96d4-a97473c4a1c9.png)
![图片](https://user-images.githubusercontent.com/90268558/230956203-dbb94251-9e20-49c2-a382-b2ccc5c5fe17.png)

**Comment by binary-husky** [comment]
存在多个python，安装到别的python上了
