### ISSUE TITLE
为什么，每次进去都只能问一次问题，第二次提交过了很久都不回答？刷新后问的问题就都没了，还是只能问一次问题。

### ISSUE THREAD

**Issue by 2531088345** [binary-husky/chatgpt_academic#410]
**Describe the bug 简述**

**Screen Shot 截图**

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
信息不足
