### ISSUE TITLE
[PDF论文全文翻译功能] 似乎效果并不太好

### ISSUE THREAD

**Issue by Lufffya** [binary-husky/chatgpt_academic#411]
有些重复翻译的，最大的问题是并不会全文翻译，只是翻译了一部分，而且公式全部漏掉了

**Comment by binary-husky** [comment]
- 翻译一部分的问题已经解决（2.6版本）
- 公式没办法，pdf版本的公式不能识别，如果是arxiv论文，强烈建议用latex源文件
