### ISSUE TITLE
【开发者】2.60版本出现代码重构错误，现已在2.67版本中修复大部分功能，提醒大家及时更新代码

### ISSUE THREAD

**Issue by binary-husky** [binary-husky/chatgpt_academic#416]
**Describe the bug 简述**

**Screen Shot 截图**

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by tomkuo1124** [comment]
hi sir,
如果您方便的話想請問您一下要怎麼更新程式碼？（我剛剛找了wiki沒有相關資料）
我目前只會把chatgpt_academic整個資料夾移除後在重新安裝, 
請問這樣做可以嗎？
謝謝您

**Comment by binary-husky** [comment]
> hi sir, 如果您方便的話想請問您一下要怎麼更新程式碼？（我剛剛找了wiki沒有相關資料） 我目前只會把chatgpt_academic整個資料夾移除後在重新安裝, 請問這樣做可以嗎？ 謝謝您

是的，完全沒有問題。 直接覆蓋原來的程式碼也是OK的。 

建議新建一個config_ private.py保留您的私密配寘，如此的話就不會在覆蓋的過程中遺失配寘。如果config_ private.py存在，程式會以高優先順序讀取它

**Comment by tomkuo1124** [comment]
Hi Sir,
太感謝您的回覆與分享了, 謝謝您 ^^
