### ISSUE TITLE
安装chatgpt_academic第二天无法连接校园网wifi了

### ISSUE THREAD

**Issue by mundoctor** [binary-husky/chatgpt_academic#417]
**Describe the bug 简述**
如题，在windows10系统下，git clone安装chatgpt_academic，然后python安装好requirements，配置好config.py的api和proxy，并另存为config_private.py，然后使用python main.py正常运行。
但是第二天打开电脑时发现，连不上校园网的wifi了，我和同学两人都遇到了这一状况。但是联通宽带接出来的wifi和手机热点wifi都可以正常连接和上网。
附：在第一次运行main.py时，遇到了360报毒frpc_windows_amd64_v0.2，添加信任，之后也没有什么异常
考虑是proxy的问题？但我自己搞一下午也没搞定
**Screen Shot 截图**
![1681215687979](https://user-images.githubusercontent.com/114044599/231160735-f344db19-e97b-4f05-a031-a54bd318b308.jpg)

**Terminal Traceback 终端traceback（如果有）**

**Comment by mundoctor** [comment]
重置无线适配器，重启电脑，都无效。疑难解答给出的提示是：重新插拔路由器，但学校无线网哪有这个。。。

**Comment by mundoctor** [comment]
是遇到了frp报毒，报毒之后我立刻添加了信任
但这不是重点...
重点是连不上校园网了...

**Comment by mundoctor** [comment]
> frp报毒看wiki

是遇到了frp报毒，报毒之后我立刻添加了信任
但这不是重点...
重点是连不上校园网了...

**Comment by suqnee** [comment]
> > 你好，请问你解决这个问题了吗
> 
> 谢谢，已经解决了

方便告知一下怎么解决的吗

**Comment by mundoctor** [comment]
> > > 你好，请问你解决这个问题了吗
> > 
> > 
> > 谢谢，已经解决了
> 
> 方便告知一下怎么解决的吗

是ip被学校封了，让学校解封，你也是cugber？
