### ISSUE TITLE
如何快速更新？

### ISSUE THREAD

**Issue by XiaoboAlexander** [binary-husky/chatgpt_academic#422]
请问这个每次更新都需要重新部署一下么？没有快速更新的方式么？

**Comment by binary-husky** [comment]
2.5版本之后就已经支持一键更新了，但我们这个一键更新比较简陋，有任何问题及时反馈吧!

**Comment by binary-husky** [comment]
如果右上角有版本号，说明是能一键更新的版本
![image](https://user-images.githubusercontent.com/96192199/231257207-cec07bcd-f3e2-4055-ac87-186c6350638a.png)

然后如果github上检测到了新版本，可以在这个界面输入Y，然后敲回车即可一键更新。不想要更新时无视这个提醒即可
![image](https://user-images.githubusercontent.com/96192199/231257133-6eeeb05d-3046-444e-b649-905506541789.png)

**Comment by XiaoboAlexander** [comment]
感谢回复，意思就是需要自动检测对吧，没有办法主动发起么？主动检测到了就可以自动更新？

**Comment by binary-husky** [comment]
> 感谢回复，意思就是需要自动检测对吧，没有办法主动发起么？主动检测到了就可以自动更新？

大体上是这样子滴

**Comment by binary-husky** [comment]
> docker有办法自动更新吗

docker还是手动吧，完全自动的更新不是不行，但我不敢把自动更新搞的太暴力了，目前是启动时触发+用户键盘确认
