### ISSUE TITLE
调用出现api key余额不足的情况

### ISSUE THREAD

**Issue by VegeBun-csj** [binary-husky/chatgpt_academic#424]
**Describe the bug 简述**
调用出现api key余额不足的情况，但是我的账号是plus，不可能呀
**Screen Shot 截图**
<img width="1562" alt="image" src="https://user-images.githubusercontent.com/39252213/231335000-98fa789f-f08f-4052-9fd8-8365f0feb615.png">

**Terminal Traceback 终端traceback（如果有）**
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/39252213/231335032-2d2db213-ed78-4e7d-8345-d0b30d0ccce7.png">

**Comment by binary-husky** [comment]
https://platform.openai.com/account/usage

**Comment by yzgrfsy** [comment]
@VegeBun-csj  plus和api 分开单独扣费的
