### ISSUE TITLE
可以支持任意项目的源码分析吗

### ISSUE THREAD

**Issue by VegeBun-csj** [binary-husky/chatgpt_academic#425]
好像现在只支持py项目？
<img width="621" alt="image" src="https://user-images.githubusercontent.com/39252213/231335631-e3f656b0-31a6-4e06-b631-803dc8e0b09a.png">

**Comment by binary-husky** [comment]
下拉菜单

**Comment by August9708** [comment]
file_manifest = [f for f in glob.glob(f'{project_folder}/**/*.m', recursive=True)]
我将这行代码里的.py改成了.m，希望解析matlab项目

上传zip文件后，提示上传成功
![image](https://user-images.githubusercontent.com/78811371/231363947-94cbd905-76ee-41d1-8709-2ee3f0a99b1f.png)

但点击相应的解析按钮无法解析，提示：
![image](https://user-images.githubusercontent.com/78811371/231364085-dfdd7e18-dc81-4526-93cb-59fa56841320.png)

附件是我上传的zip文件
[matlabcode.zip](https://github.com/binary-husky/chatgpt_academic/files/11207650/matlabcode.zip)

该怎么改才能正常使用？
