### ISSUE TITLE
尝试解析matlab项目遇到的问题

### ISSUE THREAD

**Issue by August9708** [binary-husky/chatgpt_academic#428]
我尝试了下，但遇到了问题，不知道怎么解决..
修改   解析项目源代码.py    文件里
@CatchException
def 解析一个Python项目...

file_manifest = [f for f in glob.glob(f'{project_folder}/**/*.m', recursive=True)]
我将这行代码里的.py改成了.m，希望能解析matlab项目

上传zip文件后，提示上传成功
![image](https://user-images.githubusercontent.com/78811371/231363947-94cbd905-76ee-41d1-8709-2ee3f0a99b1f.png)

但点击相应的解析按钮(解析整个python项目)，却无法解析，提示：
![image](https://user-images.githubusercontent.com/78811371/231364085-dfdd7e18-dc81-4526-93cb-59fa56841320.png)

附件是我上传的zip文件
[matlabcode.zip](https://github.com/binary-husky/chatgpt_academic/files/11207650/matlabcode.zip)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/231386583-f4341c75-2563-4420-b402-f20311a791e1.png)
把这几个外国名字去掉即可

**Comment by binary-husky** [comment]
![Uploading image.png…]()

这个地方可以加一个 errors='replace'

**Comment by August9708** [comment]
图片没有传上来 在哪里加？

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/231390435-5e06e059-5062-4d89-b039-ca7e2f4bf19e.png)
