### ISSUE TITLE
请问现在支持使用本地chatglm模型作为底座了吗？

### ISSUE THREAD

**Issue by lwj44542** [binary-husky/chatgpt_academic#434]
请问现在支持使用本地chatglm模型作为底座了吗？有相关的教程吗~

**Comment by binary-husky** [comment]
v3.0分支测试中，目前效果不错，可以同时向chatgpt和chatglm提问。
目前我们提供测试用的dockerfile：
https://github.com/binary-husky/chatgpt_academic/blob/master/Dockerfile%2BChatGLM

**Comment by lwj44542** [comment]
> v3.0分支测试中，目前效果不错，可以同时向chatgpt和chatglm提问。 目前我们提供测试用的dockerfile： https://github.com/binary-husky/chatgpt_academic/blob/master/Dockerfile%2BChatGLM

那可以只是用chatglm吗？

**Comment by binary-husky** [comment]
> > v3.0分支测试中，目前效果不错，可以同时向chatgpt和chatglm提问。 目前我们提供测试用的dockerfile： https://github.com/binary-husky/chatgpt_academic/blob/master/Dockerfile%2BChatGLM
> 
> 那可以只是用chatglm吗？

也支持通过调用tgui，切换galactica-1.3b，opt-1.3b这些，但这些几b大小的模型能力太弱了，还不支持中文……

**Comment by binary-husky** [comment]
> > v3.0分支测试中，目前效果不错，可以同时向chatgpt和chatglm提问。 目前我们提供测试用的dockerfile： https://github.com/binary-husky/chatgpt_academic/blob/master/Dockerfile%2BChatGLM
> 
> 那可以只是用chatglm吗？

可以
