### ISSUE TITLE
使用chatgpt_academic-version2.67的功能函数PDF总结和PDF翻译时，报错'Could not automatically map gpt-3.5-turbo to a tokeniser. '

### ISSUE THREAD

**Issue by cheng9911** [binary-husky/chatgpt_academic#435]
**Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect. 简述**

**
![图片4](https://user-images.githubusercontent.com/101553251/231438936-c326299a-28da-469a-a3a0-e5b6e70b6861.png)
**

`Traceback` (most recent call last):
  File "D:\chatgpt使用\chatgpt_academic-version2.67\toolbox.py", line 185, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "D:\chatgpt使用\chatgpt_academic-version2.67\crazy_functions\批量翻译PDF文档_多线程.py", line 221, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, sys_prompt)
  File "D:\chatgpt使用\chatgpt_academic-version2.67\crazy_functions\批量翻译PDF文档_多线程.py", line 237, in 解析PDF
    enc = tiktoken.encoding_for_model(*get_conf('LLM_MODEL'))
  File "D:\python\lib\site-packages\tiktoken\model.py", line 51, in encoding_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-3.5-turbo to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you 

> expect.'’‘

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by Le-ying** [comment]
我在解析py项目中也遇到这个错误，将tiktoken更新到0.3.3版本解决

**Comment by binary-husky** [comment]
安装依赖时用的啥pip源，分享一下让大家拉黑了吧
