### ISSUE TITLE
使用第三方代理API时修改API_URL不起作用

### ISSUE THREAD

**Issue by zhanggao1793** [binary-husky/chatgpt_academic#440]
想使用API2D这样的第三方代理API，目前在修改API_URL和API_KEY为API2D的ForwardKEY后不起作用，依然会提示缺少api_key，不知道作者能否增加对第三方API的支持

**Comment by zhanggao1793** [comment]
问题解决了，第三方的key跟openai_key长度不一样，导致bridge_chatgpt.py文件里的inputs.startswith('sk-') and len(inputs) == 51处一直为FALSE，修改后问题解决

**Comment by xixia123** [comment]
我忽然感觉我可能也是遇着这个问题了。。。。
