### ISSUE TITLE
一直显示代理所在地：未知，IP查询频率受限，如图

### ISSUE THREAD

**Issue by xinzhaobuxuan** [binary-husky/chatgpt_academic#441]
**Describe the bug 简述**

[**Screen]([url](url)) Shot 截图**
![2023-04-12_23-09-20](https://user-images.githubusercontent.com/19953262/231501733-1b5a654d-de32-444f-8660-89f3db30ca9b.png)

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
#1
