### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by YangPeng61790312** [binary-husky/chatgpt_academic#444]
pip colorama后仍然显示 ModuleNotFoundError: No module named 'colorama'

**Comment by binary-husky** [comment]
更新pip依赖

**Comment by YangPeng61790312** [comment]
> 更新pip依赖
colorama安装成功，但还是显示ModuleNotFoundError: No module named 'colorama'

**Comment by YangPeng61790312** [comment]
>还是不行
