### ISSUE TITLE
网页报错文件找不到

### ISSUE THREAD

**Issue by xuehongnizhao** [binary-husky/chatgpt_academic#445]
报一个文件找不到一只开在loading页面

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/17492322/231633794-7420de78-4b6c-45dc-8521-4a56af0a6193.png">

**Comment by binary-husky** [comment]
信息不足，尝试

- 更新代码
- 切换代理模式

**Comment by xuehongnizhao** [comment]
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/17492322/231671293-c2fd8d13-8646-4b53-a8b2-e4a3cf778b84.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17492322/231671211-f2086c3e-42dc-435b-b9c2-057c424efa7b.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17492322/231671259-4351bb79-2f7f-4e27-ba0d-f650fd65be22.png">

我这个应该是对的啊  一直卡在loading页面
