### ISSUE TITLE
导入文件的时候无响应

### ISSUE THREAD

**Issue by star562** [binary-husky/chatgpt_academic#447]
**Describe the bug 简述**
导入文件无响应，zip格式，以及py文件。选择导入文件后，就没有反应了，且后续无法展开文件上传区了
**Screen Shot 截图**
![Uploading image.png…]()

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
- 请先尝试更新代码，目前最新是2.68版本
- 图片上传失败了，看不到
