### ISSUE TITLE
批量翻譯pdf文檔(多線程)功能出現問題: AttributeError: module 'tiktoken' has no attribute 'encoding_for_model'

### ISSUE THREAD

**Issue by tomkuo1124** [binary-husky/chatgpt_academic#448]
**Describe the bug 简述**
(已經更新到最新的ChatGPT_academic)當我上傳一個本地文件（Also_sprach_Zarathustra.pdf）後想使用紫色功能：批量翻譯pdf文檔(多線程)的時候會顯示出錯:
Traceback (most recent call last):
  File "/home/tom/chatgpt_academic/toolbox.py", line 185, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "/home/tom/chatgpt_academic/crazy_functions/批量翻译PDF文档_多线程.py", line 56, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, sys_prompt)
  File "/home/tom/chatgpt_academic/crazy_functions/批量翻译PDF文档_多线程.py", line 72, in 解析PDF
    enc = tiktoken.encoding_for_model(*get_conf('LLM_MODEL'))
AttributeError: module 'tiktoken' has no attribute 'encoding_for_model'

**Screen Shot 截图**
file:///home/tom/%E5%9C%96%E7%89%87/%E8%9E%A2%E5%B9%95%E5%BF%AB%E7%85%A7/%E8%9E%A2%E5%B9%95%E5%BF%AB%E7%85%A7%202023-04-13%2012-16-16.png

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
Try `pip install --upgrade tiktoken>=0.3.3`

**Comment by tomkuo1124** [comment]
非常謝謝您的解答, 我測試過之後功能正常了! 謝謝您 ^^

use below command to update:
pip3 install --upgrade tiktoken==0.3.3
