### ISSUE TITLE
生成的 MarkDown 分析报告打开时出现乱码

### ISSUE THREAD

**Issue by mambaHu** [binary-husky/chatgpt_academic#45]
Python 在写入文件的时候会默认使用 ANSI 编码，而大部分开发者不了解 ANSI 编码，且多数工具默认以 UTF-8 编码读取 MarkDown 文件，这会导致阅读分析报告时呈现乱码。我在代码中的写入部分规定了 UTF8 编码，申请提交 Pull Request

**Comment by binary-husky** [comment]
在我测试时没出现类似问题，但pr已经merge，多谢！
