### ISSUE TITLE
docker容器+反向代理通过域名访问，能够登录和输入信息，但是反馈报错，如图

### ISSUE THREAD

**Issue by Gao-yu-1214** [binary-husky/chatgpt_academic#453]
![d2f46d63c688a40aac8f7be8afbc05b](https://user-images.githubusercontent.com/64946812/231689360-0bc5a37b-c1c9-4f69-9769-6c834dc38653.png)

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/wiki/%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9C%E7%A8%8B%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97

**Comment by Gao-yu-1214** [comment]
按照链接的方法试过了，还是不行
报同样的错误，目前的状态是能打开并且登录页面，正常显示，但是在输入完成点击提交之后就会报错，如上图所示

**Comment by Gao-yu-1214** [comment]
> [https://github.com/binary-husky/chatgpt_academic/wiki/%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9C%E7%A8 %8B%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97](https://github.com/binary-husky/chatgpt_academic/wiki/%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9C%E7%A8%8B%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)

按照上述方法试过了，还是报错，现在的状态是可以正常访问并登录，页面打开正常，但是输入完点击提交之后，就会报错，如上图所示

**Comment by Gao-yu-1214** [comment]
> [https://github.com/binary-husky/chatgpt_academic/wiki/%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9C%E7%A8 %8B%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97](https://github.com/binary-husky/chatgpt_academic/wiki/%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9C%E7%A8%8B%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)

按照上面描述方法试过了，还是报错，现在的状态是可以正常访问并登录，页面打开正常，但输入完成点击提交上传后，就会报错，如上图所示
