### ISSUE TITLE
理解PDF文档内容那个功能是不是有点欺负老实人了？

### ISSUE THREAD

**Issue by fmyblack** [binary-husky/chatgpt_academic#456]
这功能先把一个长的pdf，分段和gpt交流，每次只要求gpt返回 接受完成，这里很好理解，毕竟论文往往内容太长，解决token嘛。

然后到了问答环节，debug发现message信息居然只有如下一段：
![image](https://user-images.githubusercontent.com/11541558/231698172-3f255d5c-d0b6-4903-a617-93d8551c35ea.png)
这玩意压根没有论文内容啊，这怎么能理解呢？
让它概述一下论文，还真回的有模有样，唬了我一下，还以为是什么高级的prmpt方式，直呼邪门。

但这玩意儿太不合理了，直到我把论文名称改为了【关于每日饮食的分析】再次上传，得到了如下答案：
![image](https://user-images.githubusercontent.com/11541558/231698757-79d10c4e-4153-4807-8d26-9f00d772489c.png)
好家伙真在聊饮食啊……

**Comment by binary-husky** [comment]
#430
