### ISSUE TITLE
自动更新程序：已禁用,这个怎么开启呢？

### ISSUE THREAD

**Issue by wzgrx** [binary-husky/chatgpt_academic#457]
win本地部署完成后，启动后就一直自动禁用，2.67到2.98更新也没有反应

**Comment by binary-husky** [comment]
这个请不必在意，自动更新程序和程序的主逻辑完全无关联

可能的情况很多：
- 访问github连接超时
- version文件无法读取
- 等等

或者可以打开https://github.com/binary-husky/chatgpt_academic/blob/master/check_proxy.py，
把134行的 print(.....) 强行改成 raise RuntimeError，让它把错误抛出来，就可以看到具体的失败原因了
