### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by steplead** [binary-husky/chatgpt_academic#459]
**Describe the bug 简述**
PS C:\Users\bruno2016> python -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/46212839/231770642-631a0a84-77d2-4e7d-b4ec-01be8d58d9e6.png)

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
cd chatgpt_academic

**Comment by StarCode000** [comment]
你的终端定位到了用户文件下面，不是chatgpt_academic这个文件夹下，当然找不到这个文件

**Comment by steplead** [comment]
![image](https://user-images.githubusercontent.com/46212839/231796358-9451060a-9977-4f9f-b107-c1584ffb07f4.png)

**Comment by steplead** [comment]
还是不行

**Comment by StarCode000** [comment]
python -m pip install --upgrade pip
先试试这个pip更新命令能不能用吧
