### ISSUE TITLE
ERROR: Invalid requirement: '__pycache__/' (from line 2 of requirements.txt)

### ISSUE THREAD

**Issue by steplead** [binary-husky/chatgpt_academic#462]
**Describe the bug 简述**
ERROR: Invalid requirement: '__pycache__/' (from line 2 of requirements.txt)
**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/46212839/231796758-e537f323-bb03-4fb1-97c8-3b80fddc8476.png)

![image](https://user-images.githubusercontent.com/46212839/231796688-14d0eb47-8ea7-4d73-9ccd-259b1b10f5df.png)

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by steplead** [comment]
![image](https://user-images.githubusercontent.com/46212839/231900968-279c5842-5b2f-4ea1-a2df-6cb108d7dd2a.png)

**Comment by steplead** [comment]
![image](https://user-images.githubusercontent.com/46212839/231901097-21c1f572-785e-4c58-ae43-24bf6cd37569.png)

**Comment by steplead** [comment]
谢谢老师，都已经满足了版本要求，也满足了安装条件，但还是出同样的错误，我的python装在D盘，是否有影响。

**Comment by binary-husky** [comment]
改requirements.txt了吗？不要改动它试试？

**Comment by steplead** [comment]
改了，我再重装安装试试。
