### ISSUE TITLE
找不到word和pdf文件

### ISSUE THREAD

**Issue by wangtianyipsy** [binary-husky/chatgpt_academic#464]
在使用插件“批量翻译pdf文档”和“批量总结work文档”的时候一直显示找不到文件。是我输入路径的方式有误吗？

**Screen Shot 截图**
<img width="1271" alt="Screenshot 2023-04-13 at 6 43 55 PM" src="https://user-images.githubusercontent.com/49813156/231898804-fe59cf24-0e2d-45ac-91fc-88f1fe52f6af.png">

终端也没有任何输出
<img width="1425" alt="Screenshot 2023-04-13 at 6 44 41 PM" src="https://user-images.githubusercontent.com/49813156/231898883-b9769455-45b8-4308-8f0b-1134b0d11a0e.png">

感谢回复

**Comment by 438749902** [comment]
应该是要在下面的上传区上传文件, 之后才能使用紫色(红色)的功能, 而不是输入文件的路径

**Comment by wangtianyipsy** [comment]
> 

感谢，现在能跑了

**Comment by 438749902** [comment]
你的2.68版本能上传pdf格式吗? 我的一上传pdf前端页面就卡死

**Comment by wangtianyipsy** [comment]
> 你的2.68版本能上传pdf格式吗? 我的一上传pdf前端页面就卡死

我刚试了一下大部分线程都成功了，不过有一个确实卡住了
<img width="798" alt="Screenshot 2023-04-13 at 10 28 58 PM" src="https://user-images.githubusercontent.com/49813156/231926360-5e2308f2-f33e-482b-91c6-fee91a07ab01.png">

**Comment by 438749902** [comment]
好的, 谢谢啦
