### ISSUE TITLE
解析整个C++项目中，程序流程图简述没有显示

### ISSUE THREAD

**Issue by liuruitju** [binary-husky/chatgpt_academic#465]
上传了一个C++项目让其解析，它在输出程序流程图简述部分，没有输出流程图，而是输出了一张奇怪的图片。以下是三张相关的截图

![Snipaste_2023-04-14_08-23-38](https://user-images.githubusercontent.com/126313472/231910626-61f9e71c-41f4-46a2-ac8e-65138cf09c9e.png)
![removed](https://user-images.githubusercontent.com/126313472/231910745-d80b4b5e-4fe9-4d11-a821-721807a6c0ac.png)

![Snipaste_2023-04-14_08-12-28](https://user-images.githubusercontent.com/126313472/231910525-0a432a44-708f-4c1b-9ad8-03717470be9a.png)

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
这种图片网址都是chatgpt瞎编的，根本不存在，或者以前存在，现在没了，包括有时候参考文献也是
