### ISSUE TITLE
[BUG] 2.68版本上传PDF时前端页面卡死

### ISSUE THREAD

**Issue by 438749902** [binary-husky/chatgpt_academic#466]
**Describe the bug 简述**
* 源代码拉取时间: 2023.4.13 20点左右
* python版本: 3.9.16/3.10.x (两个版本都测试过)
* 问题描述: 每当我在文件上传区上传文件时, 前端页面就会卡死, 失去所有交互功能

**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/49568115/231913934-20d7225d-9db3-4f21-9e83-d19a6e7bde0f.png)
![image](https://user-images.githubusercontent.com/49568115/231913991-168c01d5-77b8-439a-8b37-490d5a05de3e.png)

**Terminal Traceback 终端traceback（如果有）**
```bash
(paper_reader) PS L:\Python\paper_reader\chatgpt_academic> python main.py
 [PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'socks5h://localhost:18899', 'https': 'socks5h://localhost:18899'} 
 [API_KEY] 您的 API_KEY 是: sk-Ss*********mQG*** API_KEY 导入成功 
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
代理配置 socks5h://localhost:18899, 代理所在地：未知，IP查询频率受限
如果浏览器没有自动打开，请复制并转到以下URL：
        （亮色主题）: http://localhost:51667
Running on local URL:  http://0.0.0.0:51667

To create a public link, set `share=True` in `launch()`.
 gpt-3.5-turbo : 0 : 啊啊啊 ..........
Keyboard interruption in main thread... closing server.

```

### 总结
我个人认为是前端的文件上传部分出了问题, 因为在我重新打开网页时是可以交互的, 后端可以继续使用, 也没有报错

**Comment by JiangshuoZhao** [comment]
我情况类似，不同的是上传pdf后，会一直重复上传，结果是C盘的TEMP文件夹内存一直增加，不及时关闭C盘会满。

![uTools_1681445296516](https://user-images.githubusercontent.com/60998131/231939786-bf781c76-9767-4356-aa8c-09915987b747.png)

**Comment by leexiaoyaoLab** [comment]
我也是，在 Edge 浏览器下出现同样问题，在 Chrome 下是正常的。

**Comment by binary-husky** [comment]
> 我情况类似，不同的是上传pdf后，会一直重复上传，结果是C盘的TEMP文件夹内存一直增加，不及时关闭C盘会满。
> 
> ![uTools_1681445296516](https://user-images.githubusercontent.com/60998131/231939786-bf781c76-9767-4356-aa8c-09915987b747.png)

@JiangshuoZhao 降级gradio
