### ISSUE TITLE
多线程翻译时部分线程失败

### ISSUE THREAD

**Issue by Kimagure7** [binary-husky/chatgpt_academic#467]
**Describe the bug 简述**
部分翻译线程重试后仍然失败
**Screen Shot 截图**

**Terminal Traceback 终端traceback（如果有）**

Traceback (most recent call last):
  File "E:\documents\study_zl\chatgpt_academic\crazy_functions\crazy_utils.py", line 186, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
  File "E:\documents\study_zl\chatgpt_academic\request_llm\bridge_chatgpt.py", line 85, in predict_no_ui_long_connection
    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-mKe3usZwPKKgGbTIu8T8osd3 on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",        "type": "requests",        "param": null,        "code": null    }}

能否开放函数允许用户指定线程数量和查询速度，现在失败太多翻译效果太差了

**Comment by binary-husky** [comment]
是开放的，默认max_workers是10 （Openai的限制是20）
``` python
def request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency(
        inputs_array, inputs_show_user_array, llm_kwargs, 
        chatbot, history_array, sys_prompt_array, 
        refresh_interval=0.2, max_workers=10, scroller_max_len=30,
        handle_token_exceed=True, show_user_at_complete=False,
        retry_times_at_unknown_error=2,
        ):
    """
    Request GPT model using multiple threads with UI and high efficiency
    请求GPT模型的[多线程]版。
    具备以下功能：
        实时在UI上反馈远程数据流
        使用线程池，可调节线程池的大小避免openai的流量限制错误
        处理中途中止的情况
        网络等出问题时，会把traceback和已经接收的数据转入输出

    输入参数 Args （以_array结尾的输入变量都是列表，列表长度为子任务的数量，执行时，会把列表拆解，放到每个子线程中分别执行）:
        inputs_array (list): List of inputs （每个子任务的输入）
        inputs_show_user_array (list): List of inputs to show user（每个子任务展现在报告中的输入，借助此参数，在汇总报告中隐藏啰嗦的真实输入，增强报告的可读性）
        llm_kwargs: llm_kwargs参数
        chatbot: chatbot （用户界面对话窗口句柄，用于数据流可视化）
        history_array (list): List of chat history （历史对话输入，双层列表，第一层列表是子任务分解，第二层列表是对话历史）
        sys_prompt_array (list): List of system prompts （系统输入，列表，用于输入给GPT的前提提示，比如你是翻译官怎样怎样）
        refresh_interval (float, optional): Refresh interval for UI (default: 0.2) （刷新时间间隔频率，建议低于1，不可高于3，仅仅服务于视觉效果）
        max_workers (int, optional): Maximum number of threads (default: 10) （最大线程数，如果子任务非常多，需要用此选项防止高频地请求openai导致错误）
        scroller_max_len (int, optional): Maximum length for scroller (default: 30)（数据流的显示最后收到的多少个字符，仅仅服务于视觉效果）
        handle_token_exceed (bool, optional): （是否在输入过长时，自动缩减文本）
        handle_token_exceed：是否自动处理token溢出的情况，如果选择自动处理，则会在溢出时暴力截断，默认开启
        show_user_at_complete (bool, optional): (在结束时，把完整输入-输出结果显示在聊天框)
        retry_times_at_unknown_error：子任务失败时的重试次数

    输出 Returns:
        list: List of GPT model responses （每个子任务的输出汇总，如果某个子任务出错，response中会携带traceback报错信息，方便调试和定位问题。）
    """
```

**Comment by binary-husky** [comment]
在PDF翻译的时候，是max_workers=16

![image](https://user-images.githubusercontent.com/96192199/231931077-eae5ca5c-35b3-4b06-8e11-c6b580400ece.png)

**Comment by binary-husky** [comment]
> **Describe the bug 简述** 部分翻译线程重试后仍然失败 **Screen Shot 截图**
> 
> **Terminal Traceback 终端traceback（如果有）**
> 
> Traceback (most recent call last): File "E:\documents\study_zl\chatgpt_academic\crazy_functions\crazy_utils.py", line 186, in _req_gpt gpt_say = predict_no_ui_long_connection( File "E:\documents\study_zl\chatgpt_academic\request_llm\bridge_chatgpt.py", line 85, in predict_no_ui_long_connection raise RuntimeError("OpenAI拒绝了请求：" + error_msg) RuntimeError: OpenAI拒绝了请求：{ "error": { "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-mKe3usZwPKKgGbTIu8T8osd3 on requests per min. Limit: 3 / min. Please try again in 20s. Contact [support@openai.com](mailto:support@openai.com) if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.", "type": "requests", "param": null, "code": null }}
> 
> 能否开放函数允许用户指定线程数量和查询速度，现在失败太多翻译效果太差了

在我们测试的时候（16线程），并没有发生这种报错。有没有可能是多人在一起用，导致了线程数超过了限制呢？

**Comment by binary-husky** [comment]
@Kimagure7

**Comment by Kimagure7** [comment]
非常感谢

**Comment by Kimagure7** [comment]
> 

不，只有我一个人使用，最后只有3-4个线程能成功，感觉很奇怪。不过我是免费版的chatgpt

**Comment by binary-husky** [comment]
> > 
> 
> 不，只有我一个人使用，最后只有3-4个线程能成功，感觉很奇怪。不过我是免费版的chatgpt

OpenAI刚刚修改了免费用户的并发请求限制，从20改成了3，太不地道了

**Comment by Kimagure7** [comment]
> > > 
> > 
> > 
> > 不，只有我一个人使用，最后只有3-4个线程能成功，感觉很奇怪。不过我是免费版的chatgpt
> 
> OpenAI刚刚修改了免费用户的并发请求限制，从20改成了3，太不地道了…… @Kimagure7

麻...估计服务器压力太大了

**Comment by yanyuechuixue** [comment]
请问能否设置多个 key，以便可以同时使用多个账号？

**Comment by max941126** [comment]
> 请问能否设置多个 key，以便可以同时使用多个账号？

复议，谢谢大佬们
