### ISSUE TITLE
理解PDF文档内容（模仿ChatDPF）报错

### ISSUE THREAD

**Issue by leexiaoyaoLab** [binary-husky/chatgpt_academic#469]
- **(1) Describe the bug 简述**
当文档中存在一行超长的文本时，报错。
报错结果如下图，找到对应报错行，下了断点，发现并不是只要有长文本都会报错，因为对应行重复执行过好几次，前几次都可以顺利处理，后面不知道具体是那句话出了问题。

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/62841450/231942225-c222069e-7a45-481c-95d7-c407a3f976ab.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**
- 样本在此：[劲爆！154页微软GPT研究报告（全中文版).pdf](https://github.com/binary-husky/chatgpt_academic/files/11228789/154.GPT.pdf)

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
你好 刚修改了一下pdf的切割方法：
https://github.com/binary-husky/chatgpt_academic/commit/ff688bb09e383fb2e4479215954884c7f22ef21a

另外这个文档是比较长的中文文档，我们设计时是按英文论文设计的，效果上可能会有偏差

**Comment by binary-husky** [comment]
感谢反馈 @leexiaoyaoLab

**Comment by leexiaoyaoLab** [comment]
> 感谢反馈 @leexiaoyaoLab

辛苦你们，非常感谢！
