### ISSUE TITLE
mac 无法连接到github

### ISSUE THREAD

**Issue by barryab** [binary-husky/chatgpt_academic#47]
Cloning into 'chatgpt_academic'...
fatal: unable to access 'https://github.com/binary-husky/chatgpt_academic.git/': Failed to connect to github.com port 443 after 75018 ms: Couldn't connect to server
cd: no such file or directory: chatgpt_academic

**Comment by binary-husky** [comment]
这个不应该出现在这个项目issue里面吧

gfw哪天开源了发它issue里面吧……
