### ISSUE TITLE
更新最新版本后，文件上传区与Edge浏览器可能存在兼容性问题

### ISSUE THREAD

**Issue by leexiaoyaoLab** [binary-husky/chatgpt_academic#470]
- **(1) Describe the bug 简述**
  
     - 在 Edge 浏览器中，点击文件上传区，选择文件后，无法正常上传文件，无法看到上传文件结果，且页面按钮均不再生效。
     - 使用 Chrome 浏览器没有问题。
- **(2) Screen Shot 截图**
  
![image](https://user-images.githubusercontent.com/62841450/231943131-13a08b80-7f15-49e7-9387-c5453e2b96b6.png)

  
- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

 任意文件均如此。

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
重复 #476

**Comment by binary-husky** [comment]
@leexiaoyaoLab gradio降级
