### ISSUE TITLE
chatgpt_academic 存在安全漏洞

### ISSUE THREAD

**Issue by eggdkk** [binary-husky/chatgpt_academic#478]
- **(1) Describe the bug 简述**
哈喽，我在 chatgpt_academic 中发现了一个高危级别的安全漏洞，但我在项目中没有找到相关反馈邮箱，鉴于安全漏洞提前曝光存在安全风险，能否提供一个联系邮箱，我将安全报告单独发送至邮箱~

**Comment by binary-husky** [comment]
505030475@qq.com

**Comment by binary-husky** [comment]
是取文件的问题吗？

**Comment by eggdkk** [comment]
> [505030475@qq.com](mailto:505030475@qq.com)



> [505030475@qq.com](mailto:505030475@qq.com)

已发邮件，请查收~
