### ISSUE TITLE
【腾讯云微服务器-宝塔Linux面板】：按照直接运行中的步骤来的，下载不了requirements文件，求大佬赐教！

### ISSUE THREAD

**Issue by ShiDing007** [binary-husky/chatgpt_academic#479]
直接按照【直接运行 (Windows, Linux or MacOS)】的步骤来的：
1.下载项目；
2.修改config中的apikey；
3.安装依赖，输入命令直接报错？？什么情况？？
<img width="779" alt="image" src="https://user-images.githubusercontent.com/75664459/232031727-2cf06721-6ba3-469a-9888-729ed978e6a2.png">

**Comment by Marfars** [comment]
你不在项目目录下吧，ls看一下

**Comment by wangfeng35** [comment]
没进目录吧 
cd chatgpt_academic/

**Comment by ShiDing007** [comment]
> 你不在项目目录下吧，ls看一下

在chatgpt_academic 目录下执行命令，是这样的错误提示：

**Comment by ShiDing007** [comment]
> 你不在项目目录下吧，ls看一下

在chatgpt_academic 目录下执行命令，是这样的错误提示：
<img width="904" alt="image" src="https://user-images.githubusercontent.com/75664459/232057584-fa8f2d2a-5ce6-44d1-9528-270bdaf3166e.png">

**Comment by Marfars** [comment]
用Python3试试

**Comment by Marfars** [comment]
> > 你不在项目目录下吧，ls看一下
> 
> 
> 
> 在chatgpt_academic 目录下执行命令，是这样的错误提示：
> 
> <img width="904" alt="image" src="https://user-images.githubusercontent.com/75664459/232057584-fa8f2d2a-5ce6-44d1-9528-270bdaf3166e.png">
> 
> 
> 
> 

用Python3试试
