### ISSUE TITLE
代理配置 socks5h://c38s3.jjvip8.com:31718, 代理所在地查询超时，代理可能无效

### ISSUE THREAD

**Issue by steplead** [binary-husky/chatgpt_academic#483]
- **(1) Describe the bug 简述**

所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
代理配置 socks5h://c38s3.jjvip8.com:31718, 代理所在地查询超时，代理可能无效

请问各路大神，这个应该怎么设置，谢谢！
 
保持原来的也不行，

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/46212839/232168995-86f1a75e-db13-4ea0-9f43-5fd07d672df4.png)

![image](https://user-images.githubusercontent.com/46212839/232169051-e19d9e2c-c58e-451d-ae49-20c0dc156c1e.png)

![image](https://user-images.githubusercontent.com/46212839/232169342-14692d43-a8d4-4f2c-b608-fddcd03a6bc8.png)

![image](https://user-images.githubusercontent.com/46212839/232169137-2ee97dd0-d81c-4e70-8d06-8d71b6e08322.png)

![image](https://user-images.githubusercontent.com/46212839/232169181-c74130fc-762c-4af1-8ef1-d9ad71fffa3d.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
#1
