### ISSUE TITLE
英文润色时会多出几个句子

### ISSUE THREAD

**Issue by paopaopeng** [binary-husky/chatgpt_academic#487]
- **(1) Describe the bug 简述**
输入一句话润色，完成后会继续生成几个相关但不是我输入的句子的润色

- **(2) Screen Shot 截图**

![image](https://user-images.githubusercontent.com/90809771/232181740-7ab3c06c-efa6-4028-9cdb-963c23151115.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
不能指望chatgpt能100%靠谱
