### ISSUE TITLE
输入区设置 clear 按钮

### ISSUE THREAD

**Issue by Drfoolin** [binary-husky/chatgpt_academic#488]
每次在输入区输入一堆东西，然后还要全部选中删除很麻烦，可不可以考虑设置 clear 按钮进行一键清理？

**Comment by binary-husky** [comment]
嗯可以加，但是这个确实是有快捷键的，比如ctrl+a是全选，然后退格就全清除了

**Comment by binary-husky** [comment]
@Drfoolin  加到3.1分支了，可以试试
https://github.com/binary-husky/chatgpt_academic/tree/v3.1

![image](https://user-images.githubusercontent.com/96192199/232210735-6418bdeb-f430-4bc8-9332-8ff90ec8c9a0.png)

**Comment by Meetzyj** [comment]
能否将这个按键固定，每次启动，添加的按钮就消失了
