### ISSUE TITLE
代理配置

### ISSUE THREAD

**Issue by flong1573** [binary-husky/chatgpt_academic#49]
我用的是v2ray，配置试了几次都没成功，显示查不到信息，可能是我没不知道v2ray哪里获取代理类型，还有地址。还有为什么都能科学上网了，还要去设置这个代理。。。。

**Comment by binary-husky** [comment]
duplicate of #1

**Comment by flong1573** [comment]
可以了，只修改了端口号就成功，之前我还把地址还有协议类型什么的都改了
