### ISSUE TITLE
private_upload/2023-04-16-10-53-33" is already in English and appears to be a file or directory name with a specific timestamp. It does not require translation.

### ISSUE THREAD

**Issue by steplead** [binary-husky/chatgpt_academic#495]
- **(1) Describe the bug 简述**
"private_upload/2023-04-16-10-53-33" is already in English and appears to be a file or directory name with a specific timestamp. It does not require translation.

不管文案里是否有英文，或者纯中文，都会出现这个错误。

- **(2) Screen Shot 截图**

![image](https://user-images.githubusercontent.com/46212839/232263731-053c37a0-874e-49f3-bfe4-9ddcc6c2597e.png)
![image](https://user-images.githubusercontent.com/46212839/232263751-189f54f2-56df-4b15-b3b0-738908fa79bc.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/232275200-14c58d1e-dbc8-400e-971c-1eb68c2c6a36.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/232275212-e27a55d1-078a-425a-8ea2-f033f0b93134.png)
