### ISSUE TITLE
多次实验发现chatglm没了上下文持续对话能力

### ISSUE THREAD

**Issue by qiujunhan** [binary-husky/chatgpt_academic#503]
- **(1) Describe the bug 简述**
多次实验发现chatglm没了上下文持续对话能力 版本3.0

- **(2) Screen Shot 截图**
![QQ截图20230416234524](https://user-images.githubusercontent.com/38062062/232324391-06529e05-0036-4261-b6f6-d2c936eb6d3f.png)

![QQ截图20230416234512](https://user-images.githubusercontent.com/38062062/232324486-5edee34b-b9f4-4b2d-a8ef-7a4d6a708356.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
@qiujunhan  您好，是几个bug，已经修复，非常感谢反馈！

![image](https://user-images.githubusercontent.com/96192199/233625483-2a45cc6f-d355-4533-83ec-aded7d9d285e.png)

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/commit/ce1fc3a99909a503880c800857f4f3dd6c9cf59b
