### ISSUE TITLE
考虑其他接入口？

### ISSUE THREAD

**Issue by Xiaoyuyoupang** [binary-husky/chatgpt_academic#504]
目前有个问题就是免费的api很快就会被用完，有没有办法接入类似poe的这种免费网站，这样有些功能我可以不需要消耗自己账号的token，毕竟批量使用的时候消耗的太快了呀。
我在使用一个叫做zotero gpt的插件的时候，就不需要设置api也可以实现翻译，总结等功能，但是不清楚这个插件接入的哪个网站的api

**Comment by jkhcc11** [comment]
他们其实都是调用gpt的api，只不过他们自己购买这个付费的key，然后封装一层提供给人用，先免费，然后就那啥嘛，你懂得。自己用key是最方便的，目前没有其他办法，毕竟目前提供底层服务的ChatGpt、百度、阿里云的也好，都是付费api。

**Comment by binary-husky** [comment]
@jkhcc11  目前接入了api2d
