### ISSUE TITLE
[新功能]GPT转化论文文献引用格式

### ISSUE THREAD

**Issue by WangRongsheng** [binary-husky/chatgpt_academic#506]
```python
把以下bib格式转为AMA格式：@inproceedings{alah2019automatic, title={Automatic Nuclei Detection in Histopathological Images based on Convolutional Neural Networks.}, author={Alah, Roaa Safi Abed and Bilgin, Gokhan and Albayrak, Abdulkadir}, booktitle={BIOSIGNALS}, pages={193--200}, year={2019} }
```

```python
Alah RSA, Bilgin G, Albayrak A. Automatic Nuclei Detection in Histopathological Images based on Convolutional Neural Networks. In: BIOSIGNALS. 2019:193-200.
```

**Comment by systemoutprintlnhelloworld** [comment]
这个换为发送一个链接再调用该函数应该能省一些token，如果能批量转那就更方便了

> ```python
> 把以下bib格式转为AMA格式：@inproceedings{alah2019automatic, title={Automatic Nuclei Detection in Histopathological Images based on Convolutional Neural Networks.}, author={Alah, Roaa Safi Abed and Bilgin, Gokhan and Albayrak, Abdulkadir}, booktitle={BIOSIGNALS}, pages={193--200}, year={2019} }
> ```
> 
> ```python
> Alah RSA, Bilgin G, Albayrak A. Automatic Nuclei Detection in Histopathological Images based on Convolutional Neural Networks. In: BIOSIGNALS. 2019:193-200.
> ```

**Comment by WangRongsheng** [comment]
它被开源：https://huggingface.co/spaces/wangrongsheng/ChatCitation ，但是因为代理它不能被继续做下去了
