### ISSUE TITLE
我是小白，想问问这个要怎么解决

### ISSUE THREAD

**Issue by lsw0210** [binary-husky/chatgpt_academic#51]
![微信截图_20230328205538](https://user-images.githubusercontent.com/95735007/228243151-469dc74b-e186-4c9b-b352-2351f40331ef.png)

**Comment by Anlans** [comment]
是否把API-KEY填入config.py对应的位置了？

**Comment by lsw0210** [comment]
原来是此处误填了key，已改正，谢谢！
