### ISSUE TITLE
上传文件后备选输入区问题

### ISSUE THREAD

**Issue by lanvent** [binary-husky/chatgpt_academic#513]
- **(1) Describe the bug 简述**

开启备选输入区，在上传文件经过插件处理后，备选输入区失效( 提问内容变成文件地址，猜测使用了顶部输入区)

- **(2) Screen Shot 截图**

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/26515464/232482971-b3afa3dd-dce2-4a0a-ab27-245097ace8ae.png">

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

1. 开启备选输入区后，选择理解PDF内容插件
2. 拖拽上传一份PDF，点击理解PDF内容
3. 在备选输入区中，随意输入问题，会出现上述所描述的问题

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
谢谢你，确实是bug，会在下个版本修复。临时的解决方法是：
- 上传文件后，执行函数插件之后，唤出第一输入区，然后把第一输入区清空即可

**Comment by binary-husky** [comment]
v3.1修复
