### ISSUE TITLE
一键解释python项目老是用不了，说找不到路径，路径放input里没有用

### ISSUE THREAD

**Issue by Wangcody123** [binary-husky/chatgpt_academic#514]
- **(1) Describe the bug 简述**
项目一键解释python项目老是用不了，说找不到路径，路径放input里没有用
- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/87231110/232487998-fe491e93-d6d1-4f2b-8d13-b3141654bd0f.png)
- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
如果输入 ./ ，然后再点击解析python项目呢？
