### ISSUE TITLE
请问如何加载chatglm模型，应该改哪里呢

### ISSUE THREAD

**Issue by syh-667** [binary-husky/chatgpt_academic#517]
- **(1) Describe the bug 简述**

- **(2) Screen Shot 截图**

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
v3.1版本还没正式入master分支，你可以先切换到v3.1版本进行测试

**Comment by linrio** [comment]
现在应该支持 ChatGLM 了吧？怎么加载呢？
