### ISSUE TITLE
centos云服务器部署后出现报错：[Json解析不合常规 “error”:]

### ISSUE THREAD

**Issue by Anlans** [binary-husky/chatgpt_academic#52]
Json解析不合常规 “error”: { “message”: “Invalid URL (POST /)”, “type”: “invalid_request_error”, “param”: null, “code”: null }}

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/35157533/228246423-8e36338f-6a43-48b0-9937-814f80d1fbed.png">

---
请问这个问题如何解决？

**Comment by binary-husky** [comment]
config里面改错东西了可能

**Comment by binary-husky** [comment]
#22
