### ISSUE TITLE
是否可以增加一个功能用于统计每个用户的token使用量？

### ISSUE THREAD

**Issue by saladxuanzhi** [binary-husky/chatgpt_academic#520]
和朋友合租API时如果能够根据每个人的实际使用量分摊费用，那将非常方便。另外，登录的授权是否也可以像nginx一样增加外部鉴权接口？非常感谢您开发的程序！

**Comment by qingshuicn** [comment]
如果有都有账号加入到一个组织就可以了 可以看到每一个成员用量
