### ISSUE TITLE
无法使用基本的英译中功能

### ISSUE THREAD

**Issue by xrandomtravel** [binary-husky/chatgpt_academic#524]
- **(1) Describe the bug 简述**
无法使用基本的英译中功能。上传pdf之后，调用路径参数已自动修正到: private_upload/2023-04-18-14-41-55。 然后选择英译中，返回的结果就是翻译 私人上传/2023年4月18日14时41分55秒。 而不是翻译我上传的 pdf。

- **(2) Screen Shot 截图**
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/96520463/232693253-ca8fc2f9-0e46-4ab0-b646-a7325227219e.png">
 

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/232707909-5171e816-d63a-41b6-9b06-41ed8c8bbd51.png)
