### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by geek312** [binary-husky/chatgpt_academic#530]
- **(1) Describe the bug 简述**
You do not have access to chat.openai.com.

- **(2) Screen Shot 截图**

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

不建议调用多线程的开发模式，高频访问openai，很大概率被ban IP，无法访问。

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
多线程不会被ban，不是多线程的问题。注意你的代理IP地址是否干净。然后国内也可以用api2d，开十几个线程都没问题

**Comment by geek312** [comment]
Plus用户，目前重新换代理或者无痕模式可以解决上述问题。
