### ISSUE TITLE
import gradio as gr ModuleNotFoundError: No module named 'fsspec.asyn'

### ISSUE THREAD

**Issue by YijieT** [binary-husky/chatgpt_academic#537]
import gradio as gr
ModuleNotFoundError: No module named 'fsspec.asyn'

**Comment by Jaxychaos** [comment]
me too

**Comment by binary-husky** [comment]
Version of gradio? Did any error pop up when executing `pip install -r requirements.txt`

**Comment by YijieT** [comment]
> Version of gradio? Did any error pop up when executing `pip install -r requirements.txt`

no error messages
