### ISSUE TITLE
请问ChatGLM模型参数下载路径在哪？

### ISSUE THREAD

**Issue by luolundashu** [binary-husky/chatgpt_academic#540]

**Comment by luolundashu** [comment]
就是下载后的模型参数在哪里？看来我的3060 6g显存不够啊，请问多大显存足够？

**Comment by lisanhu** [comment]
建议去看ChatGLM的Github README，我记得最少要6G的显存去Infer，具体的可以看https://github.com/THUDM/ChatGLM-6B，还是需要量化之后的，需要按照文档修改一下使用的模型，下载路径就不知道了，这得看你是怎么运行的，Docker container运行方式应该就在container里，常规Linux运行应该是在Huggingface的缓存目录，~/.cache/huggingface/xxxxxxx

**Comment by luolundashu** [comment]
谢谢
