### ISSUE TITLE
ImportError: cannot import name 'send_telemetry' from 'huggingface_hub.utils' 

### ISSUE THREAD

**Issue by JackeyLoveT** [binary-husky/chatgpt_academic#546]
- **(1) Describe the bug 简述**
运行main.py 后报错ImportError: cannot import name 'send_telemetry' from 'huggingface_hub.utils' 

各位大佬 如何解决？

**Comment by JackeyLoveT** [comment]
有没有人救一下

**Comment by binary-husky** [comment]
严格按安装步骤走
