### ISSUE TITLE
报错：SyntaxError

### ISSUE THREAD

**Issue by Skychou-source** [binary-husky/chatgpt_academic#55]
File "main.py", line 1
SyntaxError: Non-ASCII character '\xe9' in file main.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
依赖安装好了，报错。

**Comment by Skychou-source** [comment]
我在开头加了一行：# -*- encoding: utf-8 -*-
报错变成了：
  File "main.py", line 58
    statusDisplay = gr.Markdown(f"Tip: 鎸塃nter鎻愪氦, 鎸塖hift+Enter鎹㈣. \nNetwork: {check_proxy(proxies)}\nModel: {LLM_MODEL}")

**Comment by binary-husky** [comment]
python2 的生命力这么顽强吗

**Comment by Skychou-source** [comment]
我的版本是3.8



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 晚上11:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [binary-husky/chatgpt_academic] 报错：SyntaxError (Issue #55)




 
python2 的生命力这么顽强吗

**Comment by Skychou-source** [comment]
不好意思已经解决了！

**Comment by wupeng1211** [comment]
> 不好意思已经解决了！

怎么解决的？
