### ISSUE TITLE
API_URL 怎么不见了？

### ISSUE THREAD

**Issue by Pandoxie** [binary-husky/chatgpt_academic#554]
请还是提供一个能在config修改api url的配置，
不然还得去bridge_all 手工修改。谢谢

**Comment by binary-husky** [comment]
还有其他的api endpoint吗，详细说说？

**Comment by Pandoxie** [comment]
> 

不是的。就是用阿里云函数做的openai代理。 这样就不用配置http proxy了。用起来很方便

**Comment by binary-husky** [comment]
> > 
> 
> 不是的。就是用阿里云函数做的openai代理。 这样就不用配置http proxy了。用起来很方便 并且对于openai账号比较友好。。不然容易被封

原来如此，我并不知道有这种玩法😂有相关资料或代码吗，我也希望学习一下

**Comment by Pandoxie** [comment]
> > > 
> > 
> > 
> > 不是的。就是用阿里云函数做的openai代理。 这样就不用配置http proxy了。用起来很方便 并且对于openai账号比较友好。。不然容易被封
> 
> 原来如此，我并不知道有这种玩法😂有相关资料或代码吗，我也希望学习一下
参考这个项目：
[openai-scf](https://github.com/Ice-Hazymoon/openai-scf-proxy)

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/commit/01a377d747a657b5c43d072a46ba5f39d9da0bd0
还原了API_URL的配置

**Comment by binary-husky** [comment]
@Pandoxie 修复了之后，旧版的API_URL依然兼容

新版的配置是这样的
API_URL_REDIRECT  = {"https://api.openai.com/v1/chat/completions": "重定向的URL"}

**Comment by binary-husky** [comment]
@zangqiourun @namezzy

**Comment by binary-husky** [comment]
> @zangqiourun @namezzy

如果没有问题了可以回复一下，我这边没有自定义域名，无法测试

**Comment by Pandoxie** [comment]
> 

works like a charm! 感谢～

**Comment by kotobuki09** [comment]
Can you remove the verification of the API key? I try to use the Azure OpenAI API key with a custom URL. But I failed to pass the verifying key in the beginning

**Comment by namezzy** [comment]
Me too. I also encountered this problem

**Comment by ssxxzzyyddxx** [comment]
![屏幕截图 2024-05-09 192610](https://github.com/binary-husky/gpt_academic/assets/169359939/3a1935d2-6ca5-4445-971a-ca68178e4db7)
按照这个操作一步步做了下来，总是显示未配置代理怎么解决呀
