### ISSUE TITLE
更新版本3以后，反向代理失效

### ISSUE THREAD

**Issue by zangqiourun** [binary-husky/chatgpt_academic#555]
- **(1) Describe the bug 简述**自动更新3.1-2版本后，之前使用的反向代理API失效，无法工作。不知道是否有结局的办法？

- **(2) Screen Shot 截图**

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
在该commit中还原了配置

https://github.com/binary-husky/chatgpt_academic/commit/01a377d747a657b5c43d072a46ba5f39d9da0bd0

**Comment by binary-husky** [comment]
#554

**Comment by zangqiourun** [comment]
好像还是不行
![微信图片_20230421175528](https://user-images.githubusercontent.com/130052096/233609921-ecee34d1-1b69-42b0-afca-f4c5a0365083.png)
![微信图片_20230421180657](https://user-images.githubusercontent.com/130052096/233609927-9120af84-495e-4b46-90f1-4407297bb906.png)
不知道是不是我哪里设置的不对

**Comment by zangqiourun** [comment]
现在是强制使用代理吗？我设置了false，还是会提示让设置代理
