### ISSUE TITLE
您好能否可以自定义API域名

### ISSUE THREAD

**Issue by namezzy** [binary-husky/chatgpt_academic#557]
自定义域名可以避免代理的问题，谢谢！

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/commit/01a377d747a657b5c43d072a46ba5f39d9da0bd0
还原了API_URL的配置

**Comment by binary-husky** [comment]
#554

**Comment by namezzy** [comment]
感谢！已恢复自定义API_URL, 但是API KEY没法自定义，因为我现在用的是微软AZURE的OpenAI 它和chatgpt的不太一样，是32位的字母加数字,这个是否能自定义呢。
