### ISSUE TITLE
增加调整背景的选项

### ISSUE THREAD

**Issue by yuzhangsjtu** [binary-husky/chatgpt_academic#559]
请问方便增加一个调整背景色调的选项吗？默认的黑底白色，看得时间长了之后，眼前全是条纹🤣

**Comment by binary-husky** [comment]
可以把 浏览器地址栏的/?__dark-theme=true去掉，换成明色背景

**Comment by yuzhangsjtu** [comment]
可以的！谢谢！原来运行提示里也有，没有注意到。sorry
