### ISSUE TITLE
之前可以使用，几天过后突然加载不进去，页面一直处于loading状态

### ISSUE THREAD

**Issue by HXF-hxf-bit** [binary-husky/chatgpt_academic#560]
- **(1) Describe the bug 简述**
之前是可以使用的，但今天使用时页面一直处于loading状态

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/64690220/233641703-bec1e0d1-2c7c-4581-9675-1b0fa56444b6.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
尝试关闭代理排查故障？
