### ISSUE TITLE
python scripts/run.py --config-name=wanjinyou dataset_name=example case_name=ngp_fox mode=train Error executing job with overrides: ['dataset_name=example', 'case_name=ngp_fox', 'mode=train'] Traceback (most recent call last):   File "scripts/run.py", line 59, in main     make_image_list(data_path, conf['dataset']['factor'])   File "scripts/run.py", line 35, in make_image_list     f = open(os.path.join(data_path, 'image_list.txt'), 'w') FileNotFoundError: [Errno 2] No such file or directory: '/cephfs/yuanweizhong/project/f2-nerf/outputs/2023-04-23/17-50-45/data/example/ngp_fox/image_list.txt'

### ISSUE THREAD

**Issue by sunshineywz123** [binary-husky/chatgpt_academic#577]
- **(1) Describe the bug 简述**

python scripts/run.py --config-name=wanjinyou dataset_name=example case_name=ngp_fox mode=train
Error executing job with overrides: ['dataset_name=example', 'case_name=ngp_fox', 'mode=train']
Traceback (most recent call last):
  File "scripts/run.py", line 59, in main
    make_image_list(data_path, conf['dataset']['factor'])
  File "scripts/run.py", line 35, in make_image_list
    f = open(os.path.join(data_path, 'image_list.txt'), 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/cephfs/yuanweizhong/project/f2-nerf/outputs/2023-04-23/17-50-45/data/example/ngp_fox/image_list.txt'

- **(2) Screen Shot 截图**

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
？
