### ISSUE TITLE
无法使用openai-sb的自定义API

### ISSUE THREAD

**Issue by 0xZhangxu** [binary-husky/chatgpt_academic#579]
- **(1) Describe the bug 简述**
使用openai-sb的API, 在config.py里修改了API key和API url后, 无法使用

openai-sb网址: https://openai-sb.com/

**Comment by binary-husky** [comment]
不识别他们的API KEY，可以找他们发适配PR

**Comment by 0xZhangxu** [comment]
https://github.com/binary-husky/chatgpt_academic/blob/cb0241db787268b31663072e200c94414b0decd1/toolbox.py#L417

将这个位置的sk改成sb即可, 或者直接return true

**Comment by sunjianan9900** [comment]
API_URL 这个配置是要自己在config.py里面添加的吗？

**Comment by 0xZhangxu** [comment]
修改config.py里的API_URL_REDIRECT即可:
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.openai-sb.com/v1/chat/completions"}
