### ISSUE TITLE
NEWBING_COOKIES在哪找到呢？

### ISSUE THREAD

**Issue by xinzhaobuxuan** [binary-husky/chatgpt_academic#584]
- **(1) Describe the bug 简述**

- **(2) Screen Shot 截图**

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
https://github.com/binary-husky/chatgpt_academic/blob/v3.3/config.py
```
...............................

# OpenAI模型选择是（gpt4现在只对申请成功的人开放，体验gpt-4可以试试api2d）
LLM_MODEL = "gpt-3.5-turbo" # 可选 ↓↓↓
AVAIL_LLM_MODELS = ["gpt-3.5-turbo", "api2d-gpt-3.5-turbo", "gpt-4", "api2d-gpt-4", "chatglm", "newbing"]

# 本地LLM模型如ChatGLM的执行方式 CPU/GPU
LOCAL_MODEL_DEVICE = "cpu" # 可选 "cuda"

# 设置gradio的并行线程数（不需要修改）
CONCURRENT_COUNT = 100

# 设置用户名和密码（不需要修改）（相关功能不稳定，与gradio版本和网络都相关，如果本地使用不建议加这个）
# [("username", "password"), ("username2", "password2"), ...]
AUTHENTICATION = []

# 重新URL重新定向，实现更换API_URL的作用（常规情况下，不要修改!!）
# 格式 {"https://api.openai.com/v1/chat/completions": "在这里填写重定向的api.openai.com的URL"}
API_URL_REDIRECT = {}

# 如果需要在二级路径下运行（常规情况下，不要修改!!）（需要配合修改main.py才能生效!）
CUSTOM_PATH = "/"

# 如果需要使用newbing，把newbing的长长的cookie放到这里
NEWBING_STYLE = "creative"  # ["creative", "balanced", "precise"]
NEWBING_COOKIES = """
your bing cookies here
"""
```

**Comment by zdevc** [comment]
- 要求
一个已经通过候补名单的微软账户 https://bing.com/chat (必填)
需要在 New Bing 支持的国家（中国大陆需使用VPN）
- 检查访问权限 (必需)
安装最新版本的 Microsoft Edge
或者, 您可以使用任何浏览器并将用户代理设置为Edge的用户代理 (例如Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51). 您可以使用像 "User-Agent Switcher and Manager" [Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg) 和 [Firefox](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) 这样的扩展轻松完成此操作.
打开 [bing.com/chat](https://bing.com/chat)
如果您看到聊天功能，就准备就绪
- 获取身份验证 (必需)
打开edge、chrome或firefox浏览器扩展商店，安装 cookie editor 扩展
移步到 bing.com
打开扩展程序
点击右下角的"导出" (将会把内容保存到你的剪贴板上)
找到config.py文件中NEWBING_COOKIES = """your bing cookies here"""，粘贴全部内容替换“your bing cookies here”

参考https://github.com/acheong08/EdgeGPT/blob/master/docs/README_zh.md

**Comment by Hylouis233** [comment]
给楼上大佬补充一下，
使用“ cookie editor 扩展”进行复制时，
格式选择 "Export as JSON"
即最终格式应为：
    {
        "domain": ".bing.com",
        "expirationDate": 
        "hostOnly": ,
        "httpOnly": ,
        "name": "
        "path": "/",
        "sameSite": ""
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "X=rebateson"

**Comment by YH721** [comment]
![image](https://user-images.githubusercontent.com/59163676/235335024-6fb65026-8323-4d7a-8139-a91bb2a706d0.png)
为什么用chatgpt这个代理地址可以适用，转换成new bing就无法使用了？
