### ISSUE TITLE
请问 ValueError: Unrecognised argument(s): encoding 错误什么原因

### ISSUE THREAD

**Issue by l1uw3n** [binary-husky/chatgpt_academic#6]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/24247258/227750744-e9f6c2f5-ec5e-4ae5-aa92-4921051a751e.png">

**Comment by binary-husky** [comment]
其他地方找到是python版本太低：https://github.com/edoardottt/twitterbot2/issues/47#issue-1089071662

请升级python版本到最新 (3.9以上)，或者直接使用docker方案^_^

**Comment by D32vd** [comment]
docekr现在也报这个错了

**Comment by binary-husky** [comment]
刚我把docker改了 @D32vd 其实只要把encoding那个参数去掉就行了

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/227776071-9754f81f-ec8a-4b5b-98e3-67c4b088848b.png)
又加了个try except。
版本问题正让人头大
