### ISSUE TITLE
因为config最后两行代码折腾了半天

### ISSUE THREAD

**Issue by realzsy** [binary-husky/chatgpt_academic#60]
if API_KEY == "sk-此处填API秘钥": 
     assert False, "请在config文件中修改API密钥, 添加海外代理之后再运行"

建议换个别的检测方式吧，我把开头和这里都填了key，就一直报错，最后才搞明白这一句检验，对于我们这种想尝试的小白，真是能被这个问题卡住直到放弃。

**Comment by weiyoubest** [comment]
看了你的我才明白 哈哈哈哈哈哈哈哈  我也是搞到现在

**Comment by weiyoubest** [comment]
我还在想是不是我的URL填错了

**Comment by realzsy** [comment]
> 看了你的我才明白 哈哈哈哈哈哈哈哈  我也是搞到现在

我更扯，我最先没看到第一句就只填了最后这里的key，然后没有报错，但是网页会显示网络代理有问题，其实是因为前面根本没填key嘛，然后我把第一句key了就疯狂报错，最后还是去看
Huggingface 测试：https://huggingface.co/spaces/qingxu98/gpt-academic
这里才发现把最后两句注释掉了，然后才读明白这句话是检验开头是不是填了key。

**Comment by weiyoubest** [comment]
> > 那个网络代理地址怎么查的？ 我程序可以运行，但是到了网页界面就代理报错
> 
> 我是部署在外国服务器，就没启用代理。 如果你是本地，不要填成所谓代理服务器的地址了，这里很多人貌似没理解，应该是填那个软件的本地地址，一般ssr小飞机是127.0.0.1:1080, clash是127.0.0.1:7890，诸如此类吧。

还是不行，明天再说吧 先睡了

**Comment by dok4everak47** [comment]
直接注释掉就能运行了

**Comment by realzsy** [comment]
> 直接注释掉就能运行了

是的，或者不改动也可以，小白真的会一股脑的修改成自己的key

**Comment by binary-husky** [comment]
改了，真的真的没想到这能形成误解

![image](https://user-images.githubusercontent.com/96192199/228485830-78ca6db2-8b17-4ddf-8fdf-48d1354bb2a8.png)

**Comment by realzsy** [comment]
> 改了，真的真的没想到这能形成误解
> 
> ![image](https://user-images.githubusercontent.com/96192199/228485830-78ca6db2-8b17-4ddf-8fdf-48d1354bb2a8.png)
> 

我们这种菜鸡是真的会误解的，辛苦了。
