### ISSUE TITLE
请问代理网络的地址在哪里看？

### ISSUE THREAD

**Issue by weiyoubest** [binary-husky/chatgpt_academic#61]
# 代理网络的地址，打开你的科学上网软件查看代理的协议(socks5/http)、地址(localhost)和端口(11284)
    proxies = { "http": "http://glados-config.com:7890", "https": "https://glados-config.com:7890", }  
这样写不对吗？程序可以运行，但是运行结束后在网页界面输入问题就返回[local] Request timeout, network error. please check proxy settings in config.py.

**Comment by oneLuckyman** [comment]
你这个 glados-config.com: 是不对的吧，一般都是 localhost: 或者 127.0.0.1: 才对吧

**Comment by xuekai1024** [comment]
确保电脑上代理开着，最好是全局
1：WIN10点击右下角网络图标
2：点击网络和internet设置
3：点击代理会看到地址和端口
4：python 的proxies语法是proxies = {
   'http': 'http://proxy.example.com:8080',
   'https': 'http://secureproxy.example.com:8090',
}
因此把你的http://glados-config.com:7890和https://glados-config.com:7890替换成http://上面查到的地址和端口

**Comment by xuekai1024** [comment]
> # 代理网络的地址，打开你的科学上网软件查看代理的协议(socks5/http)、地址(localhost)和端口(11284)
> ```
> proxies = { "http": "http://glados-config.com:7890", "https": "https://glados-config.com:7890", }  
> ```
> 
> 这样写不对吗？程序可以运行，但是运行结束后在网页界面输入问题就返回[local] Request timeout, network error. please check proxy settings in config.py.
确保电脑上代理开着，最好是全局
1：WIN10点击右下角网络图标
2：点击网络和internet设置
3：点击代理会看到地址和端口
4：python 的proxies语法是proxies = {
'http': 'http://proxy.example.com:8080/',
'https': 'http://secureproxy.example.com:8090/',
}
因此把你的[http://glados-config.com:7890和https://glados-config.com:7890替换成http://上面查到的地址和端口](http://glados-config.xn--com:7890https-w59v//glados-config.com:7890%E6%9B%BF%E6%8D%A2%E6%88%90http://%E4%B8%8A%E9%9D%A2%E6%9F%A5%E5%88%B0%E7%9A%84%E5%9C%B0%E5%9D%80%E5%92%8C%E7%AB%AF%E5%8F%A3)

**Comment by qi-github-ui** [comment]
> 
![01230A87](https://user-images.githubusercontent.com/73466589/228459181-f860d19b-82de-4baf-bae5-9d8f48f48cc0.png)

**Comment by xuekai1024** [comment]
> 查不到代理的地址，怎么办呀 ![image](https://user-images.githubusercontent.com/45426458/228466754-dbf9b0a2-d5d7-4a50-8c52-eb01952a94dc.png)

![1](https://user-images.githubusercontent.com/101375134/228468266-22933d9a-4be6-4dc6-a295-efbbb1c85b6f.png)
请注意看 ，最后一个是代理

**Comment by adrianzzk** [comment]
![image](https://user-images.githubusercontent.com/96020706/228481009-4028cc4c-7c4b-445d-b3b1-9ea7f490e7ae.png)
试过了，但无效果

**Comment by weiyoubest** [comment]
> > # 代理网络的地址，打开你的科学上网软件查看代理的协议(socks5/http)、地址(localhost)和端口(11284)
> > ```
> > proxies = { "http": "http://glados-config.com:7890", "https": "https://glados-config.com:7890", }  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样写不对吗？程序可以运行，但是运行结束后在网页界面输入问题就返回[local] Request timeout, network error. please check proxy settings in config.py.
> > 确保电脑上代理开着，最好是全局
> > 1：WIN10点击右下角网络图标
> > 2：点击网络和internet设置
> > 3：点击代理会看到地址和端口
> > 4：python 的proxies语法是proxies = {
> > 'http': 'http://proxy.example.com:8080/',
> > 'https': 'http://secureproxy.example.com:8090/',
> > }
> > 因此把你的[http://glados-config.com:7890和https://glados-config.com:7890替换成http://上面查到的地址和端口](http://glados-config.xn--com:7890https-w59v//glados-config.com:7890%E6%9B%BF%E6%8D%A2%E6%88%90http://%E4%B8%8A%E9%9D%A2%E6%9F%A5%E5%88%B0%E7%9A%84%E5%9C%B0%E5%9D%80%E5%92%8C%E7%AB%AF%E5%8F%A3)

太详细了，感谢！把https改成http就好了

**Comment by adrianzzk** [comment]
同上，蹲一个

**Comment by adrianzzk** [comment]
@lnnocencezz 已解决 可能你协议类型出错了？ 可以去1#看看

**Comment by binary-husky** [comment]
代理问题汇总到 #1
