### ISSUE TITLE
请问如何能保存log以及能否增加token的使用量？

### ISSUE THREAD

**Issue by Suiiiii** [binary-husky/chatgpt_academic#62]
RT
Q1: 如何能保存对话内容？
Q2: 能否如川虎gpt一样显示token的使用量，以及当前使用了多少，还有多少token？
谢谢

**Comment by Suiiiii** [comment]
我是在Docker中使用的

**Comment by binary-husky** [comment]
Q1: 对话内容保存在日志中 ./gpt_log/chat_secrtes.log
Q2: 暂无此功能，欢迎pr
