### ISSUE TITLE
Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'

### ISSUE THREAD

**Issue by ruantiancheng** [binary-husky/chatgpt_academic#63]
你好，我根据readme的指示完成了所有的配置工作。但是在运行python main.py的时候弹出的网页无法访问此网站，且是“localhost 拒绝了我们的连接请求”。  
以下是错误日志：Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B18A7A2A60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')  
我使用的是Vs code，目前身处美国。

**Comment by Xiaoyuyoupang** [comment]
1、False改为True应用代理
2、将“socks5h”改为socks5
3、查看魔法里面的port 并对应修改

**Comment by ruantiancheng** [comment]
可是我人就在美国 还需要代理吗
    	Get Outlook for iOS
    
  

 From: ***@***.*** ***@***.***> on behalf of Xiaoyuyoupang ***@***.***>Sent: Tuesday, March 28, 2023 9:51 PMTo: chatgpt_academic ***@***.***>Cc: 492493590 ***@***.***>; author ***@***.***>Subject: Re: [binary-husky/chatgpt_academic] Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。' (Issue #63) 
1、False改为True应用代理
2、将“socks5h”改为socks5
3、查看魔法里面的port 并对应修改

**Comment by 413162826** [comment]
3、查看魔法里面的port 并对应修改
这个怎么看我的魔法没有显示
![image](https://user-images.githubusercontent.com/34346573/228544089-e0bfabe0-a6a2-426f-b440-fa2686abb397.png)

**Comment by binary-husky** [comment]
@ruantiancheng 尝试升级urlib，建议使用conda环境或docker环境。
国外网路不需要代理，代理相关配置保持关闭即可
