### ISSUE TITLE
海外使用依然报错让配置代理

### ISSUE THREAD

**Issue by xiaxin1998** [binary-husky/chatgpt_academic#66]
不在国内 运行main 还是显示让添加代理
网络代理状态：未配置。无代理状态下很可能无法访问。
Traceback (most recent call last):
  File "/home/jlyu/chatgpt_academic/predict.py", line 12, in <module>
    try: from config_private import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
ModuleNotFoundError: No module named 'config_private'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jlyu/chatgpt_academic/main.py", line 3, in <module>
    from predict import predict
  File "/home/jlyu/chatgpt_academic/predict.py", line 13, in <module>
    except: from config import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
  File "/home/jlyu/chatgpt_academic/config.py", line 29, in <module>
    assert False, "请在config文件中修改API密钥, 添加海外代理之后再运行"
AssertionError: 请在config文件中修改API密钥, 添加海外代理之后再运行

**Comment by beifeng1937** [comment]
不添加代理只是警告，程序依然运行，真正报错的是你没有添加API

**Comment by xiaoliwe** [comment]
> 

整个 config.py 文件只有 2 处需要修改 API_KEY, 填写正确的key 后，依然是这个错误就有问题了.

**Comment by Hanserwei** [comment]
所有题主找到问题了么，我也是这个报错，config.py不是只需要填一个key，最后两行不是检验你填没填的的吗

**Comment by xiaxin1998** [comment]
> 所有题主找到问题了么，我也是这个报错，config.py不是只需要填一个key，最后两行不是检验你填没填的的吗

我填了一个key就可以了 不过感觉润色英语有点慢

**Comment by xiaoliwe** [comment]
只填一个API_Key ? 代理设置为 True了么？

**Comment by xiaxin1998** [comment]
> 只填一个API_Key ? 代理设置为 True了么？

是的 只填写第一个地方 文件最后的那个地方是不填的 如果你填了才会报错 海外的代理设置不需要的
