### ISSUE TITLE
ImportError: cannot import name dataclass_transform好像是调用API的库出错，怎么解决呢？

### ISSUE THREAD

**Issue by ponyling** [binary-husky/chatgpt_academic#67]
File "D:\anaconda\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ImportError: cannot import name dataclass_transform

请问大家有遇到这个问题吗？
好像是调用API的库出错，怎么解决呢？

**Comment by clippersman** [comment]
同问

**Comment by henniudeaniu** [comment]
同问

**Comment by xuekai1024** [comment]
可以详细描述一下，哪一步出的问题。
试试这个方法
https://stackoverflow.com/questions/74451907/import-spacy-error-cannot-import-name-dataclass-transform

**Comment by ponyling** [comment]
谢谢，我现在把这个问题解决啦。我将报错的库都卸载再重装后就没事了（应该是之前版本的问题）

**Comment by xuekai1024** [comment]
> 谢谢，我现在把这个问题解决啦。我将报错的库都卸载再重装后就没事了（应该是之前版本的问题）

好的，客气了

**Comment by Nanlim-wow** [comment]
我也碰到了
pip uninstall fastapi
pip install fastapi
解决了这个问题
