### ISSUE TITLE
ImportError: cannot import name dataclass_transform  

### ISSUE THREAD

**Issue by honminga** [binary-husky/chatgpt_academic#68]
请问大家 ImportError: cannot import name dataclass_transform  如何解决

**Comment by Xiaoyuyoupang** [comment]
1、False改为True应用代理
2、将“socks5h”改为socks5
3、查看魔法里面的port 并对应修改

**Comment by honminga** [comment]
已经解决，重新创建了一个Python3.9的环境，导入配置后是可以的
