### ISSUE TITLE
配置文件里面有个错误？

### ISSUE THREAD

**Issue by Xiaoyuyoupang** [binary-husky/chatgpt_academic#69]
你是不是多加了个h，正确的应该如下，
proxies = { "http": "socks5://localhost:11284", "https": "socks5://localhost:11284", }

**Comment by Orangon** [comment]
我按照你说的删去了h之后，报错[local] Request timeout, network error. please check proxy settings in config.py.

**Comment by Xiaoyuyoupang** [comment]
1、False改为True应用代理
2、将“socks5h”改为socks5     这一步我不确定，因为我改了之后才好用
3、查看魔法里面的port 并对应修改
4、魔法里面是全局模式

**Comment by binary-husky** [comment]
没错的，这好像和新版本的urlib有关系，请问python版本和其他依赖库版本是？

**Comment by Xiaoyuyoupang** [comment]
好像是 我后来又改成“socks5h了 ，又好用了 哎 玄学

**Comment by binary-husky** [comment]
我加个tag #1
