### ISSUE TITLE
中文项目解析问题

### ISSUE THREAD

**Issue by wei-seven** [binary-husky/chatgpt_academic#71]
解析项目时总是会报错
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 89: invalid start byte

初步估计是中文解码问题，求解决。

![image](https://user-images.githubusercontent.com/63662290/228418815-440e17ab-7c6a-4596-b6bf-c71c2d22cb8e.png)

**Comment by binary-husky** [comment]
暂没能支持非utf8编码
1、将文件转换至utf8： https://blog.csdn.net/rothschild666/article/details/125610103
2、欢迎任何相关的兼容性pr
