### ISSUE TITLE
为什么不显示呢？弹出浏览器后页面是空白

### ISSUE THREAD

**Issue by Jacksonk1997** [binary-husky/chatgpt_academic#72]
如题

**Comment by xiaozhangyongqin** [comment]
俺也一样

**Comment by dafei5350** [comment]
什么原因没找到，不过你可以试试下面这个方法
先把代理关掉，然后在启动项目，项目启动成功后，再打开代理，就可以正常使用了，

**Comment by fileban** [comment]
![无标题](https://user-images.githubusercontent.com/129386797/228815562-544ee8fb-1857-4808-83c7-e5ac7da5b44e.png)
请问有解决吗，我弹出这个界面

**Comment by binary-husky** [comment]
是不是错误地打开了代理的地址，而非web地址？注意区分一下
