### ISSUE TITLE
代理地址怎么填都不对

### ISSUE THREAD

**Issue by gxandys** [binary-husky/chatgpt_academic#73]
用的v2rayN，socks://127.0.0.1:10808 和 http://127.0.0.1:10809 这两个代理在其他连接chatgpt的应用上是可以用的。
但在您的 config.py 里，不论怎么填都回“代理所在地查询超时，代理可能无效”：
proxies = { "http": "socks5h://127.0.0.1:10808", "https": "socks5h://127.0.0.1:10809", } 
proxies = { "socks": "socks5h://127.0.0.1:10808", "http": "socks5h://127.0.0.1:10809", } 
proxies = { "http": "http://127.0.0.1:10809", "https": "https://127.0.0.1:10809", } 
proxies = { "socks": "socks://127.0.0.1:10808", "http": "http://127.0.0.1:10809", } 
以上几种写法都没法用。求指导。

**Comment by doyle1996** [comment]
proxies = { "http": "127.0.0.1:10809", "https": "127.0.0.1:10809", }

**Comment by gxandys** [comment]
> proxies = { "http": "127.0.0.1:10809", "https": "127.0.0.1:10809", }

多谢！成了！
