### ISSUE TITLE
请问用Ghelper翻墙能用吗，如果能用的话怎么配置本地代理？

### ISSUE THREAD

**Issue by Dota-Ball** [binary-husky/chatgpt_academic#74]

**Comment by binary-husky** [comment]
不清楚Ghelper是神马, 相关issue #1

**Comment by researcher-tiger** [comment]
同问用Ghelper怎么配置本地代理

**Comment by abbymeimei520** [comment]
我参考的这个用Ghelper实现了，成功使用。https://loukky.com/archives/1337#gsc.tab=0

**Comment by mark98307** [comment]
可否介绍一下如何用Ghelper实现的？

**Comment by poincarelee** [comment]
@abbymeimei520 
hi, how do you solve this problem? I set the proxy in ghelper but when running the check_proxy.py, an error occured: 
代理配置 http://127.0.0.1:7890, 代理所在地查询超时，代理可能无效
