### ISSUE TITLE
访问本地项目时显示无权限

### ISSUE THREAD

**Issue by dojjy9192** [binary-husky/chatgpt_academic#75]
**1. 调用本地文件的测试项目无权限：**
在线的润色功能可以无问题运行，到需要访问本地时一直有如下报错

`找不到本地项目或无权访问: ./crazy_functions/test_project/latex/attention`

**2. 上传文件后，提示不能阅读文件**

```
[Local Message] 收到以下文件: private_upload\2023-03-29-11-38-51

private_upload\2023-03-29-11-38-51\xxxx.pdf

调用路径参数已自动修正到: private_upload/2023-03-29-11-38-51

现在您可以直接选择任意实现性功能
```

 _**提问：**_
`解释文件的大纲内容，帮我阅读这篇文献并总结内容。private_upload/2023-03-29-11-38-51`

**回复**
`抱歉，我没有权限访问私人上传的文件。如果您想让我帮助阅读和总结文献，请提供更具体的信息或问题，以便我能够为您提供更准确的回答和帮助。`

系统情况：
在WIN的pycharm中运行，以前设置过使用虚拟环境运行。不知道是否和这个有关系？
非CS出身，代码和环境设置上比较小白。

**Comment by binary-husky** [comment]
不支持pdf，读pdf有更为专业的工具 #27

**Comment by dojjy9192** [comment]
谢谢后一个问题的解答。
关于第一个问题，不仅是pdf的问题，测试的文件也显示无法访问。
