### ISSUE TITLE
十八刀能用多久，过期了是否就无法使用了？

### ISSUE THREAD

**Issue by Lhy330782** [binary-husky/chatgpt_academic#80]

**Comment by jkhcc11** [comment]
可以登录你账号进去看那个过期时间，18$应该是早期的账号，应该可以到6月还是7月1号来着，用完就不行了。

**Comment by lingfengchencn** [comment]
6月1号，看你咋用了。但是还可以用挺久的。具体的看
[https://platform.openai.com/account/usage](https://platform.openai.com/account/usage)
