### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by aslanshen** [binary-husky/chatgpt_academic#83]
![3bc8c26ba9ea74d1492eb711720992b](https://user-images.githubusercontent.com/69495002/228450990-fb335d8a-dc75-4263-9532-a364572d3042.png)
使用香港服务器用squid搭建代理，用check_proxy.py和我自己PC端测试都是成功的，但是一旦运行就报错，可能是哪里出了问题？

**Comment by xuekai1024** [comment]
提示代理可能无效，有没有试过直接用，是否可以使用？我这边显示查询超时但是可以正常使用。

**Comment by aslanshen** [comment]
> 

尝试过，在网页上也是超时，socks5/http协议和squid搭建的proxy是不是不同，可能是这个问题？

**Comment by xuekai1024** [comment]
> 

这个就不清楚了，我用的不是自己搭的

**Comment by xuekai1024** [comment]
> 香港不在开通地区里面啊

对，把这个忘了

**Comment by aslanshen** [comment]
> 



> 香港不在开通地区里面啊

但是我可以在服务器上直接curl到，还有另一个项目也可以直接访问

**Comment by realzsy** [comment]
> > 
> 
> 
> 
> > 香港不在开通地区里面啊
> 
> 但是我可以在服务器上直接curl到，还有另一个项目也可以直接访问

我也不是太懂哈，应该只是能访问但是没权限返回不了数据吧，网页版也能打开，但是会提示不支持该国家，也并不是直接封禁。

**Comment by binary-husky** [comment]
代理问题汇总 #1
