### ISSUE TITLE
输入显示不正确

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [binary-husky/chatgpt_academic#84]
输入：
```
    txt.submit(**predict_args)
    txt.submit(**empty_txt_args)
    submit_event = submitBtn.click(**predict_args)
    submitBtn.click(**empty_txt_args)
```
输出：
![image](https://user-images.githubusercontent.com/58595459/228452382-824c14da-c9d1-4f07-9ff4-765c6286a650.png)

**Comment by binary-husky** [comment]
无法复现？
![image](https://user-images.githubusercontent.com/96192199/228486896-74503e7d-78d8-4c44-9b21-4a94d67170f1.png)

**Comment by Okabe-Rintarou-0** [comment]
我是windows下的环境 直接在pycharm 中复制多行会出现该问题 我估计可能是换行符的问题

**Comment by Okabe-Rintarou-0** [comment]
找到原因了 /t tab会让markdown认为这是一个子层级 然后导致渲染在同一行，见下面的例子：
![1680083104034](https://user-images.githubusercontent.com/58595459/228495245-c08da029-c1d8-461f-b1ca-ea0f1342090d.png)
我在 pr 把第一行加入了 \<p\>标签内，测试了不会产生这种结果

**Comment by binary-husky** [comment]
非常感谢您的帮助，已merge
