### ISSUE TITLE
代理超时或无效

### ISSUE THREAD

**Issue by 2Red1Blue** [binary-husky/chatgpt_academic#85]
代理配置为proxies = {"http": "http://10.151.54.131:7890", "https": "https://10.151.54.131:7890", }或proxies = {"http": "http://127.0.0.1:7890", "https": "https://127.0.0.1:7890", }都会请求超时，代理本身没有问题，可以正常访问，全局代理也尝试了还是不行，是怎么回事呢

**Comment by xigrug** [comment]
> 代理配置为proxies = {"http": "http://10.151.54.131:7890", "https": "https://10.151.54.131:7890", }或proxies = {"http": "http://127.0.0.1:7890", "https": "https://127.0.0.1:7890", }都会请求超时，代理本身没有问题，可以正常访问，全局代理也尝试了还是不行，是怎么回事呢

我也是这个问题

**Comment by xuekai1024** [comment]
> > 代理配置为proxies = {"http": "http://10.151.54.131:7890", "https": "https://10.151.54.131:7890", }或proxies = {"http": "http://127.0.0.1:7890", "https": "https://127.0.0.1:7890", }都会请求超时，代理本身没有问题，可以正常访问，全局代理也尝试了还是不行，是怎么回事呢
> 
> 我也是这个问题

参考我在Issues:请问代理网络的地址在哪里看？中的回复

**Comment by doraemonlei** [comment]
我这里虽然显示超时，但是功能还可以用

**Comment by binary-husky** [comment]
与代理模式无关。 issue汇总 #1

**Comment by binary-husky** [comment]
查询ip用的这个网站，查的太频繁也会被拒绝
https://ipapi.co/
