### ISSUE TITLE
clash for windows代理

### ISSUE THREAD

**Issue by chencn2020** [binary-husky/chatgpt_academic#9]
你好，请问你知道clash for windows如何查看代理的协议(socks5/http)、地址(localhost)和端口(11284)吗，一直都找不到

**Comment by chencn2020** [comment]
找到解决方法了，直接在浏览器输入：https://ipapi.co/json/
然后在浏览器上右键->检查->网络->ctrl+r
![image](https://user-images.githubusercontent.com/60561885/227757562-91c5f0f4-3721-47dd-800a-5785b4cbd9f7.png)
把这个cv进config即可
![image](https://user-images.githubusercontent.com/60561885/227757576-8d9a12a7-8833-4f7d-901d-c32dd7b8f489.png)
![image](https://user-images.githubusercontent.com/60561885/227757602-ca5456ca-9946-4e4e-9bf9-c8810e20c206.png)

**Comment by binary-husky** [comment]
66

**Comment by Pandaxia8** [comment]
感谢

**Comment by zhaoyongq** [comment]
设置完成，也不行，
![image](https://user-images.githubusercontent.com/76219134/228356345-a8539ffe-1dc3-4e89-9d60-94b9eb3f6d67.png)

![image](https://user-images.githubusercontent.com/76219134/228356511-cbeacdda-1ce8-4b5e-a17b-e9400ad1ad16.png)

**Comment by chencn2020** [comment]
> 

需要把USE_PROXY变量设置为True

**Comment by chencn2020** [comment]
> 设置完成，也不行， ![image](https://user-images.githubusercontent.com/76219134/228356722-60e1dfa6-b36b-4199-9ce7-19d51e76d674.png)
> 
> ![image](https://user-images.githubusercontent.com/76219134/228356511-cbeacdda-1ce8-4b5e-a17b-e9400ad1ad16.png)

需要把USE_PROXY变量设置为True

**Comment by LiSonglin-xidian** [comment]
![image](https://user-images.githubusercontent.com/53897055/228414581-8510ec5d-09f6-481f-82a6-502c4847df7f.png)
你好，我这样设置后代理设置还是检查不通过

**Comment by chencn2020** [comment]
> ![image](https://user-images.githubusercontent.com/53897055/228414581-8510ec5d-09f6-481f-82a6-502c4847df7f.png) 你好，我这样设置后代理设置还是检查不通过

ip地址的冒号后面是端口号，是一个纯数字。建议改成127.0.0.1:7890而不是127.0.0.1:7890/

**Comment by zhaoyongq** [comment]
> > 设置完成，也不行， ![image](https://user-images.githubusercontent.com/76219134/228356722-60e1dfa6-b36b-4199-9ce7-19d51e76d674.png)
> > ![image](https://user-images.githubusercontent.com/76219134/228356511-cbeacdda-1ce8-4b5e-a17b-e9400ad1ad16.png)
> 
> 需要把USE_PROXY变量设置为True

没注意到，谢谢啦

**Comment by guaner007** [comment]
> 找到解决方法了，直接在浏览器输入：https://ipapi.co/json/ 然后在浏览器上右键->检查->网络->ctrl+r ![image](https://user-images.githubusercontent.com/60561885/227757562-91c5f0f4-3721-47dd-800a-5785b4cbd9f7.png) 把这个cv进config即可 ![image](https://user-images.githubusercontent.com/60561885/227757576-8d9a12a7-8833-4f7d-901d-c32dd7b8f489.png) ![image](https://user-images.githubusercontent.com/60561885/227757602-ca5456ca-9946-4e4e-9bf9-c8810e20c206.png)

确实可以

**Comment by LiSonglin-xidian** [comment]
> 

感谢回信，python check_proxy测试错误，但是我直接使用python main 也可以使用，我也不知道咋回事儿了~~

**Comment by chumingqian** [comment]
> 
[666] * 666

**Comment by yuluo-yx** [comment]
我将前面的http和https删掉就可以使用了
![image](https://user-images.githubusercontent.com/77964041/229522710-f55e7fd3-746b-471c-abad-a254651853cd.png)

**Comment by zc619340855** [comment]
![image](https://user-images.githubusercontent.com/13324789/230313553-356a6e77-3e82-497d-b300-14d3b9cba77d.png)
![image](https://user-images.githubusercontent.com/13324789/230313565-29ea8412-4320-4e5d-bc45-fb3453cd999c.png)
我按照上面的配的，不知道为什么一直不行。。。

**Comment by Luvmylife** [comment]
你好，我用的是clash for window，下面是详细配置。请问大佬“代理所在地查询超时，代理可能无效”接下来该怎么做呀。（浏览器可以正常访问google）
![image](https://user-images.githubusercontent.com/65061935/230710793-c0aecafc-45ad-4227-aad2-45b18ffe8083.png)
![image](https://user-images.githubusercontent.com/65061935/230710900-6d9cc33a-d67a-48e5-850d-00f695e6fba7.png)
![image](https://user-images.githubusercontent.com/65061935/230710876-587a0d27-5708-4264-abc1-1c55d8759e29.png)
第三张的报错信息明显比较多，还说需要访问https://ipapi.co/ratelimited/

**Comment by lowestindorm** [comment]
配置完成之后显示：OpenAI以账户额度不足为由，拒绝服务？
ChatGPT还需要充值吗？之前没遇到过啊

**Comment by healerlalala** [comment]
啊啊啊啊啊啊终于好了！可行！Mac端亲测也有效！

**Comment by qiujingtao** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/30258435/a9c7c023-8cf7-4540-86a3-bbec42300f52)
老哥，我还是不行啊啊啊，我的代理好像有auto的加密方式，这个有影响吗

**Comment by q-sue** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/58127162/0582bbd9-7457-4a6f-b63c-093ad75ee82a)
stdout: [1;32m [ENV_VAR] 成功读取环境变量proxies [0m
stdout: [ENV_VAR] 尝试加载USE_PROXY，默认值：False --> 修正值：    False                                                                                           
stdout: [1;32m [ENV_VAR] 成功读取环境变量USE_PROXY [0m
stdout: [1;31m [PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。 [0m


我也不行

**Comment by kingstar2020sdu** [comment]
感谢，clash for windows的网络超时问题已解决

**Comment by DonRa1den** [comment]
我这代理正常显示的但是报   WARNING:  Invalid HTTP request received.    ，插件全关了也不行

**Comment by 130abc** [comment]
代理配置 https://127.0.0.1:1082, 代理所在地查询超时，代理可能无效, 请问要怎么办呢

**Comment by tooeqwwwi** [comment]
> 感谢，clash for windows的网络超时问题已解决

怎么解决的，兄弟。
我也是用clash，一直卡在这儿

![image](https://github.com/binary-husky/gpt_academic/assets/43226360/2125952e-3613-4ab1-a74b-3dca02271540)

**Comment by 130abc** [comment]
输对端口号就好。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tooeqwwwi ***@***.***&gt;
发送时间: 2024年4月21日 14:27
收件人: binary-husky/gpt_academic ***@***.***&gt;
抄送: 130abc ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [binary-husky/gpt_academic] clash for windows代理 (Issue #9)





  
感谢，clash for windows的网络超时问题已解决
  
怎么解决的，兄弟。
 我也是用clash，一直卡在这儿
 
image.png (view on web)
