### ISSUE TITLE
docker部署完访问不到

### ISSUE THREAD

**Issue by HongJunShan** [binary-husky/chatgpt_academic#90]
大佬好   按照步骤操作最后docker run -dit --name gpt-academic -p 9988:9988 gpt-academic
然后用ip+9988端口访问显示拒绝了连接请求，docker管理器和docker ps命令都显示成功运行   对外端口9988
检查防火墙端口和ip_forward也是开放的，在服务器运行这个显示
[root@VM-4-6-centos ~]# curl localhost:9988
curl: (56) Recv failure: Connection reset by peer
日志部分内容：
URL http://localhost:36424
Running on local URL:  http://0.0.0.0:36424
两台服务器搭建起来都是访问不了，请问可能是哪里没设置对？

**Comment by realzsy** [comment]
下面显示的端口不是36424吗？
config里面的端口改了吗？

**Comment by Okabe-Rintarou-0** [comment]
docker -p <host port>:<guest port>

**Comment by HongJunShan** [comment]
> docker run -p <host port>:<guest port>

感谢大佬
