### ISSUE TITLE
我的运行之后没有弹出窗口？

### ISSUE THREAD

**Issue by xigrug** [binary-husky/chatgpt_academic#91]
(base) Tools\chatgpt_academic-master>python main.py
网络代理状态：运行。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
代理配置 socks5h://localhost:7890, 代理所在地查询超时，代理可能无效
Running on local URL:  http://0.0.0.0:6414

**Comment by binary-husky** [comment]
7890 端口用的clash？

    # 填写格式是 [协议]://  [地址] :[端口] ，
    # 例如    "socks5h://localhost:11284"
    # [协议] 常见协议无非socks5h/http，例如 v2*** 和 s** 的默认本地协议是socks5h，cl**h 的默认本地协议是http
    # [地址] 填localhost或者127.0.0.1（localhost意思是代理软件安装在本机上）
    # [端口] 在代理软件的设置里，不同的代理软件界面不一样，但端口号都应该在最显眼的位置上

**Comment by xigrug** [comment]
> 把0.0.0.0换成localhost，也就是http://localhost:6414

这个解决了问题！不知道怎么可以设置浏览器直接弹窗
