### ISSUE TITLE
V2ray代理配置问题

### ISSUE THREAD

**Issue by liuqy21** [binary-husky/chatgpt_academic#92]
请问下，使用VMess协议应该怎样写欸
vmess or ws?（试了试都不太行）
![image](https://user-images.githubusercontent.com/42308039/228477885-cb558318-e535-48e5-9bb7-03fb4fc301af.png)

关于IP和端口，win系统抓取的代理地址和 myip这类网站抓取的代理服务器地址不相同，应该以哪一个为准呢？

**Comment by doraemonlei** [comment]
`proxies = { "http":"socks5h://localhost:10809", "https":"socks5h://localhost:10809"`
这样写就行，虽然现实超时，但是是可以用的
