### ISSUE TITLE
MacOs使用git下载一直不成功

### ISSUE THREAD

**Issue by barryab** [binary-husky/chatgpt_academic#93]
Cloning into 'chatgpt_academic'...
fatal: unable to access 'https://github.com/binary-husky/chatgpt_academic.git/': Failed to connect to github.com port 443 after 75019 ms: Couldn't connect to server
cd: no such file or directory: chatgpt_academic

**Comment by lingfengchencn** [comment]
总所周知，网络问题，不能clone就```download zip```。
