### ISSUE TITLE
[一些建议]input框还是太小了

### ISSUE THREAD

**Issue by lixibi** [binary-husky/chatgpt_academic#94]
RT 多行输入还是不方便，如果适当调整会更好用。

希望采纳，感谢分享。

**Comment by binary-husky** [comment]
UI问题很让人头大的，一方面是gradio限制太多，另一方面是众口难调，这个您可以尝试在main.py中调整

例如第50行插入 txt.style(height=200) 试试

**Comment by binary-husky** [comment]
#342 @lixibi
