### ISSUE TITLE
剖析整个代码之后写入markdown之后 ，文档显示乱码

### ISSUE THREAD

**Issue by YongCun1** [binary-husky/chatgpt_academic#95]
剖析整个代码之后写入markdown之后 ，文档显示乱码

**Comment by binary-husky** [comment]
旧代码有bug，请检查chatgpt_academic/toolbox.py, line 55, 或者直接git pull新代码亦可

```
with open(f'./gpt_log/{file_name}', 'w', encoding = 'utf8') as f:
```

**Comment by YongCun1** [comment]
感觉更新后的分析py项目文件剖析的太笼统了，能不能精细一下

**Comment by binary-husky** [comment]
目前的问题是 
最后一步总结大工程源代码时，总是文本过长、token溢出，
目前的方法是直接二分丢弃掉后面一半文字，这太过于粗暴，让有效信息大量丢失

解决方法还在想，有想法的话可以交流
