### ISSUE TITLE
Request timeout, network error. please check proxy settings in config.py

### ISSUE THREAD

**Issue by wangqian97** [binary-husky/chatgpt_academic#98]
求助，我用的win11系统，代理用的clash机场梯子，配置如下：
![image](https://user-images.githubusercontent.com/35491970/228508097-a0228997-4b74-4b04-acb6-0904ff2c75ad.png)
config文件如下：
![image](https://user-images.githubusercontent.com/35491970/228508228-0404f969-4626-4a75-9cd6-f2663cd7af55.png)
![image](https://user-images.githubusercontent.com/35491970/228508662-d07fdf13-4862-4379-ad6f-edd909137373.png)
y一直不成功，请大佬们看看

**Comment by binary-husky** [comment]
能查到代理所在地吗？如果能查到，说明机场太多人用ChatGPT了，或者纯粹的网络卡

查不到 -> #1

**Comment by wangqian97** [comment]
![image](https://user-images.githubusercontent.com/35491970/228511091-0a6dab3c-6552-4400-adc2-aa143a87c609.png)
可以查到，请问有其他好一些的梯子推荐吗
